### ISSUE TITLE
V6 - initialize another form will remove props?

### ISSUE THREAD

**Issue by reyhansofian** [erikras/redux-form#1018]
Hi, thanks for your hard work on this.

I'm using `6.0.0-alpha.13`. I'm trying to pass another props to the component like this 

```js
<Field name="method" onChange={this.onChange.bind(this)}
  component={(method) =>
    <PaymentsMethodSelect 
        method={method} 
        paymentMethods={this.props.initialValues.paymentMethods} />
  }
/>
```

I have multiple form that get initialized on the first load. When another form got initialized, my `paymentMethods` props is gone. Is there a way to fix it?

**Comment by ooflorent** [comment]
Add `paymentMethods` to the field.

```js
<Field name="method"
  onChange={this.onChange.bind(this)}
  paymentMethods={this.props.initialValues.paymentMethods}
  component={field =>
    <PaymentsMethodSelect
      method={field}
      paymentMethods={field.paymentMethods}
    />
  }
/>
```

However, there are some minor issues with your code:

- You should not create `onChange` this way. `onChange` will hold a new closure on every render and `Field` will fail to block rendering within `shouldComponentUpdate`
- Same pitfall with `component`
- Passing a closure to `component` is deprecated because it causes trouble during the reconciliation phase of React. You should use a reference to a component here.
- `initialValues` should be serializable and so contains only scalars, objects and arrays (no function)

Since `Field` will pass down its props to its `component`, you could refactor your code like this:

```js
class MyForm extends Component {
  constructor() {
    super()

    // Binding `onChange` here prevent recreating the bound closure within `render`
    this.onChange = this.onChange.bind(this)
  }

  onChange(event) {
    // ...
  }

  render() {
    return (
      <form onSubmit={this.props.handleSubmit}>
        <Field name="method" onChange={this.onChange}
          paymentMethods={this.props.initialValues.paymentMethods}
          component={EnhancedPaymentsMethodSelect}
        />
      </form>
    )
  }
}

const EnhancedPaymentsMethodSelect = field => (
  <PaymentsMethodSelect
    method={field}
    paymentMethods={field.paymentMethods}
)
```

Using `EnhancedPaymentsMethodSelect` you don't have to change `PaymentsMethodSelect` to get `method` and `paymentMethods`. However, refactoring `PaymentsMethodSelect` to remove this abstraction would be a better idea.

**Comment by reyhansofian** [comment]
thanks for the explanation @ooflorent! never taught it can works like that. 👍
