### ISSUE TITLE
V6.0 - Initial value for nested object disappears after blur

### ISSUE THREAD

**Issue by q42jaap** [erikras/redux-form#1047]
Possibly related to #1023 

I have a form with nested props separated in 2 'sections':
```
section1.prop1
section2.prop2
section2.prop3
```
The initialValues are set to `{section1: {}, section2: {}}`

What I'm seeing is that when the field for `section1.prop1` is blurred, `section1` is removed from `values` in the redux store (it is present when the form is initialized).
However, When I focus `section2.prop2`, the `section1: {}` comes back into the `values` in the redux store.

**Comment by ooflorent** [comment]
What version of Redux Form are you using? v5 or v6?

**Comment by q42jaap** [comment]
v6.0.0-alpha.14

**Comment by erikras** [comment]
The issue here is that `redux-form` treats your `initialValues` the same as if you had not provided any, _since you are not providing any __field values___. So in order to to back to pristine when you enter a value in `section1.prop1` and then remove it again, it deletes any now-empty container structures as well.

For example, say you started with no initial values:


---

values: `undefined`
pristine: `true`

---

Action: Enter a value of `foo` for `section1.prop1`.

---

values: `{ section1: { prop1: 'foo' } }`
pristine: `false`

---

Action: Clear value of `section1.prop1`.

In order to get back to `undefined`, after it deletes a value, it has to recurse up the path, and if the container is `{}`, it sets it to `undefined`.

---

values: `undefined`
pristine: `true`

---

#### Conclusion

If you're not going to specify any values for an actual _field_, you should not provide an empty structure for `initialValues`.

Make sense?

**Comment by q42jaap** [comment]
That makes sense. Too bad it doesn't fit my particular needs though.

Lets discuss further at stackoverflow?
https://stackoverflow.com/questions/37480486/redux-form-how-to-add-object-for-nested-properties
