### ISSUE TITLE
V6 Alpha 14 - initialValues not updating

### ISSUE THREAD

**Issue by sQVe** [erikras/redux-form#1084]
I've been struggling for way to long trying to get my form component to update with **initialValues** passed as **props**. Is this a bug or am I just being slow today?

This is the component I'm having problems with. **initialValues** does update correctly and `{initialValues && initialValues.username}` views the correct values. The **Field** does not update tho...

``` js
import React, { PropTypes } from 'react';
import { Field, reduxForm } from 'redux-form';

function UserInformation(props) {
  const { handleSubmit, initialValues } = props;
  console.log('INITIALVALUES', initialValues);
  return (
    <div className="user-information">
      <h2>Kontaktinformation</h2>
      {initialValues && initialValues.username}
      <form className="user-form" onSubmit={handleSubmit}>
        <Field
          className="user-form__username"
          name="username"
          component="input"
          type="text"
          placeholder="Användarnamn"
        />
      </form>
    </div>
  );
}

UserInformation.propTypes = {
  handleSubmit: PropTypes.func,
  isReadingUser: PropTypes.bool.isRequired,
  initialValues: PropTypes.object,
};

export default reduxForm({
  form: 'user-form',
})(UserInformation);
```

**Comment by olegkalyta** [comment]
To update initial values in form, now it's not enough to just change that prop.
Please see [documentation on 0.15](http://redux-form.com/6.0.0-alpha.15/examples/initializeFromState/):

> You may only initialize a form component once via initialValues. If you wish to change the "pristine" values again, you will need to dispatch the INITIALIZE action yourself (using the action creator provided by redux-form).

**Comment by erikras** [comment]
Published `enableReinitialize` flag in [`v6.0.0-rc.1`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.1).

**Comment by nhjk** [comment]
@erikas I don't understand the rationale in #370. I think default behavior should go back to what it used to be. React is designed so that when a component's prop changes, the component itself changes. Having a prop ignored after the first time is counter intuitive. It should be the responsibility of the library consumer to maintain their initialValues if they want to keep partial changes a user made to a form.

**Comment by nhjk** [comment]
On further thought it seems the use case presented in #370 is separate and should not be handled with initialValues. Maybe have a separate prop values that gets merged with initialValues.

**Comment by OKNoah** [comment]
Must `initialValues` be passed in as a prop ala `<MyComponent initivialValues={this.props.initialValues} ... />`, or can `load()` be used in the component itself?

I'm also having trouble getting `Field`s to show new values.

**Comment by jtbennett** [comment]
Slightly different topic, but still related to initialValues in v6. I'm using rc3.

In my form's mapStateToProps(), I'm trying to set initialValues.  I have a deeply-nested object in another reducer, and my form allows editing of just some of the values.

```
someState: {
  editableInForm: "foo",
  notEditableInForm: "bar",
  ... many more not-editable fields
  nested: {
    alsoEditable: "baz",
    notEditable: "qux"
    ... many more nested not-editable fields
  }
}
```
My form has only the fields: `someState.editableInForm` and `someState.nested.alsoEditable`.  I want to use `registeredFields` to limit what is in `initialValues`, rather than putting all of `someState` in there.  

My form's `mapStateToProps()` seems to be called at least twice. On the first call, the form state (`state.form.myForm`) does not exist.  On subsequent calls, it does exist, with all of the `registeredFields` available. I have to set `enableReinitialize=true` so that the fields get the values the second time around. 

* Are the multiple calls to `mapStateToProps()` expected or am I doing something wrong?

* Since v6 connects the fields to state, rather the form, shouldn't we be able to set `initialValue` on each field, rather than on the form as a whole?

* Or am I doing this completely wrong? :)

Thanks!
