### ISSUE TITLE
[v6] In Production

### ISSUE THREAD

**Issue by olegkalyta** [erikras/redux-form#1099]
Can i use latest alpha version in production? Does anybody have such experience?
Do you plan to change API much untill release?
When do you plan to release stable version?

Thanks!

**Comment by brotzky** [comment]
We're using alpha-13 in production and are upgrading to alpha-14 in a few days.

**Comment by erikras** [comment]
Yeah, it's _very_ stable. However, I cannot promise that there will be no more breaking changes between now and `v6.0.0`. If there are, rest assured that they will be well documented on the [Releases Page](https://github.com/erikras/redux-form/releases) as if on a major version bump.

I have not yet migrated my production app only because it's using the `plugin()` and `normalize()` APIs that have not yet been published in `v6`. But if you're starting a new app, I would _**definitely**_ start with `v6`.

**Comment by andrewmclagan** [comment]
Also using it in production.

**Comment by clayne11** [comment]
I am also using it in production.

**Comment by gustavohenke** [comment]
I'm closing this issue because it's a question, and has already been answered by folks :)
