### ISSUE TITLE
How to send boolean value from select ?

### ISSUE THREAD

**Issue by whatifif** [erikras/redux-form#1150]
I am trying to select a boolean as stat's value like the below:

`<select className="form-control" {...stat} >`
                  `<option value={false}>falsy stat</option>`
                  `<option value={true}>truthy stat</option>`
`</select>`

But redux-form sends this as a string ( 'false' or 'true'). 

How can I correctly send this value as boolean?
Should I convert the received value to boolean after it is received?

**Comment by erikras** [comment]
`redux-form` just reads from `event.target.value` from the DOM, and the DOM will only give strings, since all the values you give eventually get outputted into `<option value="true">` in the DOM. So yes, you have to cover the received value to boolean after it is received.

Coming soon in `v6`, we will have a `normalize` prop that you can pass a function to convert the DOM value to whatever you want, so you will be able to do something like:

```js
const toBoolean = value => value === 'true'
...
<Field name="stat" component="select" className="form-control" normalize={toBoolean}>
  <option value={false}>falsy stat</option>
  <option value={true}>truthy stat</option>
</Field>
```

**Comment by whatifif** [comment]
Thanks for your kind explanation.
I look forward to using V6 soon.

Cheers.

**Comment by oliviertassinari** [comment]
I couldn't make the above example work. I ended-up normalizing the data just before sending them to the server.
