### ISSUE TITLE
[V5] removeField is broken

### ISSUE THREAD

**Issue by EnoahNetzach** [erikras/redux-form#1169]
When removing fields from an array field, strange behaviors occur:

 - when I have two blank fields, I fill the first then delete it, it behave as if I deleted the second one;
 - when I have multiple fields filled, and then remove one in the middle, the right field is removed, but the last two fields become identical;
 - when I try to reset a form with multiple fields in it, it doesn't clear every field.

N.B.: the second and third bugs occur only if the first bug is performed.

It can be seen [here](http://redux-form.com/5.2.5/#/examples/deep).

I think this is because the state of the field is supposed to be an array, but with the first step it becomes an object (I have not seen deeply enough in this, but I noticed this behavior in other related issues I had)

**Comment by alurim** [comment]
@EnoahNetzach I've had to debug this problem before as well! It's all about React `key`s. First you have two fields:

Field 1 key=1 value=""
Field 2 key=2 value=""

then you fill the first field

Field 1 key=1 value="foobar"
Field 2 key=2 value=""

then you delete the first field

Field 2 key=? value=?

but what's Field 2's key? If you look at the example the key is just the index in the fields array so it's 1!

Field 2 key=1 value=?

so even though redux-form's internal state says that Field 2's value is `''`, the React reconciler says oh hey! An input with key=1, that's already rendered (as "foobar"). Let's not rerender it since we don't have to.

Only when you then touch the field again does it rerender it. To solve this problem you can do several things but the key is to make the field's key unique. An easy way to solve this would be to have each field's key be its index plus the length of the fields array.

Does that make sense?

**Comment by EnoahNetzach** [comment]
@alurim no, it doesn't, if done as you are suggesting this scenario is broken:

| fields | _**a**_ |  _**b**_ |  _**c**_ |
|---|---|---|---|
| initial keys | 3 | 4 | 5 |
| _**c**_ is removed | 2 | 3 | x |

Clearly react thinks the new _**b**_ is the old _**a**_.

The only proper way I can think of is to have an object instead of an array of fields, with initialization-generated unique keys.

**Comment by chehonte** [comment]
@EnoahNetzach I have the same problem and don't found the solution how to fix it. Are you fix this problem? Can you help me?

**Comment by EnoahNetzach** [comment]
@chehonte by bookkeeping.

Basically I made an HOC retaining local state about the `FieldArray`s, disabling the possibility to delete entries directly, but keeping note in the local state of the active indexes.

Basically I had to make a proxy between the real `FieldArray` and the one I am passing down as props.

If you want more details I'll try to upload a gist ASAP (no time now, unfortunately).

**Comment by chehonte** [comment]
@EnoahNetzach I would be very thankful if you upload an example to gist! Thank you!

**Comment by EnoahNetzach** [comment]
https://gist.github.com/EnoahNetzach/a953f6b4f35ad7de6cd794b8a85c896d

@chehonte I think something like this should work.
Unfortunately I have not tested it thoroughly as in my case I used it for keeping track of files and we changed the handling of uploaded files soon after I did this.

Also, I compacted it down to one file (plus an usage example).
