### ISSUE TITLE
React Native firing validate on each change

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#117]
I see the synchronous validate function being fired on each change in a TextInput field.

Ideally, I would want this synchronous validation to be executed onBlur. The reason is that on slower phones processing a validation function with each keyboard input can lead to frame drops in typing. I already experienced this with tcomb form. And I can totally see this happening on more larger validation functions.

I'm new to redux-form and trying to wrap my head around it, so it might already be possible without me realizing. Does this suggestion make sense?

**Comment by erikras** [comment]
The sync validation does, indeed, happen on each render. This is because normally sync validations are simply checking for string length, equality, or regex matching. It is the intent of the `touched` flags to denote when a validation error should be shown.

Depending on design intuition and use case, it might make sense to hide a validation message (e.g. a `> 140 character tweet`) immediately when the 141st character is removed. What's why it happens on every render.

Are you really seeing dropped frames in production (i.e. not running redux-devtools)? If it's really a problem, perhaps a config setting could be provided to override the default behavior.

**Comment by erikras** [comment]
`v3.0` is much more efficient than `v2`. [I recommend upgrading](https://github.com/erikras/redux-form/releases/tag/v3.0.0
