### ISSUE TITLE
Removing Dynamic Array Values When Form is Cancelled

### ISSUE THREAD

**Issue by switmac** [erikras/redux-form#1170]
I have a dynamic form structure where the user can add dynamic fields.
It is a modal so when the modal opens the update data must be loaded.
When the user clicks the CANCEL button, I want to discard the changes made to revert the form in 
its original state. However, if the user clicks SAVE then I should reload the new data from the http response.

What I've done so far, 
1. Whenever the form opens, I set the data to its fields including a nested array in `onOpen` method.
2. I can add the fields dynamically when I need updates.
3. When I click CANCEL then close modal, I call the `resetform()` and remove all the values in the array  with reference to this solution https://github.com/erikras/redux-form/issues/474.
4. When I click open again and set the data like STEP 1, the data I added previously which must be discarded is still in the list.

My possible solution which I thinks is tedious, is controlling the index when calling `addField(value, index)`, store it in an array and iterate the array when calling `removeField(index)` during cancel.
And this will be implemented in all my array fields.   

Is there a proper way to handle this? Thanks!

**Comment by danielrob** [comment]
@switmac do you still need help with this question? The question is somewhat challenging to follow. For the most part, `initialValues` can be used to update formValues from the server - if you have [`enableReinitialize`](http://redux-form.com/7.0.1/docs/api/ReduxForm.md/#-code-enablereinitialize-boolean-code-optional-) prop set to true, when `initialValues` changes, the formValues will be updated. 

After that [`reset()`](http://redux-form.com/7.0.1/docs/api/Props.md/#-code-reset-function-code-) will always return you to your initialValues. 

I'll eagerly close this since the question is over a year old, but we can re-open if the question represents an issue with redux-form, and don't hesitate to ask further questions.
