### ISSUE TITLE
Access whole store when doing validation

### ISSUE THREAD

**Issue by johnz** [erikras/redux-form#118]
It'd be nice if could access full store when doing validation,  a common use case would be 
- loaded a list of todo items from store and render it
- add a new todo item which already exist 
- when doing validation if could access store to get a list of todos then could stop adding duplicate todo item

**Comment by erikras** [comment]
Duplicate checking is more in the realm of async validation, I think. For two reasons.

1. It's probably too complex to do on every keypress.
2. If your list is long enough, it could potentially require talking to the server.

**Comment by johnz** [comment]
that make sense, but can we have access full state in asyncValidate, I would do validation against other state in store but not talk to server.

**Comment by johnz** [comment]
its a bit like redux thunk, it has access to dispatch and state

**Comment by erikras** [comment]
Thunk as access to `getState` which is not the same as `state`. What we don't want is to register your form as a listener for every change to any state anywhere in the application. I'll need to think a little more on this.

**Comment by antoinejaussoin** [comment]
Hi, I actually need the exact same thing, but for another reason altogether: translations.

Let me explain: I need to display the validation error messages in various languages, and the only way to get the current language is by accessing the store, or the props.

Would be great to have a third argument to the validate function, so that redux-form passes either the store or the component props

**Comment by erikras** [comment]
@antoinejaussoin The sync validation function is given the props. See bottom of [this docs page](http://erikras.github.io/redux-form/#/api/reduxForm).

```js
validate(formData, props)
```

That should be good enough, right?

**Comment by antoinejaussoin** [comment]
It is!
I couldn't get it to work at first because the "currentLanguage" prop is set by another High Order Component, and in this case, the order matter... so I just realised I had to set my "translation" component after the reduxForm one (which means it's evaluated before), so the prop is correctly set on the reduxForm one (I hope this makes sense).

Thanks for your quick reply!

**Comment by erikras** [comment]
To @johnz's original point, in `v3`, you can connect to any part of the store that you want with your own `mapStateToProps`, and then access them in validation as I mentioned in my previous comment.

**Comment by kristian-puccio** [comment]
just to clarify to do this in asyncValidate you would dispatch a validation action that returned a promise.
The action creator then has access to getState if it returns a function and your using thunk.

Seems a bit overkill to dispatch an action that doesn't result in a reducer being called just to get access to getState.

Or maybe I'm thinking about this wrong?

**Comment by demongaorui** [comment]
@erikras 

The sync validation `validate(formData, props)` works well for me, thank you very much.

**Comment by swp44744** [comment]
@erikras @demongaorui  can you elaborate more on how to use `validate(formData, props)`?? I am also in a need to access store data in validate to make my syncvalidation more dynamic

**Comment by dapicester** [comment]
@swp44744 I do this, I map the state slice I need using `connect` on my decorated form component:
```javascript
MyForm = reduxForm(/* ... */)(MyForm)
MyForm = connect(state => ({ foo: state.foo })(MyForm)
```
Then the data is available in the `props` argument of `validate`: 
```javascript
const validate = (values, { foo }) => { /* ... */ }
```

**Comment by swp44744** [comment]
@dapicester Thank you brother!! It worked...

**Comment by edward-hong** [comment]
Hi this is what I have:
```
const validate = ({ selection, customSelection }, props) => {
	console.log(props)
	const errors = {}
	if (!selection) errors.selection = 'Please select an option'

	if (selection === "I'd like a custom option" && !customSelection) {
		errors.customSelection = 'Please enter your custom selection'
	}
	return errors
}

const mapStateToProps = ({ poll, form, auth }) => ({ poll, form, auth })

export default reduxForm({
	form: 'vote',
	validate
})(connect(mapStateToProps, actions)(withRouter(PollDetails)))
```

The problem here is that I look in my console and I don't see `poll` or `auth` in my props. So I try changing the order between connect and reduxForm:

```
export default connect(mapStateToProps, actions)(
	reduxForm({
		form: 'vote',
		validate
	})(withRouter(PollDetails))
)
```

Now I'm getting `auth` and `poll` in the props of my validate function but my actual PollDetails component doesn't have access to this.props.form.vote - it's undefined. Is there some way "merge" or run concurrently the two HOC of reduxForm and connect?

Sorry if this sounds awfully like it should be asked in Stack Overflow but to me it kinda seems like it could be a feature request.
