### ISSUE TITLE
wizard form example uses component state, isn't that anti-redux? 

### ISSUE THREAD

**Issue by jasan-s** [erikras/redux-form#1219]
The example [here ](http://redux-form.com/6.0.0-alpha.15/examples/wizard/) of the wizard form uses componeent state to keep track of page location. I am curious if in this case its acceptable to have a local component state instead of storing page location data in the APP redux state.

**Comment by ooflorent** [comment]
It is perfectly fine. State is part of React and is not a bad practice. Over-reduxing things is.

**Comment by slavierouse** [comment]
Hi @ooflorent I understand and agree that over-reduxing things is not desirable. However the front page of this library library promises "to enable an html form in React to use Redux to store all of its state". Wizard step is part of the form's state. I think it's a good use case for storing in redux because I want to share it with a progress bar that's living outside of the form. I'm trying not to write my own form reducer on top of the library's to handle this issue. Any advice?

<img width="908" alt="screen shot 2018-01-27 at 7 57 00 pm" src="https://user-images.githubusercontent.com/6227867/35478819-455cba88-039c-11e8-862b-0ebf870a4888.png">
