### ISSUE TITLE
[v6.rc1] field array validation problem

### ISSUE THREAD

**Issue by mauvew** [erikras/redux-form#1279]
For the field array example in the examples [doc](http://redux-form.com/6.0.0-rc.1/examples/fieldArrays/), validation seems doesn't work very well.

1. displaying errors when the input is not empty
![image](https://cloud.githubusercontent.com/assets/14197252/16579619/799c527a-4298-11e6-9bc5-7f0a4fbb3503.png)
2. not able to display error: No more than five hobbies allowed
![image](https://cloud.githubusercontent.com/assets/14197252/16579651/97ccc81a-4298-11e6-8567-49d9f320bff2.png)
3. when clicking submit with only club name filled in, no able to submit(which is correct), but also not having error: 'At least one member must be entered'. This can be quite confusing
![image](https://cloud.githubusercontent.com/assets/14197252/16579759/2a350e56-4299-11e6-83e0-ab09b814f1a9.png)

**Comment by stevengoldberg** [comment]
Can confirm that validation seems to have been broken in `rc1`. I have a `reduxForm` with a `validate` function. The `validate` function returns an object that looks like:

```
{ email: [ 'This is not a valid email address'] }
```

but when I call `fields.map` in the component I'm passing to `FieldArray`, the `error` prop that gets passed along with the `emails[0]` member is `undefined` instead of my error string.

**Comment by davepies** [comment]
I can also confirm the issue as per @stevengoldberg's description. For me it's happening in `rc2`.

The `fields.error` prop is always set to 'undefined'.

Within the example the line `{fields.error && <li className="error">{fields.error}</li>}` never renders.

**Comment by erikras** [comment]
Should be fixed in [`6.0.0-rc.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.3).
