### ISSUE TITLE
Using store for validation

### ISSUE THREAD

**Issue by mohebifar** [erikras/redux-form#128]
I've been using this library and it works great for most cases. One only issue that I've had is that for the cases that validation and submission are done in the same API, I have to dispatch the action in the `asyncValidate` function. However, it might be possible to subscribe to redux state for getting errors and validation result. Something like this:

```es7
@connectReduxForm({
  form: 'contact',
  fields: ['name', 'address', 'phone'], 
  validate: validateContact,
  storeValidate: (state) => { return { errors: state.contact.errors, loaded: state.contact.loaded }; },
  action: (dispatch, data) => { return dispatch(submitAction(data)); }
})
class FormComponent extends Component {}
```

**Comment by erikras** [comment]
That's very intriguing. I'll think about it.

**Comment by maarekj** [comment]
+1 for this feature

**Comment by erikras** [comment]
Oh, I might have misunderstood. You can totally return validation errors from your submit API. See #151.

**Comment by mohebifar** [comment]
This idea makes it easy to submit a form in the action creators.

**Comment by erikras** [comment]
`v3.0` supports something very similar to this, partially due to your suggestion in this issue. [I recommend upgrading](https://github.com/erikras/redux-form/releases/tag/v3.0.0). Check out the [`handleSubmit` docs](http://erikras.github.io/redux-form/#/api/props).

[![redux form 2015-11-06 21-55-46](https://cloud.githubusercontent.com/assets/4396759/11008511/4ef31b06-84d1-11e5-90af-c844dec8dc72.jpg)](http://erikras.github.io/redux-form/#/api/props)
