### ISSUE TITLE
Reformatting initialValues in redux-form

### ISSUE THREAD

**Issue by ishwinder** [erikras/redux-form#1307]
I am loading the Redux form with initialValues being passed as props. However, I need to reformat the data so as to fit my form names .. so e.g if the data in initialValues passed as props is {name: 'John', age: '32'} (I dont have control over the format this data is coming because its coming from backend which is not in our control), I want to convert it to {user: {name: 'John', age: '32'}}. How do you achieve it ? Do you write a reducer to accomplish this and if yes then do you invoke it at the component load or there is some other way as well ?

Thanks.

**Comment by ishwinder** [comment]
I did call the reducer in the componentDidMount but it leads to re-rendering since it changes the state. Still looking for a way with single render.

To rephrase the problem to make it understand easier, The state that comes from server contains the value at the root node but i want to load it in the field name which is nested. E.g the state that comes from server {name: 'John', age: '32'} but I want to load name into a field who name attribute is set to user[name]

**Comment by clayne11** [comment]
You can pass whatever object you want to `initialValues`. You can also call the action creator `initialize` with any object you'd like to initialize a form. I'm having trouble understanding what the issue is that you're having. Nothing is stopping you from transforming the value returned from the server before you pass it into `initialValues`.

**Comment by brotzky** [comment]
@clayne11 it would be easier to have each Field normalize whatever is passed to it instead of having to parse an object and create a normalized version to initialize all the Fields with.

That way each Field is solely focused on its own thing and if the initial object changes for whatever reason the Field continues working as expected since it only cares about the value passed to it. 

We've run into this exact issue since all our Fields are mini-components that handle errors and normalization within themselves. Now we're trying to initialize entire forms with data from the server and it's a bit of a nightmare to parse the object and map the keys to normalizer functions to recreate pretty values passed to initialValues of the form or dispatching initialize.

**Comment by muhaNERD** [comment]
I run into the same issue. Any solution for this?
