### ISSUE TITLE
Persist data when using react-widgets for a wizard form

### ISSUE THREAD

**Issue by tejans24** [erikras/redux-form#1316]
So, I am using react-widgets using a Multiselect wrapper in a wizard form. When the form is filled and the next button is clicked, the data is not being persisted and the field becomes blank when a back button is clicked. 

Is there an additional mechanism to make this happen? I am using using 6.0.0-rc.2.

Thanks

**Comment by fini** [comment]
For wizards, you need to set destroyOnUnmount to false, or it will automatically clear after submitting.

export default reduxForm({
    form: 'wizard',
    destroyOnUnmount: false,
    validate: validateForm
})(somePage)

Refer to the updated rc.4 examples and docs for more info.

**Comment by gustavohenke** [comment]
I hope @fini's hint helped you @tejans24.

I suggest asking again at StackOverflow

In case you need further help with React Widgets and Redux Form integration, we recommend you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
