### ISSUE TITLE
can Redux-Form recursively parse `field` option?

### ISSUE THREAD

**Issue by ryerh** [erikras/redux-form#1361]
I want something like this:
``` javascript
function SimpleForm(props) {
  const { fields: { username, user } } = this.props;
  return (
  	<form>
      <input type="text" {...username} />
      <input type="text" {...user.email} />
      <input type="text" {...user.editor} />
    </form>
  );
}

export default reduxForm({
  form: 'simple',
  fields: ['username', 'user.email', 'user.editor'],
})(SimpleForm);
```

**Comment by hellosmithy** [comment]
+1 for this

I was about to make the same request. The `Field` HoC may be useful for some people, but the above example feels much more idiomatic. It would also allow us to map the props to match an inputs prop interface rather than needing to create factory functions to map the components themselves.

E.g.

```
const props = someMapFunction(customInputProps);
<CustomInput { ...props } />
```

instead of

```
const input = mapProps(someMapFunction)(CustomInput);
<Field name="customInput" component={ input } />
```

I can't help but feel this would do away with some of the issues described in https://github.com/erikras/redux-form/issues/1249 around namespacing props under `input` and then needing to `mapProps` on the component.

**Comment by rikkipitt** [comment]
Small world @hellosmithy... looking for something like this too.
