### ISSUE TITLE
[6.0.0-rc.3] Field's normalize function skipped for initialValues/reset

### ISSUE THREAD

**Issue by echenley** [erikras/redux-form#1379]
I have a form with a price field normalized as currency. If I initialize a form with a price of `5.5`, it appears un-normalized until interacted with, at which point it normalizes to `'$5.50'`. Calling `props.reset()` on the form restores the un-normalized value.

```js
// initialValues
{ price: 5.5 }
```

```js
normalizePrice = (value = 0) => {
  if (typeof value === 'string') {
    value = value.replace(/[^0-9\.]+/g, '');
    value = parseFloat(value);
  }

  return this.props.intl.formatNumber(value, {
    style: 'currency',
    currency: 'USD'
  });
};
```

```js
<Field
  id="product-price"
  name="price"
  type="text"
  pattern="^\\$?(([1-9](\\d*|\\d{0,2}(,\\d{3})*))|0)(\\.\\d{1,2})?$"
  floatingLabelText="Price"
  component={ this.renderTextField }
  normalize={ this.normalizePrice }
/>
```

**Comment by brotzky** [comment]
I'm getting the same issues. Loading in values to initialize my form and the normalize function is only called once the user types in the field. Would be fantastic to run this on initialize as well.

**Comment by erikras** [comment]
I looked into this for many hours, and it just isn't possible, because of the way the data flows from the Redux Store through to the input and then back to the Redux Store. The only time to call your normalize function is when a field value changes.

When I came to this realization, however, I realized that normalization is not what you need, and I decided to go ahead and implement two other lifecycle hooks that I have been meaning to do since I first announced that `v6` was coming. If you want your value to be formatted (and prices are the perfect example) for the form on first initialization, you will need to implement a `format()` and a `parse()` function, to convert the value in the data to the value  you want displayed in the input and back again.

I even drew up a diagram to illustrate the [Value Lifecycle](http://redux-form.com/6.0.0-rc.4/docs/ValueLifecycle.md/).

**Comment by brotzky** [comment]
We're formatting input values onKeyDown before this implementation. This gave us the ability to restrict certain keyCodes if we wanted to. For example, only allow 0-9 keys if asking for a number. With the lifecycle events it doesn't seem possible to provide the event object to the function you pass. 
 
Format an input:
```JavaScript
 <input onKeyDown={event => handleChange(event)} />
```

Would there be any ideas to providing the event object to `format()` or `parse()`? Now that I look into it more we use the event object in a lot of the input formatting. Maybe there's a different approach to how we have it setup that would work well with `<Field format={func} />`

**Comment by erikras** [comment]
@brotzky Seems like you could just use regex.
```js
const parse = value => value && value.replace(/\D/g, '') // remove everything but digits
```

**Comment by brotzky** [comment]
Yeah, we do a mixture of both regex & keycode specific stuff. I'm going to try to make it work using the lifecycle methods. Will report back.

**Comment by MtDalPizzol** [comment]
@echenley , just out of curiosity... about the `this.props.intl` in your code: Have you set this manually or am I missing some inherited `intl` from `redux-form` or another lib?

**Comment by echenley** [comment]
@MtDalPizzol It's from [react-intl](https://github.com/yahoo/react-intl).

**Comment by MtDalPizzol** [comment]
Ah! Ok... thanks!
