### ISSUE TITLE
Can't type 1.01 on number input

### ISSUE THREAD

**Issue by RHavar** [erikras/redux-form#1383]
(Only tested on 6.0.0-rc.3)

`<Field name="foo" type="number" component="input" />`

I can't type `1.01` in this field, because when I type `1.0` it immediately gets normalized to `1`

**Comment by sknoslo** [comment]
This is because the value of an html input field is a string, and redux-form tries to convert it to a number using ```parseFloat()``` and because of the way JavaScript treats numbers you lose that precision. So ```parseFloat("1.0")``` just turns into ```1```. While having a number field produce an actual number seems to make a lot of sense, it's actually pretty broken. Probably just something the developers didn't consider.

There may be other workarounds, but I would suggest just using a normal text field and writing your own normalize function to make sure it looks like a number. Then just use ```parseFloat()``` later if you need an actual number for calculations/storage/etc... Honestly, even if they decide to change this, I would recommend this approach anyway because it avoids browser inconsistencies.

**Comment by RHavar** [comment]
I think redux form just needs to store them internally as a `string`, just the same as getting the value out of a `<input type="number">` from the dom. (it returns a string, not a number).

But anyway, using a `<input type="number">` over a normal text input is important for my use case. Probably the most obvious reason is most of my users are on mobile and a number input opens the number keyboard, but there's a whole set of niceties with a number input that don't exist in a text one

**Comment by sknoslo** [comment]
Yes, as I mentioned their idea to turn input into a number is inherently flawed.

If you want to trick mobile browsers into displaying a numeric input you could potentially use ```type="tel"``` and then still normalize the input as I suggested. But it seems kinda hacky.

Or submit a PR removing lines 34-36 [here](https://github.com/erikras/redux-form/blob/v6/src/events/getValue.js#L34) with some justification, and hopefully they will accept it.

**Comment by JosephEarl** [comment]
I am also having this issue, specifically on IE11 it is impossible to enter a number with a decimal e.g. '1.1'.
Strangely entering '.1' produces '0.1'. Only way to enter '1.1' is to enter '11', and then move the cursor and enter a '.' between the 1s.

**Comment by Lube** [comment]
Are number inputs being serialized as numbers now in the store?

**Comment by amangeot** [comment]
I am also having this issue, currently testing on latest version of Chrome.

I just updated redux-form to v6.2.0 and I think there is still an issue with dots in inputs of type number:

```
<Field name='min' component={renderTextField} type='number' step={0.1} min={0} max={MAX} />
```
```
export const renderTextField = ({ input, meta: { touched, error }, ...custom }) => (
  <input {...input} {...custom} />
)
```

If I digit "1", then ".", the input gets cleared. I'm .

Anyone else having this issue ?

**Comment by 3ffy** [comment]
issue stills present in v 6.4.3.

I can't figure why exactly, but if i type 1,50 and then edit to 1.60 my app is populated with 1,60 (so there is no real problem with dot notation). Problem is when you are typing `1.` because i assume some parseFloat somewhere is used to check the value to use into the field. However, typing `1,` (with a coma) is working fine since redux-form assume `1, == 1,0`.

A simple workaround could be something like:
```javascript
val = val.replace(new RegExp(search, '.'), ',');
```

This way, all dots will be replaced by a coma before being analysed and everything will be fine. When the user will be typing `1.`, `1,` will be showed into the input.

**Comment by faizrr** [comment]
@3ffy i've found out that html inputs depend on regional settings. Try to change them (e.g. in Russia comma is used, in USA - dot)

**Comment by luisgrases** [comment]
use the following normalizer: 
```const maskMoney = (value) => {
  if (value === null || value === '' || value === undefined) { return '' }
  let v = value.toString().replace(/[^\d.]/g, '')
  v = v.slice(0, v.indexOf('.') >= 0 ? v.indexOf('.') + 3 : undefined)
  return v
}```

**Comment by Frit** [comment]
seems strange, but helps:
   ```
 onFocus = e => {
        this.props.input.onChange(e.currentTarget.value); //or (e.currentTarget.value.toString())
    };

```
