### ISSUE TITLE
[v6] Why do all fields re-render when a single field changes?

### ISSUE THREAD

**Issue by andrewmclagan** [erikras/redux-form#1405]
Im sure this has been answered.

Tracing component updates in the console  shows on every: keypress and update event **ALL** fields are re-rendered. This seems like a performance bottle neck with large forms? 

Already when I try to type fast in a  `<textarea />` its slow, much slower then non-redux-form.

**Comment by xiaofan2406** [comment]
Any `props` or `state` changes in a component will cause the whole component to re-render. The 'Trace component updates' shows what components are being re-render by `React`, but it doesn't mean that the DOM tree for the component is completely redrawn. `React` is effect enough to re-draw the necessary dom tree.

**Comment by cristian-sima** [comment]
I think one of the ways to see if the component really updated on dom is to use the Chrome `Paint Flasing` from `Rendering` section.

![image](https://cloud.githubusercontent.com/assets/12199042/17170237/d526ce42-53f3-11e6-8e14-143eaf0dbf6f.png)

**Comment by richardscarrott** [comment]
@andrewmclagan I believe that v5 re-rendered all fields because it's the top level `Form` component which is `connect()`ed to the store so whenever the store changes, i.e. whenever you change a value in the form it re-renders. This makes for a great programming model in true Flux / React style however I believe many people ran into performance issues as unfortunately whilst JS is fast, it's not _that_ fast.

I think this is why in v6 each individual component is `connect()`ed to the store so only specific fields need to update...saying that, `store.dispatch` would still have to trigger change on each of the connected Fields so unless there's some fancy optimisation in place I can't imagine it being too much faster... actually, @erikras I'd be really interested to hear more about the performance characteristics between v5 and v6?

**Comment by erikras** [comment]
`v6` should **not** rerender every input on every keypress. One confusing aspect is a potential confusion between [**updates and renders**](https://github.com/erikras/redux-form/issues/1031), which are not the same. If you have an example that can be shared where your entire form is being slowed down with each keypress, by all means share it.

**Comment by richardscarrott** [comment]
@erikras Would I be right in saying that in v6 every `<Field />` is notified of a change to the store on every keypress (even if `connect` determines it doesn't necessarily need to render via `shouldComponentUpdate`)?

**Comment by erikras** [comment]
@richardscarrott Yes, just like every `connect()`ed component in your app.

**Comment by richardscarrott** [comment]
@erikras so if you had 300 `<Field />` components in your app (not saying I have this use case but just for stress testing purposes) it'd still be similarly expensive as it was in v5 when the whole form was rendered or have you found it to in fact be faster?

**Comment by erikras** [comment]
Yes. The slowness is in the render, which consists of React reconciliation (its magic virtual DOM stuff) and the actual DOM updating. Running a `deepEqual()` compare of two js objects pales in comparison.

**Comment by andrewmclagan** [comment]
On some form components we have developed specifically for redux-form we have HUGE performance benefits front only passing 'props.onChange' a new value when our underlying input 'input.onBlur' is called. 

Maybe... Just maybe we could default to blur updates? And users can opt in to onChange updates?

**Comment by andrewmclagan** [comment]
Have not thought it out allot... I'm sure there are caveats to this approach. Although it does have massive benefits and I can't see a reason store needs updating on every change event

**Comment by schwermer** [comment]
We also have seen a huge performance benefit from ignoring onChange events and only updating the redux-form state onBlur for forms with large FieldArrays.  The most obvious downside to this approach is that normalization does not occur while the user is typing.  

I wonder if an option in the reduxForm config or the Field component to only update onBlur would be worth including with this package?  I would be happy to submit a PR if there is interest

**Comment by richardscarrott** [comment]
@erikras I spent some time benchmarking the performance of v5 and v6 with various size forms and I've found myself able to tune v5 better than v6.

The reason I've been able to get v5 running faster is because I'm able to prune large parts of the component tree during a re-render by separating my form into multiple fieldsets. This isn't possible in v6 because the heavy lifting has in effect been taken away from React and given to Redux's event publisher which isn't designed to be optimised in the same way React render is.

I've pushed up my demo along with the HAR files demonstrating the difference in frame rate whilst typing in a form with 40 and another with 400 inputs. If you have time it'd be great if you could review the code to determine if you can squeeze out any more perf on either versions?

v5
https://github.com/richardscarrott/redux-form-v5-vs-redux-form-v6/tree/redux-form-v5

v6
https://github.com/richardscarrott/redux-form-v5-vs-redux-form-v6/tree/redux-form-v6

**Comment by richardscarrott** [comment]
@erikras did you get a chance to look over those benchmarks at all? The main reason I ask is because I can see you're looking to land v6 very soon and I'm concerned the _really nice_ v5 API is going to be dropped even if there aren't performance benefits in v6...

Incidentally, I wrote a blog post describing the performance optimisation I was able to make in v5 which wasn't possible in v6 -- https://richardscarrott.co.uk/blog/post/rendering-big-lists-in-react/

**Comment by timhwang21** [comment]
Thought I would bump this to the top. I'm having the same issue with all fields re-rendering (I specifically checked the `render` method of `<Field>` and confirmed that yes, this is what's happening). 

@schwermer , would it be possible to share your solution of only updating `onBlur`? I'd love to take a look.

Thanks!

**Comment by smirea** [comment]
the `onBlur` workaround simply implies removing the `onChange` listener from the input. 
The main downside is that normalization and validation don't occur on keypress. 
Another key factor is that if you use custom plugins for reducers, you have to listen for the `redux-form/BLUR` action to check when a field is changed (since the `CHANGE` event is never fired)

aka, for the following example: 

```jsx
<Field name='foo' component={renderTextField} />
```

normal way (bind all listeners: change, blur, focus, etc), that causes a `CHANGE` action to be dispatched on every keypress

```jsx
const renderTextField = ({input, meta, ...custom}) => <input type='text' {...input} {...custom} />
```

only using `onBlur`:

```jsx
const renderTextField = ({input: {onChange, ...input}, meta, ...custom}) => 
    <input type='text' {...input} {...custom} />
```

This prevents the `onChange` events from ever firing

**Comment by timhwang21** [comment]
Perfect! Will play with this. Thanks!

**Comment by bertjwregeer** [comment]
@smirea If you don't call `onChange` then `value` is never updated, so you end up with a form field that won't let you input any data (since it is not round-tripping to React for a DOM refresh).

You'd have to make the form component stateless by removing value from the props passed to `<input>` but then you can't have redux form provide an initial value...

I ended up with this, and it seems to work (probably some corner case I am missing somewhere...)

```
export class inputOnBlur extends Component {
    state = {
        value: '',
    }

    componentWillMount = () => {
        const { input: { value } } = this.props;

        this.setState({value: value});
    }

    componentWillReceiveProps = (nextProps) => {
        const { input: { value } } = nextProps;

        this.setState({value: value});
    }

    onChange = (e) => {
        this.setState({value: e.target.value});
    }

    render() {
        const { input, type, placeholder } = this.props;

        delete input.onChange;
        delete input.value;

        input.value = this.state.value;
        input.onChange = this.onChange;

        return (
                   <input type={type} placeholder={placeholder} {...input} />
               );
    }
```

**Comment by semy** [comment]
Are there any news about this issue?

**Comment by erikras** [comment]
Two things:

1. I'm not really sure what to tell you. While I seriously doubt it, I cannot verify the claim that all the fields rerendered on every change back in July and August, during the rocky `v6-alpha` period. I _can_, however, verify that it is not the case now. See the commit above. ☝️ 
2. Since this ticket was introduced, there is a new component called `Fields` that will more or less return sections of your form to `v5` functionality, where you get one component that is given all the metadata and props for many fields. So if you wanted to do optimization like @richardscarrott suggests above, you could potentially use that.

---
P.S. Your fields will rerender every time if you are creating your component function every time. Don't do that.
```jsx
<Field name="foo" component={props => <input {...props.input}/>}/> //  ❌ WRONG
```
```jsx
const renderInput = props => <input {...props.input}/>
...
<Field name="foo" component={renderInput}/> //  ✅ RIGHT
```
