### ISSUE TITLE
[v6] Design flaw - Cannot decouple redux from presentational components

### ISSUE THREAD

**Issue by adamjking3** [erikras/redux-form#1444]
Before v6, it was possible to write forms as presentational components with no knowledge of the underlying application state (redux). You could then add redux-form as a decorator to a container (smart component) that's aware of the redux state and can then pass it along as props to the presentational component. v6 makes this impossible, as the presentational component which renders the form is now required to use the redux-form/Field component. 

Here is a working example using the v5 API to show what I mean.

Presentational component:

```
export const LoginForm = (props) => {
  const { fields : { email, password }, submitting, handleSubmit } = props;
  return (
     <form onSubmit={handleSubmit}>
        <input name="email" placeholder="email" type="email" {...email}/>
        <input name="password" placeholder="password" type="password" {...password}/>
        <button type="submit" disabled={submitting}>
          Login
        </button>
      </form>
   );
}
```

Smart container:

```
@reduxForm({
  form: 'login',
  fields: [ 'email, password' ]
})
export default class Login extends Component {
  onFormSubmit({ email, password }) {
    this.props.dispatch(loginUser({ email, password }));
  }
  render() {
    const { submitError, authenticated, fields, submitting, handleSubmit } = this.props;
    return (
      <LoginForm fields={fields} submitting={submitting} handleSubmit={handleSubmit(this.onFormSubmit.bind(this))} />
    );
  }
}
```

This separation of concerns isn't possible in the v6 API as far as I know. I propose that another solution is found that allows the benefits of v6 (single field re-rendering) but continues to allow the separation of concerns allowed in previous versions.

For reference on smart vs dumb components and why we should use them:
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.p8nv77juo

**Comment by rluiten** [comment]
This is not a defense or an argument, just what  I did.

I limited my exposure by creating a few low level common control components  eg. CheckboxField, TextField, TextAreaField etc. These use redux-form Field and such.

These are then assembled in my form components, most all of my form components don't know about redux-form.

I am dependent on redux-form in the common controls, in the top level wrapper and around areas where I use redux-forms FieldArray to manage sets of fields. I also create controls that use FieldArray to limit areas that need to be aware of FieldArray.

**Comment by clayne11** [comment]
It's not really a design flaw. It's a trade-off. There's no way to have both the performance gains of `v6` and the decoupling you're referring to.

**Comment by naw** [comment]
Actually, you can easily achieve decoupling by passing `Field` as a prop to your presentational component ---- so the presentational component doesn't need to know anything about `Field` being connected to redux, it just needs to know that it receives a prop called `Field`, which it uses to build the form. Whether that `Field` happens to be the one from redux-form, or something completely different that has nothing to do with redux, the presentational component remains completely agnostic and decoupled.

**Comment by stevenmusumeche** [comment]
@naw can you give an example?

**Comment by naw** [comment]
@stevenmusumeche

In order to capitalize on the performance benefit of v6, each form input must be inside of its own connected component.

This requires the presentation component to change a bit.  Instead of generating `<input>` components, it must generate connected components that wrap `<input>` components.

From a conceptual standpoint, this _doesn't_ mean the presentation component needs to know anything about redux or state --- it just means that the presentation component needs to "generate" components using some helper (like `<Field>`) rather than generating them directly (e.g. using `<input>`). 

In other words, using `<Field>` inside a presentation component doesn't actually result in a loss of separation of concerns, it just changes the API.  You're not stuck using `<Field>`, you can imagine other API's, as long as there is a layer between the form and each input.

To reinforce this idea at the conceptual level, you can use dependency injection to _give_ the presentation component the "helper" that it is supposed to use to generate form components --- the presentation component doesn't even need a hard dependency on `Field` from `redux-form`, it just needs to know that it will receive a "helper" as a prop. This is what I mean:

```javascript
const PresentationComponent = (props) => (
  <form>
    <props.InputGenerator name="firstName" component="input" />
    <props.InputGenerator name="lastName" component="input" />
  </form>
)

const Parent = () => (
  <PresentationComponent InputGenerator={Field} />
)
```

To clarify --- I'm trying to say that conceptually the existence of `Field` does not conflict with the idea of separation of presentation concerns.

All of that said, you _do_ lose the ability to write your forms _directly_ with `<input>` components, **which might be the actual issue from a pragmatic standpoint**.  

If you _really_ want to write things more like v5 and don't care about the performance benefits of separately connected fields, you can use `<Fields>` and do something like this, which is very similar to v5:

```javascript
const PresentationComponent = ({ firstName, lastName }) => (
  <form>
     <input type="text" {...firstName.input} />
     <input type="text" {...lastName.input} />
  </form>
);

const Parent = () => (
  <Fields names={['firstName', 'lastName']} component={PresentationComponent} />
)
```

Finally, you can _imagine_ a variety of hybrid approaches.  Here is an example:

```javascript
const PresentationComponent = () => (
  <div>
      <Field name="firstName" render={(fieldProps) => (
        <input type="text" {...fieldProps.input} />
      )} />
  </div>
)
```

(note: this code doesn't actually work out of the box) -- the pros/cons of this particular approach were discussed in https://github.com/erikras/redux-form/issues/1555

**Comment by danielrob** [comment]
This discussion seems to have been closed out by @naw's excellent comments above.

**Comment by penx** [comment]
I've written a post about decoupling presentational form components from redux and redux-form that may help - https://medium.com/@penx/form-elements-in-presentational-component-packages-a618e9aa7416
