### ISSUE TITLE
[v6] Question: Dispatching actions on field change and after validation has passed.

### ISSUE THREAD

**Issue by casparrolfe** [erikras/redux-form#1446]
Hello!

I have two form fields, `A` and `B`. On change of either field, I want to dispatch an async action that hits an endpoint with the values of `A` and `B` if they exist and they are valid. I don't want to do this on submission of the form.

I've considered doing this on the component passed to `Field`, however, validation is not complete at this stage. Any suggestions?

Thanks!

**Comment by clayne11** [comment]
You could use a `formValueSelector` on the form level component, and then in `componentWillReceiveProps` diff them, and if they are different then fire an action.

**Comment by gustavohenke** [comment]
Hi @casparrolfe, in case you never fixed your issue, we recommend you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
