### ISSUE TITLE
Slow performance with multiple records of forms.

### ISSUE THREAD

**Issue by haradakunihiko** [erikras/redux-form#146]
I use redux-form for multiple records of forms. 
The performance is terrible when the page has more than 30-40 records, since focusing on one single form element forces all redux-form-connected component to rerender. It's simply because 'connectReduxForm' connect the very root of the redux-form's state with the following connector.
```
connect(state => state.form)
```
Though I could write shouldComponentUpdate to the decorated component, and yes I did it, I can not use stateless component with it...

So, here is my hack with reselect.
https://gist.github.com/haradakunihiko/4d27dadd4aba951f6582

Maybe reduxForm should accept only its related form data?
I mean, getSubForm should be outside of reduxForm. How do you think about this?

**Comment by erikras** [comment]
This library grew organically from something designed to only handle one form, and I think it might need a bit of a rewrite to properly fill the multi-form role that people are now expecting from it.

This issue is very thought provoking. I think you've steered me down the right path. Thank you, @haradakunihiko.

**Comment by erikras** [comment]
Thank you for this ticket. In `v3.0`, I implemented it to only connect to the Redux state slice that the form needs. [I recommend upgrading](https://github.com/erikras/redux-form/releases/tag/v3.0.0).
