### ISSUE TITLE
[6rc4 or beyond] How best to do late async initialization?

### ISSUE THREAD

**Issue by estaub** [erikras/redux-form#1461]
I have some fields that are usually already in cache, but may be ajax'ed in by starting a server HTTP get at component construction.  I'd like to paint as much of the form as is available as soon as possible.  What's the best way to initialize fields that come in late (after initialValues has been read)?

**Comment by erikras** [comment]
If the ajax is happening in the container of your form, you can just update the `initialValues` prop.

**Comment by hathawsh** [comment]
@erikras has the right advice, but it sounds like you'll also want the new enableReinitialize flag so that the new form data becomes visible to users. Furthermore, you might also want to ensure that whatever users type in the form doesn't get overwritten when the async data arrives, which means you probably want the pull request I submitted today (or something like it). :wink:

https://github.com/erikras/redux-form/pull/1465

**Comment by albermav** [comment]
It would be good to add some kind of notInitialized or isLoading flag to the redux store to be able to show a spinner when the form is not yet ready

**Comment by estaub** [comment]
Thanks, it works fine - a subtle bug on my end made me think that late mods to initialValues weren't picked up.

**Comment by erikras** [comment]
Great follow up, @hathawsh and @albermav. 👍
