### ISSUE TITLE
[6.0.0-rc.4] hidden field

### ISSUE THREAD

**Issue by stunaz** [erikras/redux-form#1495]
Hi,
I wasn't able to use an hidden field.
`<Field component="input" name="id" type="hidden" />`

the field doesnt appear in redux store.
Am I doing something wrong or there is another way to do that?

**Comment by brotzky** [comment]
It works for us and shows up in the redux state. Try initializing the input field with an empty value?

```JavaScript
const initialValues = {
  myHiddenInput: '',
};

...

myForm = reduxForm({
  form: 'form',
  initialValues,
})(myForm);
```

**Comment by hathawsh** [comment]
FWIW, here's how I created a hidden field recently:

```javascript
function HiddenField() {
  return null;
}

function ExampleForm() {
  return <Field name="hiddenthing" component={HiddenField} />
}

export default reduxForm({
  form: 'example',
  initialValues: {hiddenthing: 'hiddenvalue'}
})(ExampleForm);
```

It worked well and didn't add any unnecessary markup to the HTML.

**Comment by stunaz** [comment]
@brotzky  it is a field that I intend to dynamically update the value.

**Comment by jonjaques** [comment]
@stunaz, so you're saying you don't see a `redux/REGISTER_FIELD` action for id on page init?

**Comment by stunaz** [comment]
@jonjaques  just double checked, I see it `redux/REGISTER_FIELD`  but I dont see it in the `values` object.
I will just use @brotzky's way.

Thanks

**Comment by brotzky** [comment]
@stunaz, hope it works! I think the issue arises because of redux's initial state behaviour. In redux (not redux-form) you have to initialize values or else they won't exist in your state (until you add something through an action). This trickles down to redux-form where you need to initalize a Field with something (like an empty string) if you want it to appear in state.
