### ISSUE TITLE
Hiding parts of the form

### ISSUE THREAD

**Issue by woylie** [erikras/redux-form#1526]
I have a deep form with three panels displayed next to each other. The nested data is basically structured like this:

```
{
    items: [{
        label: 'A',
        subItems: [{
            label: 'A-1',
            subSubItems: [{
                label: 'A-1-1'
            }]
        }]
    }]
}
```

It would be confusing to display all the fields at once. The items with their labels are all displayed in panel 1. If you select one of those items, only its subitems will be displayed in panel 2. If you then select one of the subitems in panel 2, the subitem's subsubitems will be displayed in panel 3.

I first made a version with Redux Form 5. I defined all the fields in advance, initialized all the field values from the state, kept track of which item and subitem were selected and looped only on the according parts of the values to display panel 2 and 3. Easy and fast. Selecting another item or subitem displayed the according sub fields instantly.

In Redux 6 however, I can't define the field structure in advance. The three panels are rendered similar to this:

```
<FieldArray
    component={Items}
    name="items"
/>
<FieldArray
    component={SubItems}
    name={'items[' + this.state.selectedItem + '].subItems'}
/>
<FieldArray
    component={SubSubItems}
    name={'items[' + this.state.selectedItem + '].subItems[' + this.state.selectedSubItem + '].subSubItems'}
/>
```

While this displays the panels correctly, it is incredibly slow. Every time another item or sub item is selected, a bunch of REGISTER_FIELD and UNREGISTER_FIELD actions are fired. It is already too slow for just a few items, and it gets much slower quickly with every added item.

So my question is: Is there a smarter and faster way to accomplish this with Redux Form 6, or isn't Redux Form suited for this kind of scenario?

**Comment by clayne11** [comment]
I think you could rearrange your data structure so that each "selected item" is stored as a single top level key in the store so that you don't need to dynamically add and remove fields in the way that you're doing. You should simply remove and add a single top level DOM element which corresponds to a single `Field` component.

**Comment by woylie** [comment]
I'm not quite sure what you mean. The three panels are dependent on each other, so I still need to be able to dynamically change which fields to display, which will then again fire all those register and unregister actions. It is all well and good when there is only one displayed item per panel, but the last panel will more likely contain twenty items at once. I don't know why it's so much slower than RF5, wasn't RF6 supposed to be faster with large forms?

**Comment by naw** [comment]
v5 performance bottleneck was rerendering the whole form whenever one field changed.

v6 performance bottleneck is that it dispatches a lot of actions to register/unregister fields. This can definitely be an issue if you're mounting or unmounting a lot of fields. It's exacerbated by anything else in your app that slows down dispatches (like redux-devtools, for example). 

If anyone wants a simple way to reproduce this that isn't tied to something complex like the 3-pane example @woylie provided, just loop over a few hundred text inputs and see how slow it is:

```javascript
_.range(300).map((i) => (
  <Field key={i}
    name={`field${i}`}
    type="text"
    component="input"
  />
))
```

If you need an immediate workaround, perhaps mounting everything at the beginning (which would be slow), and using `display: none` and `display: block` to hide/show things instead of actually unmounting and remounting them would help with the speed of transitions.  I'm not sure what a good long-term solution is.

**Comment by slavab89** [comment]
@woylie I have the exact same scenario that you have. Did you find a workaround or solution for this?
What happens to me is once i click on some input on the subSubItems place it sends a FOCUS event and right after that a bunch of REGISTER and UNREGISTER events.

**Comment by kristian-puccio** [comment]
I've done this in two ways.

First way is to just add a style { 'display': 'none' } to the element. That
way no events are triggered.
The other way is to wrap the 'Field' in a ternary, this means as the field
is hidden and shown the REGISTER and UNREGISTER events are triggered.

I also wanted when a field was deregistered that it's value was blanked so
I added redux middleware that listened to this event and dispatched a
change action to clear the value.

**Comment by slavab89** [comment]
I actually tried to go with the hide/display way but it was too complicated for me to do that.

What i did in the end that solved this was:
I have a list of items that i can choose from (Regular list, not FieldArray). Once i click on one of them it dispatches an action of SELECTED_ITEM and that is saved on the redux store.
Then i have a form for that chosen item. In that form i also have a list of subitems that i can choose from (Regular list, not Field). Once one of them is chosen, an action is dispatched and this subItem creates a FieldArray with the subSubItems (that each of them is a Field) that are registered dynamically like you have.

When editing fields i also have a button that changes the edit mode (plain test or an input place). To do that i'm using the same field just control the component property in that field to show an input area or just a div with the value.

To add new items i use a different form that changes the Items array and then its reflected to the Form fields.

I think that the main point is to try not to do a Field within a Field - this seems to cause UNREGISTER and REGISTER (for me at least). Might be the same for FieldArray within a FieldArray

**Comment by danielrob** [comment]
Assuming that this question is answered based on lack of response from OP. Efficient Conditional Fields documentation +1.
