### ISSUE TITLE
"Uncaught TypeError: Converting circular structure to JSON" with redux-promise-middleware

### ISSUE THREAD

**Issue by rluiten** [erikras/redux-form#1587]
Just a heads up in case anyone else gets the error hope it saves someone time :).

Spent an hour wondering why I was getting "VM9955:2 Uncaught TypeError: Converting circular structure to JSON" in my javascript dev console when my form post end point returned an error (400 or 500)
I combed through my code first then started looking for other sources (yes I did think briefly there might have been a regression in redux-form since i updated last week).

Turns out uninstalling redux devtools from chrome makes the error go away

**Comment by HriBB** [comment]
Thanks for the heads up ;)

Instead of opening a new issue, I will steal this one. Hope you're not angry :) Anyway, I don't use Chrome addon, but render `redux-devtools` with `redux-devtools-dock-monitor`. Together with `react-hot-loader@3.0.0-beta.2` that make my forms very very veeeery slow in development. Without devtools it usually takes 1-3s to reload, but with devtools it takes some 5-15s. Using `redux-devtools-inspector` seems to be much faster, but I haven't tested properly. I also created an additional config switch, with which I can turn devtools on/off. @erikras and thoughts on this topic. How can we speed things up in development. I understand that this is probably a devtools issue, but still you might have some insight.

**Comment by erikras** [comment]
@rluiten Hmm... Are you putting a circular JSON structure into your form values? Because I'm pretty certain that `redux-form` isn't.

@HriBB Hijacker! Ouch, that sounds like some pretty bad DX (developer experience). Sounds like the tools and not the library, though. It must be replaying every action on reload, but inefficiently somehow.

**Comment by rluiten** [comment]
@erikras as far as i know I am not (i will recheck), and from what I can tell redux-form is not - its visible state looks kosher.

I just ran across this a 1/2 hour ago, redux-promise-middleware update has a comment about latest release to do with circular links in particular cases... so its next on my list to check.

**Comment by rluiten** [comment]
It seems that my circular reference came from error handling in redux-promise-middleware and they just released 4.0.0 recently that changes how the error's are generated and the Chrome addon Redux DevTools no longer triggers the circular log messages. 

So my original heads up is of limited value I think, unless you are using redux-promise-middleware and Chrome redux dev tools addon.

**Comment by erikras** [comment]
Thanks for investigating. I've re-titled the issue for maximum help for future searchers. Closing.
