### ISSUE TITLE
initialValues in wizard form reset syncErrors generated by validation

### ISSUE THREAD

**Issue by liming** [erikras/redux-form#1619]
To reproduce this problem:
1. Create a wizard form with sync validate and set initialValues as an empty object {}
2. Load the form there is no syncErrors

The action sequence is something like this:
1. redux-form/UPDATE_SYNC_ERRORS 
2. redux-form/INITIALIZE 
3. redux-form/REGISTER_FIELD
4. redux-form/REGISTER_FIELD
...

It seems not correct because INITIALIZE would reset syncErrors. UPDATE_SYNC_ERRORS should invoke after initialise with initialValues.

**Comment by karthikiyengar** [comment]
I can confirm this, although in my case I am fetching initialValues from the server. This results in the error meta for every field to be set to undefined.

<img width="626" alt="screen shot 2016-08-30 at 3 18 10 pm" src="https://cloud.githubusercontent.com/assets/8260207/18084766/23034176-6ec6-11e6-87f0-bc82bb9e7ed3.png">

Also, it seems that dispatching initialize using the API gets rid of syncErrors too. Is this by design or is it a bug?

**Comment by dmason30** [comment]
@erikras  please prioritize this same occurs with RESET/DESTROY. UPDATE_SYNC_ERRORS needs to run after these are called.

**Comment by karthikiyengar** [comment]
I shall be happy to take this up if I can get a confirmation from the author regarding what he feels would be the correct direction here.

**Comment by erikras** [comment]
Hmm.. I'm not able to replicate this.

1. I'm seeing `UPDATE_SYNC_ERRORS` happening _after_ `INITIALIZE`. And looking at the code, I don't see how it could ever be otherwise if you are using the `initialValues` config param/prop.
2. As of `v6.3.2`, `INITIALIZE` does not blow away sync errors

Can someone recreate this using the [Sync Validation Example](http://redux-form.com/6.3.1/examples/syncValidation/) (or any other example you choose)?

**Comment by danielrob** [comment]
Closing this issue due to lack of response and lack of reproducibility. If you can advise of reproduction steps for this issue, please provide details in a new issue / reopen request comment.
