### ISSUE TITLE
Programmatically submit a form from outside the form component

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#1679]
I generally abstract my forms into a form component. However, a number of forms that we use, have the submit button designed in the header, which is outside of the form screen in a parallel render branch.

So, I have been wondering how to implement a programmatic submit. I was thinking of the following:

1. create a programmatic submit property in a reducer, that when true, leads to the execution of a programmatic submit in the form component, after which it's immediately set to false.
2. using refs. In my case, the components are simply "too far away from eachother" for this to be feasible.

Any suggestions on the best way to approach this? Ideally, I would be able to just call a redux-form action creator with the form name to submit the form.

**Comment by erikras** [comment]
Yep, I think you're on the right track.

I have thought long and hard about this. Because so much of the work involved in submitting the form depends on props given to the form, there has never been a great way to have a `submit()` action creator. I suspect that your first option of leaving a `submit as soon as you see this` flag in a reducer is the way to go. You could implement this now with your own reducer in the form component's container (which would then use a ref), but I might add this functionality to the library itself, as it is one of the most requested features.

I wonder if there's a technical computer science term for this kind of async communication. I nominate [dead drop](https://en.wikipedia.org/wiki/Dead_drop) as the term. 🕵

**Comment by mschipperheyn** [comment]
Thx!

**Comment by mschipperheyn** [comment]
This was a bit more difficult than expected and the solution is not all that elegant, although it seems to work ok.

https://github.com/reactjs/react-redux/issues/376 got in the way of getting access to the submit method inside the form from the container component, which my initial attempt since the all the connect/reducer stuff is in the container component. 

So, I solved it by putting a submitThis property on the form component itself combined with the already discussed reducer flag for this.

**Comment by diegohaz** [comment]
Hey, guys, I've published [redux-form-submit](https://github.com/diegohaz/redux-form-submit), which adds the submit action creator to redux-form. Maybe we can add this to redux-form itself in the future.
