### ISSUE TITLE
[FireFox] Input with type='number' allows to enter letters v6.0.2

### ISSUE THREAD

**Issue by Mari4ka89** [erikras/redux-form#1701]
Hello Erik,

I have tried version 6.0.2. 

In the code I have:
     `<Field name="age" type="number" component={renderField} label="Age" />`
 where: 
`const renderField = ({ input, label, type, meta: { touched, error } }) =>
  <div>
    <label>{label}</label>
    <div>
      <input {...input} placeholder={label} type={type} />
      {touched && error && <div className="validation-error">{error}</div>}
    </div>
  </div>;`

The problem is that I can enter letters into such field in FireFox 48, Ubuntu.
In Chrome works fine.

**Comment by KyKyPy3** [comment]
Why did you decide that this is a problem in this library? Restricting character input makes chrome instead redux-form. You can create html with number input and open it in Chrome and Firefox and test.

**Comment by Mari4ka89** [comment]
Yes, that's right. But when I type letters into input type="number" I can't get into validate() method.

**Comment by KyKyPy3** [comment]
You can use normalization for Firefox like here http://redux-form.com/6.0.2/examples/normalizing/.

**Comment by garrettn** [comment]
Normalizing doesn't seem to help here because even though Firefox displays non-numeric characters in number inputs, it doesn't actually change the `value` of the DOM node, so Redux Form has nothing to work with. Oddly enough, I do see the `redux-form/CHANGE` action getting dispatched every time I type a letter into a number input, but the value doesn't actually change.

The only way I am able to force a number in Firefox is to use a default input (or `type="text"`) and then use a normalizing function. But by doing that I lose out on the number keyboard coming up on mobile. I don't think this is Redux Form's problem, but it certainly is a conundrum.

**Comment by gustavohenke** [comment]
Guys here are right.
No business of ours, unfortunately the only way around this issue makes mobile UX worse, as @garrettn initially documented.
