### ISSUE TITLE
Proposal: Drop support for normalize, parse and format

### ISSUE THREAD

**Issue by x2764tech** [erikras/redux-form#1736]
I don't think these are useful methods as they are implemented.

There are better places to handle this type of concern:
- in the `Field.component` for handling user input, 
- in the `initialValues` for transforming values from external state, 
- `onSubmit` handler for transforming form values to external state

We already expect that the Form's state may be invalid, and, as far as I can see, restricting user input is outside of the scope of this library too.

Transforming the inputted text messes for the Form's state also messes around with the caret position on text inputs.

I'm not say there shouldn't be hooks to handle form value changes (which can happen in the validation or in the `Field.component`), but I would suggest that these three methods are unnecessary on a library that allows users to inject their own components.

**Comment by dtipson** [comment]
Format seems to work the same as normalize now, unless I misunderstand: I still see the "formatted" values showing up in the redux store instead of the raw values.

**Comment by leesei** [comment]
I've used `<Field>` to wrap Material UI's `<DatePicker>`, the `input.value` is a `Date` object.
I used `parse()` and `format()` to convert the `Date` object to format I want ("YYYY-MM-DD").

Yet my first thought was to use a pre-submit function to convert the "native" input values (including the `Date` object for `<DatePicker>`) to the model of the API. However there's no pre-submit hook in redux-form so I resorted to `parse()` and `format()`.

**Comment by gustavohenke** [comment]
It seems that there are more people against this idea than people in favor of dropping such props.
Therefore, I'm closing this issue.

**Comment by jedwards1211** [comment]
@leesei typically you would parse the values in the function you pass to `handleSubmit`.

Are there really common cases where `parse` and `format` don't cause annoying behavior?  For example if you `parse` values in a text field into a `Date` and then `format` them back to a string, the text field will be irritatingly contrary, resetting the cursor position anytime the re-formatted value ends up being different.

Thus far I always end up parsing values in my submit handler and formatting them before I initialize the form.  Which is much less convenient than if I could define such logic on the fields themselves, without making the fields behave in a contrary way.

I think it would be better for `redux-form` to:
* store both raw and parsed values separately in redux store
* have an option to validate parsed values rather than raw values
* always pass the raw value to field components (if storing a special value in the redux store is necessary, it should be the **component's responsibility** to do parsing and formatting)
* have the ability to pass raw and/or parsed values to initialize
* pass raw and parsed values to the submit handler

**Comment by jedwards1211** [comment]
@leesei that logic is better put in a wrapper component anyway so that you don't have to pass `parse` and `format` props to every date field you make.
