### ISSUE TITLE
how to excute handleSubmit on change value

### ISSUE THREAD

**Issue by alirezavalizade** [erikras/redux-form#1742]
Im want when user is typing execute a function,but its not working.this is my code :

```
const StoresSearchForm = (props) => {
  const {handleSubmit, pristine, reset, submitting, invalid} = props;
  console.log("props", props);
  return (
    <form>
      <div>
        <div>
          <Field name="name"
                 onChange={()=>handleSubmit()}
                 component={InputGroupText} type="text" placeholder="Search"
                 className="form-control marginTop15"/>
        </div>
      </div>
    </form>
  )
};

export default reduxForm({
  form: 'storeSearchForm'
})(StoresSearchForm)
```

**Comment by aight8** [comment]
Currently you can achieve this with this hack:

```JS
      onChange={value => {
        input.onChange(value);
        setTimeout(handleSubmit);
      }}
```

**Comment by Guria** [comment]
How about asyncValidate + shouldAsyncValidate?

**Comment by mschipperheyn** [comment]
BTW, ()  => soneFunction will lead to a report render each and every time. It's a performance a it pattern. If that's a habit, I suggest unlearn in it. Read up on autobind-decorator

**Comment by Iuriy-Budnikov** [comment]
+1

**Comment by aight8** [comment]
#362

**Comment by aight8** [comment]
This code snippet from @kyleboyle is a good base to accomplish this centrally:
```
  componentWillReceiveProps(nextProps) {
    if (nextProps.dirty && nextProps.valid) {
      let doubleDirty = false;
      Object.keys(nextProps.fields).forEach(key => {
        if (nextProps.fields[key].value !== this.props.fields[key].value) {
          doubleDirty = true;
        }
      });
      if (doubleDirty) {
        nextProps.handleSubmit();
      }
    }
  }
```

An event callback option on reduxForm() level could be powerfull, too. Since the callback is optional and the calculation only occures when the option is given there is no performance drawbacks for all others. The problem now is that this solution is hidden from the majority of the users - maybe it were good to note this in the documentation.

Example callback events:
- onFormFieldValueChange(name, value)

The original question which this issue have to solve is:
- How get I notified if any of the form values are changing (ex: as submit the form on every change or periodically)

**Comment by aight8** [comment]
What do you think about it?

**Comment by TrevorHinesley** [comment]
@aight8 how do you do that in v6? Not seeing fields on props.

**Comment by gustavohenke** [comment]
Guys, #2576 (when it gets released) will solve this problem.
Then you will probably want to combine it with the [remote submit example](redux-form.com/6.5.0/examples/remoteSubmit/).
