### ISSUE TITLE
detecting focus on any field ?

### ISSUE THREAD

**Issue by jasan-s** [erikras/redux-form#1777]
this might be very obvious but how can i detect that field has focus , because on mobile the keyboard moves up and i need to adjust the UI accordingly.

**Comment by erikras** [comment]
Each `Field` component is given a [`meta.active`](http://redux-form.com/6.0.5/docs/api/Field.md/#-meta-active-boolean-) flag that you could detect changing from `false` to `true`. Something like that?

**Comment by jasan-s** [comment]
Yes, but it would be nice if it was in the passed down props. Because if I
use mapStateToProps to pass in that in, the app throws an error on startup
because the that state has not been initialized in redux.

**Comment by STEVEOO6** [comment]
+1

I am looking to implement a checkout payment credit card form with a visual credit card reference (using https://github.com/JohnyDays/react-credit-card) and I need to tell the Card component which field currently holds focus (so that the visual reference can spin around to display the CVC when the user is inputting that information).

![screen shot 2016-11-04 at 5 50 21 pm](https://cloud.githubusercontent.com/assets/4055977/19996987/7d76e0b6-a2b7-11e6-9290-213d938bda1c.png)

Ideally the form's would receive a prop containing the entire 'state' (values, meta, errors etc) of its Fields and the user could destructure the state accordingly.

Currently I'm planning to use the parse/normalize hooks and store the focus state myself.

**Comment by danielrob** [comment]
Not passing all the values/meta/errors as props as a default behaviour is, to my understanding, an intentional part of the api that helps keep it performant by default.  Otherwise you drift towards the v5 api which was revamped partly because of this problem.

Closing this usage question as it is nine months old since last update. There are now many ways provided to access the state information required, namely the [provided selectors](http://redux-form.com/7.0.3/docs/api/Selectors.md/).
