### ISSUE TITLE
Best way to  take input for date in redux-form?

### ISSUE THREAD

**Issue by jinxac** [erikras/redux-form#1797]
Hey,

I have a form in which have few fields which take date is inputs. Now, I tried searching a bit and I see that input type "date" is not supported by most of the browsers and hence cannot use that.

Now, I am using [react-datetime](https://github.com/YouCanBookMe/react-datetime) in few other places in my projects. Is it possible to use this in the forms too? In the end I just need the date in my values object under form right?

If not can you please suggest a good way to deal with dates under a form?

**Comment by Iuriy-Budnikov** [comment]
You can use any date picker. You need just rewrite onChange.
```onChange={value => field.input.onChange(value)}```

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
