### ISSUE TITLE
destroyOnUnmount should be false by default

### ISSUE THREAD

**Issue by mschipperheyn** [erikras/redux-form#1825]
I spent a lot of time struggling with a problem with submitErrors and judging by the number of issues on this subject, I am not the only one.

http://stackoverflow.com/questions/39597528/submit-validation-destroys-form-with-each-render-cycle/39598719#39598719

My forms were getting destroyed during submitValidation. It seemed weird.

It turns out that part of my submit validation is generating a global status message that leads to a new render cycle on my parent component. The new render cycle destroys the form unless I set destroyOnUnmount to false.

New render cycles are common and this is confusing. destroyOnUnmount:false should be the default

**Comment by davidkpiano** [comment]
Agree with this. The whole idea of Redux is an atomic global state that is not directly dependent on components, and should be agnostic to whether the form is mounted or not. The notion of `destroyOnUnmount` is more akin to local component state, not to Redux.

**Comment by erikras** [comment]
One thing I've learned about maintaining a library is that for every setting, there is a developer who thinks it should default the other way, to their specific use case, and cannot possibly _fathom_ what an idiot the lib author must be for defaulting it the wrong way.

This flag and behavior date back to [`v3`](https://github.com/erikras/redux-form/releases/tag/v3.0.0-beta-1), almost a year ago. It was instituted when everyone complained both, "Why is my form data still hanging around in Redux when I'm not using that form anymore?" and "Why does my form still have the previous data in it when it has already been submitted?"

Why is it the default?

- Developers are used to their high level garbage collected languages that clean up after they are no longer using data.
- Many applications use dozens or even hundreds of form components between browser reloads, and all that memory does add up.
- I have been using `redux-form` in production since the beginning, and I have never once needed or wanted my form data to persist after the form has been unmounted. I generally edit or create a record and then the form can be discarded.

Of course I concede that just because I have never needed it the other way does not mean that others do not, which is why it's a setting. It's also nearly impossible to know how many people fall on one side or the other on an issue like this. And of course changing it would be a breaking change, which no one likes.

**Comment by kevinzwhuang** [comment]
To touch on the technical issue, I think there might be something wrong with your submit validation @mschipperheyn, or at least somewhere along your submit flow there is a bug in your implementation that is causing the form component to become unmounted during your submit event. As long as the form is mounted, it should behave as expected

I have never had a form getting destroyed due to a submit action. Also regular render cycles within react should not unmount the whole form component either to cause the destroy action.

Form data is only cleaned up when the component is no longer needed and unmounted. I'm pretty happy with the destroyOnUnmount set to `true` on default and have always expected it to behave this way. It's reasonable for most developers & users to expect garbage to be removed after the data is no longer needed.

**Comment by mschipperheyn** [comment]
@kevinzwhuang Ok, yes, you may be right. Learning more about React every day. I will review this. One thing I'm running into when I set destroyOnUnmount:false is that submitErrors are not getting cleared after first submit. It leads to me only effectively being able to submit once. The stored submitError prevents subsequent submits. Could this be related to destroyOnUnmount:false?
