### ISSUE TITLE
How to use select2 with redux-form 6?

### ISSUE THREAD

**Issue by hgminh95** [erikras/redux-form#1826]
In v5, I can do something like:

``` javascript
const fields = ['concepts[]']

class Input extends Component {

  componentDidMount() {
    const {
      fields: { concepts}
    } = this.props

    $("select").select2()
      .on("select2:select", function(e) {
        let addId = Number(e.params.data.element.value)
        concepts.addField(addId)
      })
      .on("select2:unselect", function(e) {
        let removedId = Number(e.params.data.element.value)
        concepts.removeField(concepts.findIndex(id => id == removedId))
      })
  }

  render() {
    ...
  }

}
```

But it does not work in v6 anymore.

I found a [page](http://redux-form.com/6.0.5/docs/faq/CustomComponent.md/) about custom component but don't know to to apply it to select2.

**Comment by gustavohenke** [comment]
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag and the equivalent for Select2.

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
