### ISSUE TITLE
in wizard how to take value on each step

### ISSUE THREAD

**Issue by gmchaturvedi1** [erikras/redux-form#1842]
in wizard how to take value on each step .We just want to save that form on every steps but want value should in form also.

Can anyone suggest?

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
