### ISSUE TITLE
Combining values selector and initialValues from state

### ISSUE THREAD

**Issue by Haraldson** [erikras/redux-form#1878]
I’ve had some trouble getting everything to work, as the order of `connect` and `reduxForm` is relevant.

Just pasting in my relevant setup for reference;

``` javascript
import { connect } from 'react-redux'
import { reduxForm, getFormValues } from 'redux-form'

const form = 'foo'
```

I’m able to extract the form `values` as they change if I do it like this, but then `initialValues` doesn’t get set on the form fields:

``` javascript
FormComponent = connect(
    (state, props) => ({
        values: getFormValues(form)(state),
        initialValues: props.id ? state.foo[props.id] : {}
    })
)(FormComponent)

export default reduxForm({ form })(FormComponent)
```

If I do it the other way around, I face the exact opposite problem – `initialValues` are set, but I’m unable to read out the form `values` as I edit those initial values;

``` javascript
FormComponent = reduxForm({ form })(FormComponent)

export default connect(
    (state, props) => ({
        values: getFormValues(form)(state),
        initialValues: props.id ? state.foo[props.id] : {}
    })
)(FormComponent)
```

---

Is there a way to get both to work, and how does that syntax look, if so?

**Comment by Haraldson** [comment]
[Possibly related](https://github.com/erikras/redux-form/issues/1744)

**Comment by umidbekkarimov** [comment]
In first example components goes like this:

reduxForm -> connect -> FormComponent

`initialValues` goes to `FormComponent`, not to `reduxForm`
And `connect` can read `values` because `reduxForm` has created them (you can access them also in `props.values`)


In second example components goes like this:

connect -> reduxForm -> FormComponent

So redux-form gets `initialValues` from `connect` but connect can't see `values` because `reduxForm` didn't create them yet.


You don't need `getFormValues` because redux-form should pass values to your component anyways http://redux-form.com/6.0.5/docs/api/ReduxForm.md 

To remove complexity I suggest you to use `compose` function (from redux, recompose or lodash)


```javascript
const enhancer = compose(
  connect(),
  reduxForm()
)

export default enhancer(Form)
```

**Comment by Haraldson** [comment]
That works nicely, @umidbekkarimov! I used `_.flowRight`, as it’s now called.

It would have been nice if the docs included more detail on how the data flows, @erikras – but maybe just mentioning how you can compose this way would help?

**Comment by danielrob** [comment]
Closing this question as it appears resolved. Documentation PR's welcome.

**Comment by NikeOnly** [comment]
@umidbekkarimov just perfect soluthion! Thank you so much)
