### ISSUE TITLE
[6.0.5] Props {name} undefined in FieldArray

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [erikras/redux-form#1886]
```
const renderRadios = ({ fields, disabled, name, handleChange }) => {
  console.log(name);
  return (
    <div>
      {fields && fields.length > 0 && fields.map((c, i) =>
        <Field disabled={disabled} name={name} type="radio" key={i} component={renderRadio} handleChange={handleChange} label={c.label} value={c.value} />
      )}
    </div>
  );
};
```

```
<FieldArray name="field" fields={[ {label: 'True', value: 'true', name: field.name}, {label: 'False', value: 'false', name: field.name} ]} component={renderRadios} {...rest} />
```

**Comment by clayne11** [comment]
I already created #1866 pointing out this issue and also created the PR #1867 to address this issue.

**Comment by pcalves** [comment]
@Iuriy-Budnikov In case you missed it, #1867 which fixes this has been merged. 🎉

**Comment by huan086** [comment]
FieldArray `props.name` is not documented and current behavior is flawed (i.e. gets prefixed) when nested inside FormSection. Thus, your radio name will get prefixed twice, once by FieldArray, and 2nd time by Field. I've sent a PR to remove `props.name` and get `props.fields.name` (that has the same behavior as `props.name` now) documented,

For your case, pass an additional custom prop

`<FieldArray name="field" radioName="field" ...`

and use

`const renderRadios = ({ fields, disabled, radioName, handleChange }) => {`

Hopefully `props.name` can return in the future as a pass-through so that your code works correctly.

**Comment by danielrob** [comment]
This was mostly finished up. @huan086 regarding the concern about props.name getting prefixed, there is an issue for this here #3106. If this is still important to you please add a comment there! 

Briefly though, note in recent versions the iterator returns the unprefixed name which solves this problem for most people, and there is a simple workaround if you want the unprefixed name which is to pass an alternate prop with the unprefixed name.
