### ISSUE TITLE
Unable to import from redux-form/immutable

### ISSUE THREAD

**Issue by cutbko** [erikras/redux-form#1998]
I am trying to migrate my app from "redux-form": "^5.3.1" to  "redux-form": "^6.1.1". My store is immutable using "immutable": "^3.8.1". When I am doing:

`import { reducer as form } from 'redux-form/immutable';`

I am getting the following error:

![image](https://cloud.githubusercontent.com/assets/5887531/19554446/471415b8-96c1-11e6-832a-4c395b57fa12.png)

What can be the issue?

**Comment by iyn** [comment]
Do you import `reduxForm`, `Field` etc. also from `redux-form/immutable`, similarly to reducer import? This should be something like this:
```
import { Field, reduxForm } from 'redux-form/immutable'
```

**Comment by cutbko** [comment]
@iyn when I import anything from 'redux-form/immutable' I get the same error from issue screenshot

**Comment by iyn** [comment]
@cutbko  First of all: I guess you're splitting your application code into `main.js` and `common.js`, but I can see on the screenshot you posted that the file is named `common.js.js` and there's an error about unsupported MIME type, which probably means that it's 404 error page instead of `common.js` file. Can you verify that `common.js` is loaded properly (you can check the Network tab in Chrome dev tools - you probably need to change the name from `common.js.js` to `common.js`)?

If this doesn't solve the problem, can you post your store initialization code and maybe some snippet where you're using `redux-form` in your app?

**Comment by cutbko** [comment]
@iyn I fixed the common.js name but still have the same issue. "unsupported MIME type" error comes from sw.js because the site is not https: http://prntscr.com/cz6wqn

stpre initialization code:

`const store = configureStore(Immutable.Map(), browserHistory);`

```
const sagaMiddleware = createSagaMiddleware();
const devtools = window.devToolsExtension || (() => noop => noop);

const setLocationMiddleware = store => next => action => {
  if (action.type !== SET_LOCATION) {
    return next(action);
  }

  return store.dispatch(push(action.location));
};

export default function configureStore(initialState, history) {
  const middlewares = [
    sagaMiddleware,
    routerMiddleware(history),
    setLocationMiddleware,
  ];

  const enhancers = [
    applyMiddleware(...middlewares),
    devtools(),
  ];

  const store = createStore(
    createReducer(),
    initialState,
    compose(...enhancers)
  );

  // Extensions
  store.runSaga = sagaMiddleware.run;
  store.asyncReducers = {}; // Async reducer registry

  // Make reducers hot reloadable, see http://mxs.is/googmo
  /* istanbul ignore next */
  if (module.hot) {
    module.hot.accept('./reducers', () => {
      System.import('./reducers').then((reducerModule) => {
        const createReducers = reducerModule.default;
        const nextReducers = createReducers(store.asyncReducers);

        store.replaceReducer(nextReducers);
      });
    });
  }

  return store;
}
```


```
import Immutable from 'immutable';
import { combineReducers } from 'redux-immutablejs';
import { LOCATION_CHANGE } from 'react-router-redux';
import helpers from 'utils/helpers';

const routeInitialState = Immutable.fromJS({
  locationBeforeTransitions: null,
});

function routeReducer(state = routeInitialState, action) {
  switch (action.type) {
    case LOCATION_CHANGE:
      return state.merge({
        locationBeforeTransitions: action.payload,
      });
    default:
      return state;
  }
}

import appReducer from 'containers/App/reducer';
import { reducer as form } from 'redux-form/immutable';

export default function createReducer(asyncReducers) {
  return combineReducers({
    route: routeReducer,
    app: appReducer,
    form,
    ...asyncReducers,
  });
}

```

no need to attach the ussage snippet because it fails trying to `import { reducer as form } from 'redux-form/immutable';` even if I don't use it further.

**Comment by iyn** [comment]
Can you try removing hot reloading reducers and check whether this can be an issue? Also, can you post screenshot/copy the whole stack trace from the console (click on the arrow next to the error that says 'Uncaught TypeError...`). I'll try to look more closely at this issue later today.

**Comment by cutbko** [comment]
@iyn removing hot reloading reducers didn't help, stack trace:
![image](https://cloud.githubusercontent.com/assets/5887531/19731064/dc0d0084-9ba4-11e6-9f20-f94c7d07d350.png)

**Comment by iyn** [comment]
Have you tried using https://github.com/gajus/redux-immutable/ instead of https://github.com/indexiatech/redux-immutablejs?

My guess right now is that it's not a problem with `redux-form` but something else, like root reducers not using Immutable. Is everything working when you remove `redux-form` from root reducers? Is the state in fact using Immutable?

**Comment by cutbko** [comment]
@iyn yes, I tried. State is immutable. Previously I was using redux-form 5 with following wrapping:

```
 function immutableFormReducer(state = Immutable.fromJS({}), action) {
    return Immutable.fromJS(formReducer.normalize({
    })(state.toJS(), action));
  }
```

**Comment by iyn** [comment]
Are you using `react-hot-loader` < 3? If so, update it to the latest version and check if that solves the problem.

**Comment by cutbko** [comment]
I am using "webpack-hot-middleware": "^2.13.0" and not using react-hot-loader

**Comment by iyn** [comment]
And what about `redux-devtools-extension`? It seems that the `window.devToolsExtension` is being depreciated (https://github.com/zalmoxisus/redux-devtools-extension/issues/220) - does using the current configuration helps? If no, have you tried removing all config from the store init (sagas, devtools etc.) besides `redux-form` reducer? The thing is, it works ok when I try it. If that step doesn't help, can you try removing `node_modules` dir, clearing `npm` cache (https://origin1tech.wordpress.com/2013/08/31/clearing-nodes-npm-cache/) and installing all packages again? This may seem strange but in fact it solved my problems few times in the past.

**Comment by cutbko** [comment]
@iyn still nothing helps

**Comment by iyn** [comment]
Bug hunting continues ;).

What happens when you comment out the `redux-form` import and then in your `combineReducers` replace `form` with:

```
form: () => return Immutable.Map()
```
?

what about if you use:
```
form: () => return (0, immutable.Map)()
```
?

I just want to see if something strange happens in above cases.

After showing what happens, please go back to the original import and reducer. Now, can you edit the file that happens to be problematic (`node_modules/redux-form/lib/structure/immutable/index.js`) and add multiple `console.log`s there:
```
// after immutable import
console.log('imported immutable:');
console.log(_immutable);
console.log((0, _immutable.Map));
console.log((0, _immutable.Map)());
```

Have you tried removing/commenting out other reducers, sagas, middlewares etc. and only leaving `redux-form` code? Have you tried removing/commenting out all `redux-form` usage across your app and leaving just store/reducer init with `redux-form` reducer?

**Comment by cutbko** [comment]
when I set: "form: () => return Immutable.Map()" form loads fine but doesn't react on change events. 
I am unable to put console in source file, probably it is cached somewhere. 

I am attaching you the [project.zip](https://github.com/erikras/redux-form/files/559936/project.zip), I have removed everything except required code to see the issue. Run npm install and npm start and open in browser: http://localhost:3000/anything
(there may be issue with webpack, if so run: npm uninstall webpack --save-dev        and then npm install webpack@2.1.0-beta.22 --save-dev )

**Comment by iyn** [comment]
I didn't solve the issue but I think I have an idea about the problem. It seems that there's something wrong with the configuration, specifically about importing/requiring modules. When I added `console.logs` to the `redux-form` file in the `node_modules`:
```js
var Immutable = require('immutable');                                                                                                                                                                            
console.log(_immutable);   
```

this is the output:
```
Object {__esModule: true}
```

Which means that `Immutable` is not loaded/imported properly. I guess it has to do something with CommonJS and webpack.

Can you play a little with the webpack config? You may try to migrate to the latest webpack beta. I also had some problems with previous webpack versions and in some cases updating helped. Note that this required updating webpack config files to the new structure.

**Comment by iyn** [comment]
These issues may be related:
https://github.com/webpack/webpack/issues/706
https://github.com/webpack/webpack/issues/2945

And it only gives me more confidence that this is webpack/CommonJS-related bug.

**Comment by danielo515** [comment]
May this issue be related to erikras/redux-form#1637 ?

**Comment by guilherme** [comment]
any ideas on solving this? 😢

**Comment by iyn** [comment]
@guilherme As I mentioned earlier and what @danielo515 linked, everything points to webpack and import-related issue. Until it's solved, you can try downloading the `redux-form` source directly from github (I advise to use tagged snapshot, instead of the current `master`), changing the build configuration. I didn't try it myself, but in this thread: https://github.com/erikras/redux-form/issues/1637 @carlos-peru said that changing this file: `internals/webpack/webpack.base.babel.js` from

```
mainFields: [
  'browser',
  'jsnext:main',
  'main',
]
```

to
```
mainFields: [
  'browser',
  'main',
  'jsnext:main',
]
```

was a working workaround - this may be something that helps.

**Comment by cutbko** [comment]
hi @iyn 
I have finally migrated my project to webpack 2 rc3 and it helped. I seamlessly upgraded my project to redux-form 6.4.1 and using  'redux-form/immutable'

**Comment by iyn** [comment]
@cutbko: that's great to hear! I was thinking about this issue from time to time, wondering what was the problem. I'm glad you finally resolved it :)
