### ISSUE TITLE
Removing modified redux-form fields does not remove the value from state

### ISSUE THREAD

**Issue by tedscape** [erikras/redux-form#2032]
Hi @erikras,
First of all, redux-form is a lifesaver.
I face an issue, not sure if its a bug or intended to be that way.
This occurs when you have some dynamic fields. In my case we have 20 different templates to be loaded on selection of different combinations. So if you edit a template, then change your mind and select another template, the modified values still stays in the state as shown in the GIF and from the examples page in redux-form.

http://redux-form.com/6.1.1/examples/selectingFormValues/

![redux-form](https://cloud.githubusercontent.com/assets/2619392/19752984/087e40f8-9c4d-11e6-898b-f6df9b02cfc3.gif)

I looked for a function that can help me out to clear it, but did not find it. Can you point me in the right direction?

**Comment by iyn** [comment]
IMO this is expected behavior in that example. If you want to clear/remove some values conditionally, you need to do this manually. For example, when "Has Email?" in unchecked, you can manually dispatch action (http://redux-form.com/6.1.1/docs/api/ActionCreators.md/) that clears a particular field in the store.

**Comment by tecnolocoEdan** [comment]
Hi, as far as know the only thing we can do with those actions is to set the desired filed value to null, this with the action "change". Note that removing a field from a fieldarray takes out the value of that field from the store.

**Comment by durunvo** [comment]
this is an example using redux store's middleware

```
import { change, actionTypes } from 'redux-form';

export default ({ dispatch }) => next => action => {
    if (action.type === actionTypes.UNREGISTER_FIELD) {
        dispatch(change(action.meta.form, action.payload.name, null));
    }
    next(action);
};

```

**Comment by gustavohenke** [comment]
Here are some ways to solve this problem (and you could probably find another one):

- Listen to onChange directly on that field
- Use a combination of [`formValueSelector`](http://redux-form.com/6.5.0/docs/api/FormValueSelector.md/) + `connect` from React Redux + `componentWillReceiveProps`

**Comment by minbelapps** [comment]
I don't agree that it's an expected behavior. It could be a flag for the form for clearing such fields. The man was one the Moon before I was born, but we need to micro transactions such things.

**Comment by blazestudios23** [comment]
This is not expected behavior. In HTML if a field ceases to exist, then the data is not submitted. There should be a flag added that will allow the data to be kept, if desired. But by default the state should clear if a field unmounts. I have no idea why one would expect non-existent components to send data to state. 

Clearing the data manually just adds a lot of overhead. I have a form with about 50 fields that may or may not load dynamically. And this form is used to initiate an important process, so each Field has to be manually handled now.
