### ISSUE TITLE
material-ui datepicker usage example?

### ISSUE THREAD

**Issue by pcompassion** [erikras/redux-form#2050]
I'm having hard time to use material-ui's datepicker with redux-form.

When I submit form, values for fields of datepickers are not included in the `values` parameter.  

http://redux-form.com/6.1.1/examples/material-ui/ doesn't show datepicker example.   
I tried redux-form-material-ui, and it's giving me errors (https://github.com/erikras/redux-form-material-ui/issues/37 Invalid prop `value` of type `string` supplied to `DatePicker`, expected `object`.)

https://github.com/erikras/redux-form-material-ui/issues/37 

has `value={input.value}`, what is input.value supposed to represent? current value of the form field entered by user? 

The simple example (http://redux-form.com/6.1.1/examples/simple/) has no mention of `value`  but it works fine without it, and now I need to use value for datePicker and don't see how it fits.

* edit

Here's my findings.

> 
> input.value: any
> 
> The value of this form field. It will be a boolean for checkboxes, and a string for all other input types. If there is no value in the Redux state for this field, it will default to ''. This is to ensure that the input is controlled. If you require that the value be of another type (e.g. Date or Number), you must provide initialValues to your form with the desired type of this field
> 

So I added to MyForm components
```

const mapStateToProps = (state, ownProps) => {
  let dateRange = {}
  try {
    dateRange = state.batchOperation.selectMethod[DateRangeViewConfig.configName]
  } catch(e) {
  }

  let initialValues = _.defaults({}, dateRange, {
    fromDate: new Date(),
    toDate: new Date(),
  })

  return {
    viewConfigs: state.viewConfigs,
    viewConfig: state.viewConfigs[BatchOperationFormViewConfig.configName],
    batchOperation: state.batchOperation,
    initialValues: initialValues
  }
}
```

MyForm uses another component which uses DatePicker 

```

  render() {
    return (
      <div>
        <Field
          name="fromDate"
          component={
            ({ input, label, meta: { touched, error }, ...custom }) => {
              console.log("input", input)
              return (
                <DatePicker
                  onChange={this.onChangeFromDate}
                  hintText="from"
                  autoOk={true}
                  value={input.value}
                  />
              )}
        } />
    )
  }

```
and on date change, I update the redux store 

```
  onChangeFromDate(_, date) {
    this.fromDate = date
    const { dispatch } = this.props
    dispatch(dateRangeSelect(this.fromDate, this.toDate))
  },

```

Now I can see `fromDate/toDate` in submit handler. that's good!

But there's another error which I think comes from the store update part.

> warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the DatePickerDialog component

And another problem is {input.value} still points to the old `initialValues`. 
I checked the store value is properly updated with a new date.

**Comment by brunobraga95** [comment]
Same Problem, 
 I am using [](https://github.com/Hacker0x01/react-datepicker) as DatePicker with a custom input. Redux-Form  does not recognize it when I wrap it inside a Field component, no changes or updates are listened. I can see that it actually makes sense, since I am not actually passing an input component to Redux-Form.

What I am doing is: Field -> DatePicker -> InputComponent.

Any idea how I can make redux-form to bing with my input?

`                      <Field component={DatePicker} style='warning' label='DatePicker Warning' />
`

**My datePicker Component that uses a third component called CustomInput**

`  const input = this.props.input

    const style = this.props.style
    const label = this.props.label
    return (
      <DatePicker
        customInput={<CustomInput input={input} style={style} label={label} />}
        selected={this.state.startDate}
        onChange={this.handleChange}
      />
    )`

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
