### ISSUE TITLE
Reset file input field

### ISSUE THREAD

**Issue by samhagan** [erikras/redux-form#2074]
I have form that accepts a file input type.  Everything works perfectly fine, except that when I try to reset just that field it doesn't work.  I can see the redux event fires, but the value for `photo` does not change.

The form shown below is not all the fields and I want to provide the user the ability to not upload a profile image.  I have referenced the below issue and tried the options (this.props.fields.myField.onChange looks to have been removed from props).

Referenced issue: https://github.com/erikras/redux-form/issues/709

```(javascript)
resetImage = () => {
    // reset the redux store
    const { change } = this.props
    change('photo', undefined)
}

<form onSubmit={handleSubmit(this.submit)}>
  <Field
      name='photo' component={FileInput}
      onChange={this.handlePreview} type='file' capture='camera'
  />
</form>

const FileInput = ({ input, label, meta: { touched, error }, ...custom }) => (
  <Input
    label={label}
    error={touched ? error : ''}
    {...input}
    {...custom}
    onChange={(...args) => {
      input.onChange(...args)
      custom.onChange(...args)
    }}
  />
)
````

**Comment by niksajanjic** [comment]
When you set ```type="file"``` on Field component value is not passed down to your component by design of Redux-Form. Reason for this is that you can't dynamically set value on input of file type as you would get error like this:

```Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.```

What this means is that you can only set value to an empty string. But how to do that if value isn't passed down to your Field component?

If you follow this PR that got merged you will see that in case of file type values isn't passed down. But you can also not set file type on Filed component but instead directly to your input tag.

```
const FileInput = ({ input: { value, ...input }, label, meta: { touched, error }, ...custom }) => (
  <Input
    type="file"
    value={value === '' && value}
    label={label}
    error={touched ? error : ''}
    {...input}
    {...custom}
    onChange={(...args) => {
      input.onChange(...args)
      custom.onChange(...args)
    }}
  />
)
```

You can see that I'm putting file on input and it should be removed from Field component. Now value will be passed down and it's up to you to make sure you don't assign value to input in case it isn't empty string. I can't guarantee this ```value={value === '' && value}``` works, but you can try. Also, anytime you select image from your PC you already have that image inside Redux-store as FileList that contains that File and you can access it using selectors if you need to.

**Comment by samhagan** [comment]
@niksajanjic thanks for your help.  This works for my use case.
