### ISSUE TITLE
FieldArray - Adding from empty, then removing all, form stays dirty

### ISSUE THREAD

**Issue by mcrawshaw** [erikras/redux-form#2102]
When I create a new FieldArray into an undefined field, reversing the user action does not return the field to undefined.  In other words, if the user adds some entries to an empty field array, then changes their mind and removes them, I would like to return the save button back to disabled.

This is at odds with Field which will completely remove the field from the "values" state object.

I have attempted the following work arounds, the first does not have the desired effect, and the second is not available as part of the FieldArray API.

```
<FieldSpecForm
   key={i}
   fieldSpec={field}
   onRemove={() => fields.length === 1 ? fields.removeAll() : fields.remove(i)}
   parentFormName={FORM_NAME}
/>
```
```
<FieldArray
   name={`globalFieldSpecs[0][${secondaryTabIndex}]`}
   component={renderFieldSpecs}
   normalize={(value: Array<any>) =>
      (value && value.length === 1 && value[0].length > 0) ? value : undefined
   }
/>
```

I guess the most optimal solution would be to revert the state back to "initial", but I'm not sure how to accomplish this...

**Comment by markau** [comment]
If I correctly understand what you are trying to do, then I was trying to do something similar. Rather than `pushing` new elements into the `arrayField`, I dispatched an action (with the new object as a parameter), and in the `action Creator` I added the new object to the `values.myArray` state property. When this was mutated correctly (as below), and if the new element was later removed from the `fieldArray`, the form realised when it was back to a pristine state, and the save button is disabled appropriately.

        return {
          ...state,
          values: {
            ...state.values,
            myArray: action.payload 
          }
        }

I had a lot of trouble getting this state object to update in a way such that the form would recognise a pristine state, but this with the ES6 spread operator [from the docs](http://redux-form.com/6.2.0/docs/api/ReducerPlugin.md/) finally worked for me. 

If this is not relevant to your scenario then please disregard. I have been staring at this for too long today :smile:

**Comment by mcrawshaw** [comment]
Oh wow, I didn't read that section of the docs.  What a great feature, I love when the power of flux really shines through other libraries.
This should solve my problem, thanks for the help!

**Comment by markau** [comment]
Hey @mcrawshaw I'm glad it helped, because re-reading what I wrote only a few days ago I barely understand it myself 😁 

The [Change prop](http://redux-form.com/6.2.0/docs/api/Props.md/#-change-field-string-value-any-function) works well for single field values and I wonder whether it could be extended to provide an abstracted way to handle the above for arrays. For example: 

`changeArray(field:Array, operation:[push | slice] newValue:any) : Function`

What do you think @erikras?
