### ISSUE TITLE
Dont REGISTER_FIELD with new object

### ISSUE THREAD

**Issue by khotey** [erikras/redux-form#2136]
I have init object:
`partner = {};`

```
PartnersUpdate = reduxForm({
  form: 'partner-update'
})(PartnersUpdate);

function mapStateToProps({ partners, languages: { lang } }) {
  let { partner } = partners;
  
  return {
    partners,
    lang,
    initialValues: partner // {}
  };
}
```

When response comes from server 
```
partner = {
  name: { en: 'name-partner' }
}
```

But form dont reinitialize when comes new object

When init value `partner = null`

```
function mapStateToProps({ partners, languages: { lang } }) {
  let { partner } = partners;

  if (!Object.keys(partner).length) {
    partner = null;
  }

  return {
    partners,
    lang,
    initialValues: partner // null
  };
}
```

When null replaces by object form reinitialize, is it feature or bug ?

**Comment by gustavohenke** [comment]
Eh, almost a year later.. ⏳ 

What was likely going on here was your `partner` object was mutated.
But, because we would need to see how the reducer is behaving, I can't tell this for sure.

Will close, but feel free to continue the discussion, or open new issues if you can provide evidences of bugs!
