### ISSUE TITLE
Import React where react is not used

### ISSUE THREAD

**Issue by danielo515** [erikras/redux-form#2157]
Please flag this issue as question.

I was wondering why are you forced to import React on every place you use redux-form. I suffered this when I removed the `import React from 'react'` statement from a redux-form file that was not using React at all. I noticed this patter in all the examples, so the question is, why is it necessary to import React on every place?

**Comment by bmv437** [comment]
If you use `Field`, `Fields`, `FieldArray`, or `FormSection`, all of those are React components, so you need React to render them. also, if you have any JSX in your code, you need to import React so it knows how to handle the JSX. also, the `reduxForm` decorator generates a decorated form React component. Does that answer your question?

**Comment by gustavohenke** [comment]
> I was wondering why are you forced to import React on every place you use redux-form

It's more like everywhere you use JSX.
This is because most transpilers (Babel, TypeScript) target React primarily when they find some JSX, although you could customize them to use something else.

As a workaround, in my project I set a global variable React, so I don't need to care about importing it.

**Comment by danielo515** [comment]
Thank you all for all your answers. Both answers totally clarifies my doubts. 
Thank you very much
