### ISSUE TITLE
need react-widgets DropdownList defaultValue and onChange example

### ISSUE THREAD

**Issue by pepepaco** [erikras/redux-form#2188]
Id like an example how to initialize the react widgets, defaultValue doesn't seems to work, also the onChange event is not firing this is for DropdownList.

it could be that these are not compatible with redux-forms?

thanks.

**Comment by jole78** [comment]
I don't know if this is exactly what you're looking for but this is sort of how I use the DropdownList from react-widgets together with redux-form.

```javascript
const example_data = [{key:'1', text='item one'}, {key:'2', text='item two'}]
<Field data={example_data} name="the_prop_to_update" valueField="key" textField="text" component={DropdownListField} />

....

const DropdownListField = (props) => {
  	function handleChange(option) {
		let value = option

		const {valueField} = props

		if (valueField) {
			value = option[valueField]
		}

		props.input.onChange(value)
	}
   
         return (
         <DropdownList {...props} value={props.input.value} onChange={handleChange} />
         )
}
``` 

What you need to do is tell the DropdownList what your text and values fields are from the data that you want to display. An depending on your needs you might also need to override the OnChange handler since DropdownList will send the entire object in onChange and you might only want the value property...normal behavior for select option otherwise.

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
