### ISSUE TITLE
Async validate should treat empty object as valid result

### ISSUE THREAD

**Issue by just-boris** [erikras/redux-form#2198]
When synchronous `validate` returns an empty object `{}` it will be interpreted as a form is valid. [Relevant source code](https://github.com/erikras/redux-form/blob/60837193418b0b6e8a27770ca69636a897a531d9/src/reduxForm.js#L142)

But asynchronous validation throws any not empty result. ([Source code](https://github.com/erikras/redux-form/blob/60837193418b0b6e8a27770ca69636a897a531d9/src/handleSubmit.js#L73)). It means that you can't submit a form when ayncValidate resolves an empty object.

I think that we should allow empty object as a valid result for asyncValidation as well for the sake of consistency.

**Comment by gustavohenke** [comment]
I went back to v6.1.0, and found no evidence of this problem:
https://jsfiddle.net/gustavohenke/qghjemfh/

All I get is that mesage "Asynchronous validation promise was rejected without errors". But the form is considered valid.
If I resolve the promise instead of rejecting it, there are no messages, and the form will work as well.

**Comment by just-boris** [comment]
Strange... I my case it didn't work. Thank you for taking your time, will look again to find a difference between your code and mine.
