### ISSUE TITLE
Ability to not reset form error key on any blur event

### ISSUE THREAD

**Issue by iamdustan** [erikras/redux-form#221]
Currently the global form error is being reset on an arbitrary blur event from within the form. A use case we would like to support is specific errors for validation and a general form error for an API response. This is possible with something similar to the following:

```
reduxForm({
  onSubmit(values, dispatch) {
    return new Promise((resolve, reject) {
      dispatch(ApiAction).then(result) => result.error ? reject({_error: result.error}) : resolve());
    });
  }
});
```

The issue is that as soon as the user interacts with the form again that error is reset. To get around this we’re putting this semi-persistent state into another part of the redux tree. It would be *extremely* convenient to not have the global error reset by an arbitrary action.

**Comment by erikras** [comment]
You've convinced me. The default behavior is wrong. In `v3.0.0` it won't reset `_error`.

**Comment by erikras** [comment]
Fixed in v3.

**Comment by smilingpoplar** [comment]
@erikras Now in v3, how to reset `_error` when any input field changed?

**Comment by erikras** [comment]
@smilingpoplar There is currently no way. :disappointed:

**Comment by cyberthom** [comment]
Slightly puzzled by this - What's the use case for continuing to show an error message after the user changed/corrected a form field? Whatever the server responded with that is displayed in `_error` surely doesn't apply anymore?

**Comment by iamdustan** [comment]
The automatic removal of `_error` isn’t necessarily accurate just because someone touches a form field. Persisting the error message until the async validation that put the global error there in the first place is the more sensible default over removing it the moment the form is interacted with again.

**Comment by cyberthom** [comment]
Apologies but I still don't understand why a general form error should behave different to an individual field error. 

After a user changes any form field, whatever the async handler based it's decision on previously to return an error doesn't hold true any longer. In other words, the error displayed doesn't relate to what the user entered at all. 

It's a bit like saying inline validation is a bad default - I'm sure there's also a valid use case to e.g. continue showing a previous validation error for a form field, until the user hits submit again, rather than continuously validating it. However, if the rest of your validation errors don't behave like that why should `_error`? 

Ignoring what should be the default or not - What are my options to reset `_error`. Is there a way to do it using the `validate(values, props)` method?

**Comment by valerybugakov** [comment]
Hey @cyberthom, did find any solution for this problem? I'm facing the same issue.
