### ISSUE TITLE
How to access fields with the new API

### ISSUE THREAD

**Issue by neilst** [erikras/redux-form#2216]
How can fields be accessed in the Form ? 

It looks like in the previous API one could define fields: {} in the decorator and then access them using props.fields.fieldname.onChange etc...

When I do this with v6.2.1 I just get an array of string values... 

Thanks

**Comment by swp44744** [comment]
Assuming you are using redux-form 6*, If you want to access individual fields in your form, then you can do something like this:
`const selector = formValueSelector('redux-form-name');`

`function mapStateToProps(state) {`
`  const fieldValue = selector(state,'form-field-name');`
`  return{`
`    fieldValue`
 ` }`
`}`

**Comment by swp44744** [comment]
and you can access the fieldValue as `this.props.fieldValue` anywhere in your component

**Comment by dcurletti** [comment]
@swp44744 I think you may have also answered my question from #2215 .  Checking now.

**Comment by dcurletti** [comment]
@swp44744 how would you access field values that are created by the `FieldsArray` object.  I haven't yet found a way to do that.

**Comment by swp44744** [comment]
**@dcurletti** I haven't tried for FieldArray but you can do something like this. 
instead of field name in selector pass the FieldArray Name
for example
`<FieldArray name="personInfo" component={renderHobbies} />`
`const fieldArrayValues = selector(state,'personInfo');`

your **fieldArrayValues** should be array of objects. then you can map through array of an object, something like this:
`Object.keys(fieldArrayValues).map((fieldArrayItem, index) => {`
`console.log('field#', index, fieldArrayValues[fieldArrayItem].fieldName);`
`});`

**P.S:** fieldName is the Field name in your FieldArray. Please also refer to the good documentation on redux form selecting form values:
http://redux-form.com/6.0.0-alpha.11/examples/selectingFormValues/

**Comment by dcurletti** [comment]
ok thanks, I'll try that out.

**Comment by neilst** [comment]
@swp44744, Thanks, that works to get the fields value ... but I would like to get hold of the actual field instance in order to get access to the input inside.

I was considering using refs but that cannot be used with stateless functions.

**Comment by dcurletti** [comment]
@swp44744 Thanks for the help.  Unfortunately, that wasn't quite what I was looking for.

**Comment by neilst** [comment]
I have taken the approach of using the change() function and passing in the field name. Will close the issue.

**Comment by neilst** [comment]
Just came across this related issue now - https://github.com/erikras/redux-form/issues/1312
