### ISSUE TITLE
Dropdown List w/ react-select : Field stays focused after being selected and value disappears onBlur

### ISSUE THREAD

**Issue by firaskrichi** [erikras/redux-form#2229]
Dropdown List w/ react-select : Field stays focused after being selected and value disappears onBlur 

```
let options = [
    { value: 'Denmark', label: 'Denmark' },
    { value: 'US', label: 'US' }
  ];

const renderDropdownList = ({ input, meta: { touched, error }, ...rest }) => (
  <div className='input-wrapper'>
    <Select {...input} {...rest}/>
    {touched && ((error && <span className='input-error'>{error}</span>))}
  </div>
)

<Field name="country" options={options} type="text" component={renderDropdownList} placeholder="Country"/>
```

Does anyone have a similar problem?

**Comment by klk1010** [comment]
I ran into a similar issue with `react-toolbox` dropdown. Making an initial or new selection worked as expected. However, when I click on the dropdown to change an existing selection, but click away instead of making a new selection, the previous value disappears. I'm still on `redux-form` 6.1.1, but v6.3.0  [docs](http://redux-form.com/6.3.0/examples/react-widgets/) provide the same hint which I found helpful: 

> ...Needs  `onBlur` to be rewritten ignoring the parameter...

When I caught the onBlur being passed from `Field` to my dropdown component, the bug disappeared. In my situation I updated my dropdown to be: 

```
const MyDropdown = ({ className, input, meta: { touched, error }, ...custom }) => (
  <Dropdown
    className={cn(style.echoDropdown, className)}
    error={touched && error ? error : ''}
    {...input}
    {...custom}
    onBlur={() => console.log('bug squashed!')} // I'm the important line
  />
);
```
but you could also do it case by case if you wanted to by adding it to `Field` instead:
```
<Field
  name="myDropdownName"
  component={MyDropdown}
  source={mySource}
  label="Make a selection"
  onBlur={() => console.log('bug squashed!')} // I'm the important line
/>
```

**Comment by firaskrichi** [comment]
Awesome! onBlur={null} worked for me. 

Thanks!!
