### ISSUE TITLE
Your reduxForm hide static react class properties.

### ISSUE THREAD

**Issue by ideal-life-generator** [erikras/redux-form#2230]
The problem is when I use your decorator, it don't copy static properties from original component. Redux decorator for example don't do that, so you have not right architecture.
Here is [screenshots](https://photos.google.com/share/AF1QipOoGmfv8MbfAXc9q0qThjXXIpyU65BkeYW1Ycg0L_aU0y-EyI9OIIxAim0pzst6vA?key=WUlELVFOVkpTYkpEb0VXdXQtSzJ1cVRJRkZUREpB). I think is clear.

**Comment by huan086** [comment]
Most likely related to https://github.com/erikras/redux-form/issues/2237

**Comment by likerRr** [comment]
@ideal-life-generator is right. Component's static members after processing by `reduxForm` are disappeared. And I think there is a huge issue. 
@erikras , please, pay attention.

**Comment by Sparragus** [comment]
I'm also in need of this. 

Here's an example: https://github.com/react-community/react-navigation/issues/332#event-961713900.

Because `reduxForm` is stripping the statics, `react-navigation` can't read `Component.navigationOptions`.

https://github.com/react-community/react-navigation/issues/332#event-961713900 is also in need of this feature.

What needs to be done to hoist statics?

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).

**Comment by erikras** [comment]
Published fix in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).
