### ISSUE TITLE
get Field value from componentWillUnmount

### ISSUE THREAD

**Issue by srajchevski** [erikras/redux-form#2243]
I need to get my Fields values from my form, not onSubmit, but from the componentWillUnmount method.
Field:

```js
<Field name="email" ref="email" type="email" component={renderField}/>
```

renderField component:

```js
const renderField = ({input, ref, placeholder, type, meta: { touched, error, warning }) =>  (
	<div>
		<input type={type} ref={ref} {...input} />
		{touched && ((error && <span>{error}</span>) || (warning && <span>{warning}</span>))}
	</div>
)
```

As you can see i tried setting the ref and then accessing it like this.refs.email, but this doesnt even set the ref. Any help/advice how to get around this? Thanks

**Comment by gustavohenke** [comment]
`ref` is a prop managed by React. So you would be getting a ref to the `Field` instance.
Also, I'm afraid that if the Field is contained in a functional component, you will get no refs when using a string, because they have no instance to bind to `this.refs`.

You can, however, use the [`formValueSelector`](http://redux-form.com/6.5.0/docs/api/FormValueSelector.md/) and have the form values always bound to a prop.
