### ISSUE TITLE
Validate function called twice with undefined params before render

### ISSUE THREAD

**Issue by mattkrick** [erikras/redux-form#228]
Just a small thing, but I noticed my sync validation function is getting hit twice before startup & is being sent an undefined value. I'm betting it doesn't need to be hit at all because even if the default data were invalid, it probably wouldn't show up since the field isn't touched yet. But, I suppose if it were passed the correct field val it'd be worthwhile to run it once (eg profile page that shows errors regardless of touch status). Thoughts?

```
First stack trace
validate (EditableContainer.js?3614:8)
readFields (readFields.js?5179:60)
ReduxForm(EditableContainer) (createHigherOrd…nt.js?14f6:135)
```

```
Second stack trace
validate (EditableContainer.js?3614:8)
readFields (readFields.js?5179:60)
componentWillReceiveProps (createHigherOrd…nt.js?14f6:152)
```

**Comment by erikras** [comment]
My thoughts are that it shouldn't matter much. As you surmised, the point of the touched flags are so that it's completely optional whether or not you show errors all the time or only when a field has been touched. If your sync validation function is inefficient, you should [memoize](https://github.com/erikras/lru-memoize) it.
