### ISSUE TITLE
Form not initializing when store is updated by a dispatch call

### ISSUE THREAD

**Issue by SepiaGroup** [erikras/redux-form#2316]
I have a form that i am initializing the fields from a dispatch call to my server. however, the form initializes before the values are returned from the server and never updates. i make a call to getUser() within componentWillMount().  i see the values i want in the store after the call to the server is completed but the form does not re-initialize. is an expected behavior? is there a way to tell the form to update the initial values? 

```
const mapStateToProps = (state) => {
    return {
        initialValues: state.user
    };
};

const mapDispatchToProps = (dispatch) => {
    return {
        getUser: () => {return dispatch(actions.getUser()); }
    }
};

export default connect(mapStateToProps, mapDispatchToProps)(AccountSettings);
```

**Comment by timurcatakli** [comment]
I am having the exact same problem. I am loading initial values but I need to make value changes to the form in order to submit it and pass the validation.

Also take a look at this example: http://redux-form.com/6.3.1/examples/initializeFromState/
After clicking on LOAD, you still can not submit the form unless you make a value change.

Anyone can shed a light on this?

Thanks

**Comment by SepiaGroup** [comment]
@timurcatakli the reason you cannot press submit until a value changes is because the form is "pristine"  http://redux-form.com/6.3.1/docs/api/Props.md/

i think i have a solution to my issue - i will call initialize when my action to get the data returns. if this does not work well for a good user experience, i will change the user workflow to make sure the data is in the store before the they see the form.

**Comment by timurcatakli** [comment]
Thanks :-)
