### ISSUE TITLE
How to disable the checkboxes 

### ISSUE THREAD

**Issue by bairisuresh** [erikras/redux-form#2328]
I have couple of checkboxes in redux-form.  When I select one check box I need to disable few checkboxes.. 
Any sample code is helpful....
I have tried in different ways but not working properly..

**Comment by bairisuresh** [comment]
Plz give sample code

**Comment by bairisuresh** [comment]
Plz provide  me sample  code...

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.

This is because StackOverflow is better at keeping popular questions visible.
The GitHub issue tracker is more suited for discussions related to bugs and improvements of Redux Form.

Thanks for using Redux Form!
