### ISSUE TITLE
Redux-from Widgets

### ISSUE THREAD

**Issue by bairisuresh** [erikras/redux-form#2340]
How to disable the other widget option on selecting one option.

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because StackOverflow is better at keeping popular questions visible.
The GitHub issue tracker is more suited for discussions related to bugs and improvements of Redux Form.

Thanks for using Redux Form!
