### ISSUE TITLE
Upgrade old v5 to react-redux v5 due to redux-autoform

### ISSUE THREAD

**Issue by vedrani** [erikras/redux-form#2347]
Redux-autoform library doesn't yet support redux-form v6, probably because difficulties to migrate due to big changes between v5 and v6. Until redux-autoform migrate to v6, is it ok to upgrade redux-form v5 to react-redux v5.0.0. I can make PR, and we can easily release 5.3.4 or 5.4.0.

**Comment by gustavohenke** [comment]
And what's your issue?

**Comment by vedrani** [comment]
I'm using redux-autoform that depends on redux-form v5. Redux-autoform moved to react-redux v5.0.0, while redux-form v5 is on react-redux v4. React-redux released major version, meaning redux-form will have unmet dependency.

**Comment by gustavohenke** [comment]
redux-form v5 is no longer supported.
Unfortunately, our team is very small, so that we can't keep releasing patches for old versions.

I saw somewhere else that the APIs of react-redux v4 and v5 are compatible (our `package.json` even allows you to use either versions). So perhaps you could ask at redux-autoform to keep both versions, if that's even possible.

I'm sorry for that.

**Comment by vedrani** [comment]
You are right, they are compatible, but npm semver doesn't see it like that because of the major version change. We only need to change a line in the link below to ^5.0.1 and you need to release a patch for v.5.3.3. It's a trivial task, there is no need to change any code.

Please check your version v5.3.3 package.json
https://github.com/erikras/redux-form/blob/v5.3.3/package.json#L90

**Comment by gustavohenke** [comment]
As usual, you can send a PR for this.
Code changes are @erikras's decisions, not mine.

**Comment by vedrani** [comment]
It's already changed here in v5 branch, you only need to publish 5.3.4. Thanks in advance.
https://github.com/erikras/redux-form/blob/v5/package.json#L98
