### ISSUE TITLE
Field will not bind

### ISSUE THREAD

**Issue by mweels** [erikras/redux-form#2373]
Can someone please help me with why the field is not binding?

 {formData.description} shows up fine, but the textbox does not have a value.

Everything else works fine.

Thank you in advance.

Regards,
Marty

```js
import React, { Component, PropTypes } from 'react'
import { connect } from 'react-redux'
import { requestLocation, fetchLocation } from '../actions'
import Picker from '../components/Picker'
import Posts from '../components/Posts'
import { Link } from 'react-router'
import Select from 'react-select';
import 'react-select/dist/react-select.css';
import { Field, reduxForm } from 'redux-form';

import { Form, FormGroup, ControlLabel, FormControl, HelpBlock } from 'react-bootstrap';





class App extends Component {
  static propTypes = {

  }

  componentDidMount() {
    const dispatch = this.props.dispatch;
    const id = this.props.params.id;
    console.log("Mounting fetchning..");
    dispatch(fetchLocation(Number(id)))

    console.log("Mounting fetchned..");
  }

  componentWillReceiveProps(nextProps) {

    if (this.props.params != nextProps.params) {
      this.props.dispatch(fetchLocation(Number(nextProps.routeParams.id)))
    }
  }


  render() {

    const id = this.props.params.id
    const formData = this.props.location;
    const error = this.props.error;
    const states = this.props.states;
    const handleSubmit = this.handleSubmit;

    return (
      <div>

        Location {id}<br/>
        <br/>
        {formData.description}

                 <Field name="formData.description" component='input' type="text" placeholder="Description"/>


      </div>
    )
  }
}

const mapStateToProps = state => {
  return {
    location: state.locations.aLocation
  };
}


// Decorate the form component
App = reduxForm({
  form: 'contact'
})(App);


export default connect(mapStateToProps)(App)
```

**Comment by gustavohenke** [comment]
You need to use `initialValues` prop.
For example, in your `mapStateToProps` function, include a key `initialValues` in your returned object with the value `{ formData: { description: 'blabla' } }`, and it'll work *like magic*.

Please note that this issue doesn't belong to our GitHub issue tracker, so in the future we request you to [ask at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.

This is because StackOverflow is better at keeping popular questions visible.
The GitHub issue tracker is more suited for discussions related to bugs and improvements of Redux Form.

Thanks for using Redux Form!

**Comment by mweels** [comment]
Thank you, that still didnt work.

Ill try over there.  

Thank you again.

**Comment by mweels** [comment]
I found the issue.

enableReinitialize: true needed to be set.

http://stackoverflow.com/questions/38881324/redux-form-initialvalues-not-updating-with-state
