### ISSUE TITLE
mapStateToProps ownProps undefined

### ISSUE THREAD

**Issue by jesperu** [erikras/redux-form#238]
I'm using the new "all in one"-connect (Great work by the way!)

I don't get ownProps passed to mapStateToProps. It's undefined.

Debugger printout:
mapStateToProps(globalState, ownProps) globalState = Object {auth: Object, products: Object, productTypes: Object, fields: Object, counter: 0…}, ownProps = undefined

**Comment by erikras** [comment]
Oops. I've never used that parameter so I missed it. Fixed in v3.0.3.

Thanks for pointing this out.

**Comment by jesperu** [comment]
Thank you! That was fast.

**Comment by gaearon** [comment]
No no no, don't do this, this is very inefficient: https://github.com/erikras/redux-form/commit/a62f9fdb5f566b943a62a574fb09a1a05084f8c0.

React Redux will now rebind the action creators on *every* prop change.
Previously it only did that once because you passed a function with single argument.

React Redux [looks at the functions you pass to `connect`](https://github.com/rackt/react-redux/blob/c2acf955b8fb33dac3bc45dd35a2ce3e226b9dfd/src/components/connect.js#L31-L32). If they accept two arguments (and have `ownProps`), it enters “slow mode”. If they accept just one argument, it works in “fast mode”.

To stay fast, your library needs to do the same thing. If `mapDispatchToProps` and `mapStateToProps` accept a single argument, pass a single-argument function to `connect()`. Otherwise, and only then, pass a function with two arguments.

I know it's a bit implicit, but then it's a bit unusual to have libraries wrapping React Redux and mimicking its API, so that's why it isn't thought out.

**Comment by jesperu** [comment]
Ok, if we don't get ownProps how do we get to our url parameters in mapStateToProps?

**Comment by gaearon** [comment]
I'm not saying Redux Form shouldn't pass `ownProps`. I'm saying it should pass `ownProps` *only* if the `mapStateToProps`/`mapDispatchToProps` specified by the user have `.length > 1`. This an implementation detail to speed it up: I'm not proposing an API change.

**Comment by abachuk** [comment]
Is there an example how to use connect and reduxForm? Should I be using wrapMapStateToProps instead? I'm trying to access values outside of the form, like auth state and pass auth value to the formSubmitHandler. Thank you!!

**Comment by lbayeva** [comment]
I'm getting the same issue now in redux-form v6.6.3 - ownProps is undefined.
