### ISSUE TITLE
Redux Form always validates even on a normal button press

### ISSUE THREAD

**Issue by srinipatil02** [erikras/redux-form#2424]
I have a redux form with a submit button and a normal html button. I dont want the form to be validated when the normal button is pressed. But looks like the form is always validated once and then when I click the button again the onclick on the button is executed. How do I prevent this? 

I replicated the same issue with same form. For example if you go to http://redux-form.com/6.4.3/examples/syncValidation/ ,enter 4 in the age field and click on clear values. First tiem the validation triggers and the second time the button action works.

**Comment by andynoelker** [comment]
I assume you opened the identical stackoverflow post, so I'll just copy my answer here in case you see this instead: http://stackoverflow.com/questions/41590766/redux-form-always-validates-even-on-a-normal-button-press

The example you link to has that behavior because by default Redux Form will call the validation function for touched Fields on a blur event. The fact that you are clicking a button is irrelevant - you could click on any element or anywhere on the page and you would get that behavior.

The only real way to stop this behavior is to stop Redux Form from touching your Fields on a blur event. You can do this by setting `touchOnBlur` to `false` in the Redux Form config object.

```
export default reduxForm({ form: 'myForm', touchOnBlur: false })(MyForm);
```

**Comment by gustavohenke** [comment]
To stop repeated discussion, I'll close here.
This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
