### ISSUE TITLE
Incorrect initializeFromState example

### ISSUE THREAD

**Issue by aray12** [erikras/redux-form#2435]
I was following this example: http://redux-form.com/6.4.3/examples/initializeFromState/ but my `initialValue` were not populating properly if the source of them were populated after the initial render. It seems like it should based on the example, since the reducer isn't being loaded until `load(data)` is being called and it works.

I realized I needed to add `reduxForm({ form: 'someForm', enableReinitialize: true })(Comp)...` to get it to work.

The example seems to work. Is this correct behavior...?

**Comment by gustavohenke** [comment]
It does work because there were no `initialValues` prior to clicking the "Load account" button.

If you do specify something to `initialValues`, then try to change it somehow, it won't work without `enableReinitialize` set to `true`.

In this example, try clicking the load button, then edit something, and click the load button again. Nothing happens.

**Comment by aray12** [comment]
@gustavohenke so I have set my reducer with default values that are sometimes not `undefined` or `null` (empty strings in this case). Would that be why it didn't work?
