### ISSUE TITLE
Passing argument to the Field validation?

### ISSUE THREAD

**Issue by nealoke** [erikras/redux-form#2453]
I am wondering if you could pass arguments to the Field level validation like so:

```
<Field name="username" type="text"
	component={renderField} label="Username"
	validate={[ required('an argument to this function'), maxLength15 ]}
/>

// The validator
const required = (value, message = 'This is required') => value ? undefined : message;
```

This would make it easy to customize messages based on the field, without needing to create a validation function which will repeat a lot of code just to have a suiting message.

**Comment by niksajanjic** [comment]
Currently you can't, but why don't you make a function that returns function which validate expects like this:

```
const isRequired = message =>
  value => value ? undefined : message;

<Field
  validate={[isRequired('an argument to this function')]}
/>
```

**Comment by niksajanjic** [comment]
Same goes for maxLengths too, so if you wanna use them both:

```
const isRequired = message =>
  value => value ? undefined : message;

const maxLength = length =>
  value => value <= 15 ? undefined : `max length is ${length}`

<Field
  validate={[isRequired('an argument to this function'), maxLength(15)]}
/>
```

**Comment by nealoke** [comment]
@niksajanjic I'm not sure how this works, how come you can still capture the value of the field? Is this automatically done by RF?

**Comment by niksajanjic** [comment]
If you take a look at the documentation here:
http://redux-form.com/6.4.3/examples/fieldLevelValidation/

You can see that when you pass required function to your validate prop on Field component, you can see that this function will receive value as first parameter.

In our case we are immediately calling isRequired function and passing it message parameter and this function returns another function. The function that gets returned is the same function as in the tutorial, because that is what validate prop expects. It expects function to which it will pass value as first parameter.

So, if you want your validate function to have some custom parameters passed to it, you wrap it in another function and pass those custom variables as this functions parameters. Also, make sure that function returns the function which validate expects.

**Comment by gustavohenke** [comment]
I will say no to this. Factory functions outside of your render method are enough.

**Comment by szerintedmi** [comment]
If anyone trying to use a validator with a parameter, here is a workaround I've found. Not sure if there is a better way but it seems to work.

```
const Validations = {
  minAmount: minValue => value => {
    return parseFloat(value) < minValue
      ? "Amount must be at least " + minValue : undefined;
  }
};

```
in component constructor:

```
constructor(props) {
  super(props);
  this.minAmount = Validations.minAmount(
    this.props.minAmount
  ); 
}
```

then in Field:

```
<Field  validate={this.minAmount} ....
```

**Comment by aniruddhashevle** [comment]
According to @erikras 

`<Field validate={[isRequired('an argument to this function'), maxLength(15)]}/> `
is not a proper way.

But,

what about

```
const validate = values => {
  const errors = {}
  /* common maxLength function */
  if(!maxLength(values.username, 20)) {
    error.username = 'Username should not be greater than 20 characters';
  }
  return errors
}

export default reduxForm({
  'form': 'UserLogin',
  validate
}, mapStateToProps)(UserLogin);

```

## is it a proper way?

**Comment by niksajanjic** [comment]
@nvh95 Because value will be `undefined` when input is empty, so your code would break on `value.length`.

**Comment by nealoke** [comment]
I found a good library which helps a lot for reusability and customizability namely [redux-form-validators](https://github.com/gtournie/redux-form-validators)

**Comment by aniruddhashevle** [comment]
I've found the solution for this...

```
let validationObj = {
    required: true,
    type: 'number'
}

<Field
    name='first_name'
    type='text'
    className="input form-flow"
    component={RenderTextField}
    placeholder={field.label}
    validate={[
         (value, allValues, props, name) => {
               let errors = dynamicValidator(value, validationObj);
               return errors;
          }
    ]}
/>
```

```
dynamicValidator = (value, validationObj) => {
    //required validation
    if (validationObj.required === true) {
      if (!value) {
        return 'Required'; //Error msg
      }
    }

    //number validation
    if (validationObj.type === 'number') {
      if (isNaN(Number(value))) {
        return 'Must be a number'; //Error msg
      }
    }

     /* And so on... */
   
}
```

The above implementation shows me the error msg properly for the respective field.

@erikras : Please let me know your thoughts on this.

**Comment by carlos0202** [comment]
is there any way to access field props while validating? Because if i have access to the props of the field that i am validating i can construct better validation functions using the metadata available for the field component to validate. For instance, i need to write a validation function to compare 1 of my field values with another field in the same form, but i found no way to do this with the way that the validation works right now. Any help is highly appreciated.

**Comment by aniruddhashevle** [comment]
@carlos0202 : In validate prop of the Field, there is **allValues** parameter, which will help you to get **all values of that respective form** in the validate function.
Please check this out: https://redux-form.com/7.2.3/docs/api/field.md/#-code-validate-value-allvalues-props-name-gt-error-code-optional-

**Comment by carlos0202** [comment]
@aniruddhashevle the problem is that having only the value is not enough when you have forms with a lot of complex validations. I'm migrating a huge project that rellies on dynamic forms with dynamic rules expressed in json format: compare, remote, masked input, and so on. And i need full control and as much info as i can while validating my form at field level and at form level when the time of submitting the form arrives.
