### ISSUE TITLE
Problem of initialValues when using immutable.js

### ISSUE THREAD

**Issue by ruanyl** [erikras/redux-form#2462]
redux-form uses `fromJS(initialValues)` to deeply convert plan javascript object to immutable object. In my case, I have `initialValues` like this:

```
const friends = selector(state); // get friends from redux state, this will be a `List` of plain objects

initialValues: {
  name: 'Javier',
  friends
}
```

What I expected when I use the `friends` List in the component is a List of plain Object, but instead I get a List of Map.

My option here is: what we got by selector, isn't it what the component expected to receive? `redux-form` should not change the value that passed to the component. Otherwise, I will have to first do `toJS()` in the component in order to use the `input.value`.

**Comment by nktssh** [comment]
You can make this by your own using this:
```
const friends = new Immutable.List([{a: 1}, { b: 2, }]); // getting List of objects

initialValues: new Immutable.Map{
  name: 'Javier',
  friends
}
```
All methods of Immutable.js and in particular`fromJS` will converting values which is already immutable, and will no iterate through them.

People usually have two options: 1) all values is in Immutable.js structures and 2) all values is just plain JS object. Your option is something in the middle.
Consider to use one of aforementioned options - it will simplify your life since you will know what type your data is 😉

**Comment by ruanyl** [comment]
@nktssh Thanks 👍  That solves my problem. I already did what you said :)

My doubt here is: should `redux-form` change the value which the component expect to get? should it just use `new Map(initialValues)` instead of `fromJS((initialValues))`?

I agree with you about your aforementioned options, ideally, the app state should like what you said. But I think `redux-form` should at least not change the value silently, or it's not the responsibility of `redux-form` to enforce the user to do something.

Thanks anyway, I will close the issue as my problem has solved.
