### ISSUE TITLE
Validation for text area

### ISSUE THREAD

**Issue by ShashankJoshi007** [erikras/redux-form#2471]
Hi, 

How to do validation for textarea ? 

Please mention renderField part also. 

Thanks much,
Shashank

**Comment by gustavohenke** [comment]
Just use the same code you would for normal validation.

In the future, for stuff like this, please [ask at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!

**Comment by ShashankJoshi007** [comment]
Thanks gustavohenke. But in renderField , what I need to mention to get textarea ? with the below code it is not rendering the textarea: 

```
const renderField = ({ input, label, type, meta: { touched, error, warning } }) => (
  <div>
    <label>{label}</label>
    <div>
      <input {...input} placeholder={label} type={type}/>
      {touched && ((error && <span>{error}</span>) || (warning && <span>{warning}</span>))}
    </div>
  </div>
)
```

**Comment by gustavohenke** [comment]
So, in regular HTML, you would use a `<textarea>` tag instead of a `<input>`. Do the same for your custom React component.
