### ISSUE TITLE
how to set/update a custom state (progressbar for uploading form)

### ISSUE THREAD

**Issue by houfeng0923** [erikras/redux-form#2488]
i has a progressbar(show the progress like 45%) for upload file form . now i create a new state  in global scope . 
has a way to add custom state in `form.x` ？

**Comment by danielrob** [comment]
You can take a look at the docs on the [reducerPlugin](http://redux-form.com/7.0.3/docs/api/ReducerPlugin.md/). 

While we often leave support requests like this open for a time, this tracker is primarily for bugs and feature requests (including docs enhancement requests) as stated in the template. Stack overflow is better suited for questions like these, but you can post issues here with a Stack Overflow link as desired. I'll go ahead and close due to inactivity, but feel free to update/clarify.
