### ISSUE TITLE
Previous button in a wizard - Validation problem

### ISSUE THREAD

**Issue by GautierT** [erikras/redux-form#2505]
Hi !
I have a multi "page" form.
My parent form is initialize like this : 
```
Parents = reduxForm({
    form: 'my-form',
    enableReinitialize: true,
    destroyOnUnmount: false,
})(Parents);
```
And multiple component/page displayed conditionaly like this : 
```
{(step === 1) && <Intro onSubmit={this.handleSubmit} loading={submitting}/>}
{(step === 2) && <Motifs onSubmit={this.handleSubmit} onSubmitFail={this.handleSubmitFail} loading={submitting}/>}
{(step === 3) && <Fichiers onSubmit={this.handleSubmit} onSubmitFail={this.handleSubmitFail} loading={submitting}/>}
{(step === 4) && <Confirmation onSubmit={this.handleSubmit} onSubmitFail={this.handleSubmitFail} loading={submitting}/>}
{(step === 5) && <Terminee onSubmit={this.handleSubmit} onSubmitFail={this.handleSubmitFail} loading={submitting}/>}
```

`this.handleSubmit` is a function that call `this.props.handleSubmit()` and add or remove `1` to step if the server respond http 200.

On the components `<Motifs>` for example i initialize redux-form like this : 
``` 
Motifs = reduxForm({
    form: 'my-form',
    destroyOnUnmount: false,
    validate: validateMotifs // validation function
})(Motifs);
```
And for each of my form components/pages i have some button to previous/next like this : 
`<NavFormButton loading={loading} handleSubmit={handleSubmit} onSubmit={onSubmit}/>`

When i click next i want to validate and submit the form. It's working.
But when i go previous i just want to submit the data so they are saved but don't want to validate because the user may have not fill all the fields.

How should i do ? Am i following the good path ?

Having a lot of trouble to understand how to do this correctly ... Thanks.

**Comment by gustavohenke** [comment]
If all you want to just go back while not losing your current state, there's no need to do anything,
the Redux store will take care of this for you.
If you want however to submit to the server, I suggest you to implement `shouldValidate`/`shouldAsyncValidate`. Check [here](http://redux-form.com/6.4.3/docs/api/ReduxForm.md/) for docs on this.

Since this is a usage question, I'll close it.
In the future, we request you to [ask at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!

**Comment by GautierT** [comment]
Thanks @gustavohenke ! 
I played all morning with `shouldValidate` but i can't find a way to catch a parameter that i would like to pass to handleSubmit so that i can true/false the shouldValidate. I opened a new issue here #2510.

**Comment by GautierT** [comment]
@gustavohenke : i finally gets through the shouldValidate.
But if one of the field is already in error state if i return false in the shouldValidate it's stay in error and dont go through the onSubmit...

**Comment by gustavohenke** [comment]
Instead of using `shouldValidate`, you can also use the `validate` function itself.
For example, when you click to go back, you can check whether you're going back and then just return an empty errors object, `{}`, so no errors will stay in your way.

**Comment by GautierT** [comment]
Ok but how can i pass different parameters to my validate function ?
```
Motifs = reduxForm({
    form: 'my-form',
    destroyOnUnmount: false,
    validate: validateMotifs,
    onSubmitFail : handleSubmitFail
})(Motifs);
```

**Comment by GautierT** [comment]
And why shouldValidate is called multiple time in a row ?

**Comment by gustavohenke** [comment]
Hey, sorry for the delay here.
Something cool about redux form is that you can pass configuration as props, so you could do something like this:

```js
const MyPage = props => {
  const validate = values => {
    // your validation logic which may use props!
    return errors;
  };

  return <MyForm validate={validate} />;
};
```

About `shouldValidate` - is it being called too much? In [this simple example](http://www.webpackbin.com/EkicAEy_z), it's called 2 times at the beginning, then on focusing, on typing and on blurring.
