### ISSUE TITLE
normalizer configuration

### ISSUE THREAD

**Issue by iamdustan** [erikras/redux-form#251]
Without looking at the implemenation details, it would be much preferred to put the normalizer definition with the `reduxForm` definition rather than at the middleware creation level.

On a project with 20+ forms throughout it can get a bit hairy to have the normalization definition so divorced from the form definition.

**Comment by erikras** [comment]
I agree that it's awkward, but the reducer and component are really separate concerns. https://github.com/erikras/redux-form/issues/134#issuecomment-148644828

> Excellent point about the dichotomy, but it really is necessary, as there are two parts to redux-form, the component and the reducer, and they are each in charge of validation and normalization respectively. I suppose that the component could normalize in the onChange function, but it really is a superior design for the reducer to be in full control over its data, just receiving actions and modifying state.

**Comment by iamdustan** [comment]
Could the normalization be integrated a bit tighter in the same way that errors are. E.g. from the component I declare normalized fields?

Sharing phone or email normalization is likely common and would still likely trim down many real-world implementations of the normalize call to be data types rather than form types.

**Comment by erikras** [comment]
I'm not sure I follow you. Normalizing functions that are even a little bit complex can, and should, be kept as reusable and testable modules, like they are in [the example](http://erikras.github.io/redux-form/#/examples/normalizing).

**Comment by iamdustan** [comment]
code probably can explain it better. Rather than `formReducer.normalize()` using form names for keys, it uses possible field names or types as keys:

```
import {reducer as formReducer} from 'redux-form';

export const formReducer.normalize({
  email: emailFieldNormalizer,
  phone: emailFieldNormalizer,
});
```


```
import {reduxForm} from 'redux-form';

export default reduxForm({
  name: 'example',
  fields: ['name', 'email', 'phone'],
  // match field key to normalize key
  normalize: ['email', 'phone'],

  // match object key === field key to object value === normalize key
  normalize: { email: 'email', primaryPhone: 'phone'},
})(MyForm);

export const formReducer.normalize({
  email: emailFieldNormalizer,
  phone: emailFieldNormalizer,
});
```

**Comment by erikras** [comment]
I'm still confused. What is `primaryPhone`? Why is `phone` using `emailFieldNormalizer`? Why are there two `normalize` keys in the config passed to `reduxForm()`?

**Comment by iamdustan** [comment]
erp. Writing code in the github issue editor makes me extra sloppy. I updated the code example. The two normalize keys in the reduxForm were to demonstrate two different APIs. One more restrictive and the other more flexible.

**Comment by erikras** [comment]
Okay, your message has successfully been communicated.

The problem with this is that, as I said in my first comment, it's the _reducer_ that needs to know what rule to apply to what value. Putting that mapping on the component doesn't help at all.

**Comment by iamdustan** [comment]
Does that not communicate to the reducer what it needs to know in the same way that the fields key communicates to the reducer what properties an instance should have? I suppose I don’t understand why doing this at the form name level accomplished the reducer knowing everything it needs versus at the field level.

**Comment by erikras** [comment]
The reducer doesn't know about the fields.

**Comment by bmueller-sykes** [comment]
I'd like to chime in here and say that I agree with iamdustan on this one. As far as implementation details go, I don't really care where the normalize routines get fired, but as far as code organization and sanity go, forcing users to put all normalizing code with the store configuration is really awkward. I've been working with redux-form for only a few days now (still learning the ropes), and I'm 99% sure that when I'm reviewing my code, if the normalizing code is not organized with the rest of the form code, I will forget that it's there (or even worse, if I'm reviewing somebody else's code, I'll have even less of a chance of remembering to look there).  

iamdustan's suggestion of grouping that normalizing code with the rest of the form code seems like exactly the right thing--if the right thing as far as when it *fires* is for it to happen at the reducer, then that makes complete sense.  I have no idea, however, if it's technically feasible to have the normalize code grouped with the form code, yet have it fire at the reducer.

**Comment by Morriz** [comment]
I agree. There is much to be gained by the proposition.

**Comment by Danita** [comment]
I'm new to redux-form and so far I'm loving the flexibility it provides, but I also agree that it would be so much more developer friendly to have the form configuration in a single place.

**Comment by xml** [comment]
So, I guess the question is: taking it for granted that the reducer shouldn't know about the fields or anything else from the calling domain... should it know about normalizers, either? Does it make sense to perform data transformation in a reducer? (While it's technically not a 'side-effect', it does seem to cross the streams, separation-of-concerns-wise...) 

Or, would both the reducer itself and the API signature for redux-form be cleaner and clearer if normalization happened in a pipeline prior to `dispatch()`?

**Comment by Morriz** [comment]
I second that suggestion. Pre-dispatch is preferred, as it's raw input. As such it does not need to be part of redux, and one can choose from the many plugins out there

**Comment by erikras** [comment]
I can see it from many different sides.

1. **Normalize in reducer** - If you had two different form components that were editing the same data, would you really want to put the normalizing code in both components? No, it's the reducer's job to accept change events and store the data canonically.

2. **Normalize in middleware** - Similar to normalizing in the reducer, but more abstract...and potentially reusable?

3. **Normalize in form component** - Closer to where you are thinking about the presentation and editing of the data. The reducer just stores, it doesn't _think_ or do anything intelligently with the data dispatched.

Like most engineering problems, there are tradeoffs with each option. Due to the decoupling of fields from the form component in the major rewrite next version (`v6`), I think the library will be moving from Option 1 to 3, giving the normalizing responsibility to the field itself.

**Comment by bmueller-sykes** [comment]
Sounds great!


On Apr 11, 2016, at 8:30 AM, Erik Rasmussen <notifications@github.com<mailto:notifications@github.com>> wrote:


I can see it from many different sides.

  1.  Normalize in reducer - If you had two different form components that were editing the same data, would you really want to put the normalizing code in both components? No, it's the reducer's job to accept change events and store the data canonically.

  2.  Normalize in middleware - Similar to normalizing in the reducer, but more abstract...and potentially reusable?

  3.  Normalize in form component - Closer to where you are thinking about the presentation and editing of the data. The reducer just stores, it doesn't think or do anything intelligently with the data dispatched.

Like most engineering problems, there are tradeoffs with each option. Due to the decoupling of fields from the form component in the major rewrite next version (v6), I think the library will be moving from Option 1 to 3, giving the normalizing responsibility to the field itself.

**Comment by jsheetzati** [comment]
Option 3 sounds great and more intuitive!

**Comment by jeromebridge** [comment]
Is there any way to use the normalizers without requiring the exact field name be in the reducer?
