### ISSUE TITLE
how to achieve subling form components communication 

### ISSUE THREAD

**Issue by iiitmahesh** [erikras/redux-form#2522]
how to achieve subling form components communication ??

I have 3 different components in a contianer. every child as some input feilds . one componets values should update other componets values.

How to implement commucation between different components??

![screenshot from 2017-01-28 01-30-04](https://cloud.githubusercontent.com/assets/13597781/22386183/f9196ac8-e4fb-11e6-8e5e-828f93571e06.png)

**Comment by gustavohenke** [comment]
Use `formValueSelector` together with `connect()` from react-redux.

In the future, [ask usage questions at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here (if you're not getting answers).
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
