### ISSUE TITLE
Question: Best practice/example with database?

### ISSUE THREAD

**Issue by Steviey** [erikras/redux-form#2550]
Hello, I'm new to Redux-Form and have a question.

I plan a react-native app which should store business logic-and session data in a local Sqlite3-db.

Is Redux-Form ready for use with a local db? I saw some videos, but I'm still not sure. 
Are there any best practices and or examples available, related to local db usage?
Thank you in advance!

PS: With the evolution of the react-native landscape, I hope to be able to port related code to desktop apps, incl. react-navigation, its internal router, redux, redux-form and database - in the future (code once).

I thank you all.

**Comment by gustavohenke** [comment]
Hi!
If Redux Form is ready for local DB? Probably. All it needs is a Redux store and some React components.

I never used React Native, so I can't help you a lot, but there are folks who integrated both (with some search you may find them in the issues around here).

In the future, we request you to [ask at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
