### ISSUE TITLE
Same Form in different react components: how to wrap values in different subprops?

### ISSUE THREAD

**Issue by sun2rise** [erikras/redux-form#2570]
Hi,
i am using redux-form for a big form so I divided it into different React components. It works just great but when my onSubmit function receives the data, it does in a single big object.
What i need is to have properties grouped by an intermediate property with a custom name, maybe defined in the component where that property was born

EXAMPLE:

```js
onSubmit={(values) => console.log(values)}
```

what i got:
```js
values = {
  field1: 'value1',
  field2: 'value2',
  field3: 'value3'
};
```

what i would need:
```js
values = {
  form1: { field1: 'value1' },
  form2: { field2: 'value2' },
  form3: { field3: 'value3'}
};
```

thank you!

**Comment by gustavohenke** [comment]
It seems like `FormSection`s are exactly what you want.  
http://redux-form.com/6.5.0/docs/api/FormSection.md/

In the future, please [ask at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag.

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
