### ISSUE TITLE
Can't focus on field in redux-form

### ISSUE THREAD

**Issue by indapublic** [erikras/redux-form#2578]
```
"react": "^15.4.2",
"redux": "^3.6.0",
"react-redux": "^5.0.2",
"redux-form": "^6.4.3",
```

Need to focus on field on form show.

```
<Field ref="me" name="title" type="text" component={renderField} />
```

That tries not solved my problem :(

```
componentDidUpdate () {
    ReactDOM.findDOMNode(this.refs.me).focus()
  }
```

```
componentDidUpdate () {    
    this.nameInput.focus()
  }

<Field ref={(input) => { this.nameInput = input; }} name="title" type="text" component={renderField} />
```

```
<Field autoFocus={true} ref={(input) => { this.nameInput = input; }} name="title" type="text" component={renderField} />
```

Where I'm was wrong? Thank you

**Comment by gustavohenke** [comment]
Use `autoFocus` prop. It's the equivalent to HTML5's `autofocus` attribute.

**Comment by gustavohenke** [comment]
The issue template would have helped to determine what your issue is.
I spent a lot more time understanding your problem without it.

Second, questions don't fit well in the GitHub issue tracker. They are, however, a good fit for StackOverflow.
This was also specified in deleted issue template.

Finally, `autoFocus` should suffice, but `renderField` is probably not passing it to the underlying `input`.
And when you use `ref` in a `Field`, you're getting the ref for the `Field` instance; you should also make use of [`withRef` prop](http://redux-form.com/6.5.0/docs/api/Field.md/#-withref-boolean-optional-).
