### ISSUE TITLE
Validation is triggered twice on form init

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/redux-form#2583]
### Are you submitting a **bug report** or a **feature request**?
Bug ?

### What is the current / expected behavior?
In `Synchronous Validation Example` validate function is trigged twice, before form is mounted and after it's rendered.

Since nothing was changed in the form, why do we need to trigger it twice, is it by design?

### What's your environment?
Redux form 6.5.0

**Comment by erikras** [comment]
This _is_ a bug, but it's a pretty minor one. It is running the validation first when the form will mount, and then It is rerunning the validation after the fields have registered, **regardless of whether or not the fields have field-level validators**. I will fix it so that it will only rerun the validation if new field-level validators are introduced by the field registration.

**Comment by VladShcherbin** [comment]
@erikras wow, that was fast. Thank you 👍

**Comment by erikras** [comment]
Fix published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).
