### ISSUE TITLE
Dynamically changed validation prop

### ISSUE THREAD

**Issue by alvelig** [erikras/redux-form#2588]
### Are you submitting a **bug report** or a **feature request**?

Bug?

### What is the current behavior?

If you dynamically change validation prop or render Field without validation prop with name of the field that had this prop before, the validation still remains.
```
{
    	check === 'yes' ?
          <Field name='lastName' type='text' 
          component={renderField}
          validate={[required]}/> :
              <div><Field name='lastName' type='text' 
          component={renderField} />No validation</div>
    }
```

https://jsfiddle.net/e8osasy2/4/
In the example: 
1. Touch "Last" field (validation error will appear)
2. Change "yes" to any other value

### What is the expected behavior?
validation error should go away as soon as validation prop is changed

### What's your environment?

6.5.0

**Comment by mqklin** [comment]
As workaround:

```
<Field
  name='lastName'
  type='text' 
  component={renderField}
  validate={check === 'yes' ? required : null} // buy the way, why you wrap `required` into brackets? validate should be function, not array
  showError={check === 'yes'}
/>
```

```
const renderField = ({ input, type, meta: { touched, error }, showError }) => {
  return (
    <div>
      <div>
        <input {...input} type={type}/>
        {touched && error && showError && <span>{error}</span>}
      </div>
    </div>
  );
}
```

Full example: https://jsfiddle.net/e8osasy2/5/

**Comment by mqklin** [comment]
I guess you shouldn't change `validate` prop. 

Instead you can move validate logic into `validate` function itself:

```
const required = (value, allValues) => {
  if (allValues.check !== 'yes') return undefined;
  return value === 'hello' ? undefined : 'Must be polite'; 
}
```

https://jsfiddle.net/e8osasy2/6/

http://redux-form.com/6.5.0/docs/api/Field.md/#-validate-value-allvalues-props-error-optional-

**Comment by alvelig** [comment]
@mqklin Good guess, thanks. As a workaround I moved all dynamic validation logic to reduxForm's validation. This one didn't occur to me.

But your idea points out the problem: validate function is not changed first time when the prop is changed. I can't find out exact condition, but generally it's reproducible. I guess it's about avoiding extra renders.

**Comment by alvelig** [comment]
@mqklin Good guess, thanks. As a workaround I moved all dynamic validation logic to reduxForm's validation. This one didn't occur to me.

But your idea points out the problem: validate function is not changed first time when the prop is changed. I can't find out exact condition, but generally it's reproducible. I guess it's about avoiding extra renders.

Look at https://jsfiddle.net/e8osasy2/7/. Just play with 'yes' and see that validate prop seems like one step back from actual render. It validates when it should not, and does not, when it should.

**Comment by mqklin** [comment]
@alvelig  Yes, I see. I don't know what the problem, but I think it's a bad practice to change `validate` prop. That's why `validate` function takes `value, allValues, props` as arguments.

**Comment by alvelig** [comment]
Anyway thank you very much. You've pointed out to me how to maintain Field-level function for dynamic conditions. I use it in more complex conditions, like one date picker's maxDate depending on another datePicker's value. I will just wrap it in a general function. I don't like reduxForm's validation approach, as it is separated from the view and code readability is affected.

Would be great if examples or/and docs explained this case, as it seems intuitive to change props dynamically in React.

**If maintainers don't find it as a bug, please, close the issue.**

**Comment by mqklin** [comment]
@alvelig just played with your last example more intensively. I think this is what happening:
1. Remove `o` letter from `First` input (now it's `hell`) and make `blur`. Validate happens and error message appears.
2. Remove `s` letter from `Validate` input (now it's `ye`). `validate` props in `First` input changes to `noop`, but **inside `Field` validate function is still `required`**, it's being called with `hell` value and returns `Must be polite` error message. So error doesn't disappear.
3. Make **any** change that causes form to rerender (for example, remove `d` letter from `Last` input, so now it's `worl`). This time `First` field has `noop` function as validate and returns `undefined`. Error message disappears. 
4. Add `s` letter back to `Validate` input. `validate` prop in `First` input changes to `required`, but **inside `Field` validate function is still `noop`**, it returns `undefined`, error message doesn't appear.
5. Repeat step 3. Error message appears because now `First` field has `required` func as validate.

So, as a result: validate function can't be called at the moment when it changes, only in the next render. Don't change validate function if you want it to be synchronous :)

**Comment by alvelig** [comment]
@mqklin Thank you very much for your investigation. I think that's an unexpected behavior. If not, let the maintainers close the ticket.

**Comment by alvelig** [comment]
As far as I can see the same behavior applies to `parse` prop... And parse does not have allValues argument.

So I believe that's a bug :'(

**Comment by danielrob** [comment]
@alvelig Thanks for your clear communication throughout this thread. We've recently had a change which you can see here: #3094 and read about here: #3211. I suspect this may have fixed or changed the nature of this issue. 

Would you be willing to verify on a recent version of redux-form after that change?

**Comment by alvelig** [comment]
I will certainly give a try to 7.0.
Can close for now as I this is by nature of 6.5.
