### ISSUE TITLE
Focus field in FieldArray after adding 

### ISSUE THREAD

**Issue by shir** [erikras/redux-form#2589]
I'm looking for away to make field focus after adding it via `FieldArray.push()` function.

Is there any callback on `FieldArray` which will be called after new item to array was added so I may get ref to new added field and make it focus? I can't find any callbacks related to FieldArray behaviour.

**Comment by gustavohenke** [comment]
No. Except for some validation-related configs and the submit function, there are no callbacks in the Redux Form API.

This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!

**Comment by shir** [comment]
@gustavohenke it's not only question, it's feature request too. That's why I put it on github. Or should I wrote "feature request" words?

**Comment by gustavohenke** [comment]
You should then have structured your OP in a way that it looked like a feature request, eg by using the issue template.

By the way, the callback you're looking for is actually built into React itself, you can implement `componentDidMount` method.
http://stackoverflow.com/a/28890330/2083599
