### ISSUE TITLE
formName not available in form component

### ISSUE THREAD

**Issue by BobWhitelock** [erikras/redux-form#259]
Firstly, thanks for this library, it's been really useful for us :). Secondly, apologies if this is no longer relevant or has since been fixed - we've not yet had the chance to upgrade from `v2.4.5`.

My issue is that I have a form component, connected using `connectReduxForm`, and as I am setting the `formName` for this component dynamically I am passing the `formName` prop into it when I use it. I also want to access the `formName` within my form component, however unlike the other props I pass into it it doesn't seem to appear in my own component - if I look in the React devtools I can see a `ReduxForm(Form)` component with `formName` prop, but my `Form` component doesn't appear to have this.

I can just get round this by passing `formName` in again with another name and using that within the component instead, however this seemed unexpected so I thought I'd check whether this was intentional/ if I'm missing something. Thanks.

**Comment by erikras** [comment]
Hmmm.. When you do upgrade to `v3`, you should know that the `formName` prop is now called `form`. And it is not passed down to your wrapped component in either version. Primarily because you _shouldn't_ need it, since it is bound to all of the actions for you. However, I guess if you really need your `Address` component to know whether it is shipping or billing, then you'll have to pass that in via some alternate prop, like `addressType` or anything else you feel like that does not collide with the `redux-form` API.

**Comment by BobWhitelock** [comment]
Thanks for your response. Our particular use case is this:

- there's a form component for editing and creating the same item, it's pretty much the same apart from this so the same component is used with the `formName` included in its props so it knows which it is;

- internally, when one field is changed we sometimes want to touch another field so it displays differently (based on other code checking whether this field is touched);

- we do this by adding an action which dispatches the `redux-form` `touch` action to the `onBlur` of the initial field;

- however the `formName` passed into the component is not available within it, and so it needs to be passed in again with a different name so it can be passed as a parameter to `touch`.

Possibly this is the wrong way to go about this. If not though, to me at least there seems no harm in passing the `formName` through to the component since:

- I would expect a prop passed to a component to be accessible within it (maybe I shouldn't expect this though);

- there's no chance of it conflicting with anything, so it's there if needed and can be ignored if not.

Thanks.

**Comment by jaroslawr** [comment]
FWIW I also have a use case for this, I would like to autogenerate HTML ids (to attach labels) for the inputs based on the input name and the form name - since Redux already collects this information, it seems pointless to manually add IDs as additional props to all the inputs.

**Comment by laem** [comment]
> Thanks for your response. Our particular use case is this:

Same use case for me.

**Comment by ooflorent** [comment]
As @erikras pointed out it is a design decision to exclude it. If you really want to pass down the form name (which is discourage), you can you the second parameter of `reduxForm`:

```js
reduxForm(
  {
    form: "myform",
    fields: ["foo", "bar"],
  },
  () => ({formName: "myform"})
)
```

**Comment by Danita** [comment]
Perhaps this use case has another solution, but I found myself needing the form name in the inputs too. I have a component that encapsulates inputs so I don't have to repeat a bunch of properties that are common to all my forms, namely i18n and help text messages. I use `react-intl` and define the string used on the fields as such:

```json
'form.account.name.label': 'Nombre de la cuenta',
'form.account.name.help': 'El nombre completo de la cuenta',
'form.account.name.error.is_required': 'Por favor ingrese un nombre para la cuenta',
'form.account.account_id.label': 'ID de la cuenta',
'form.account.account_id.help': 'El ID de la cuenta',
'form.account.account_id.error.is_required': 'Por favor ingrese un ID',
```

So then in my form instead of simple `<input>` I use something like this:

```jsx
import React from 'react';
import { injectIntl } from 'react-intl';
import {Input} from 'react-bootstrap';

const TranslatedValidatedInput = React.createClass({
	render() {
		const
			{
				intl:{formatMessage},
				formName, // This is used to disambiguate the i18n strings
				name,
				touched,
				error
			} = this.props,
			label = formatMessage({id: `form.${formName}.${name}.label`}),
			helpMsg =  formatMessage({id: `form.${formName}.${name}.help`})
			;

		return (
			<Input
				{...this.props}
				ref={name}
				label={label}
				bsStyle={ touched && error ? 'error' : null}
				hasFeedback
				help={ touched && error ? error : helpMsg}
			/>
		);
	}
});

export default injectIntl(TranslatedValidatedInput);
```

It is used in the form like this:

```jsx
<form onSubmit={handleSubmit}>
	{errorAlert}
	<TranslatedValidatedInput
		type="text"
		bsSize="large"
		formName="account" <----- passing formName manually
		autoComplete="off"
		{...name}
	/>
...
```

You could say I could dispense with the `formName` altogether from the i18n keys, but several forms have similar field names with different translations, so there is the need to disambiguate among them.

**Comment by DrMeers** [comment]
Yes, I'd also love to be able to access the form name from within fields for similar reasons to Danita -- database-managed labels/tooltips namespaced via form names

**Comment by harlynx** [comment]
@jaroslawr mentions a common and important use case. How would one approach this given that the form context is not passed down? I don't like to make the second parameter of reduxForm mandatory just because I use form labels. And generating random unique id strings just for the sake of labels is overload.

**Comment by gustavohenke** [comment]
Hi guys, this will finally land in the next release of the v6 branch 🚢 
See #2386 and #2400 for context.

I'm afraid that there won't be v5 releases any further.
