### ISSUE TITLE
Value vs defaultValue for dynamically created form fields

### ISSUE THREAD

**Issue by kyleboyle** [erikras/redux-form#261]
I'm creating a dynamic form (validators, fields, initalValues passed as props to form component). It appears as though the defaultValue for the fields are set correctly, but I have validators that are failing because the value is undefined until the user modifies the value in a field from it's default value. Shouldn't the value be set to the defaultValue on form creation? The "value" key of my dynamic form field objects is initially not defined (key isn't present). 

For example, here is a dynamic field "2.number", with proper defaultValue but no value and thus is failing a validator that checks for it being defined:

![screen shot 2015-11-11 at 2 57 37 pm](https://cloud.githubusercontent.com/assets/6877108/11099972/c22e9ce2-8884-11e5-8087-920ce91d1f42.png)

**Comment by erikras** [comment]
This is very interesting. Can you submit the redux state for the form reducer? e.g. with redux-devtools running, show that the `INITIALIZE` action has fired, and its result?

**Comment by kyleboyle** [comment]
Sorry, this was my fault. I mistakenly had 2 dynamic forms with the same name. redux-forms is great thank you.

**Comment by erikras** [comment]
Awesome. Glad you worked it out. :+1:

**Comment by Lonelind** [comment]
I've faced the similar problem:

I have form with two inputs that represent ```min``` and ```max``` amount. And I should generate ```(max - min + 1)``` fields when any of those two changed. The problem is that I need to get values from this field and pass correct amount of dynamic fields inside form component. It looks like this:

```jsx
// reducer.jsx
// The structure is important because I have multiple forms in my App and there will be
// three different forms inside view.form simultaneously. Alongside I must have some
// non-form data for this view and have a reducer for it.

import { reducer } from 'redux-form';

export default combineReducers({
    /* ... */
    view: combineReducers({
        form: reducer.normalize({
            generalInfo: {
                min: minNormalizer,
                max: maxNormalizer,
            },
        }),
        data: someDataReducer,
    }),
});
```

```jsx
// FormContainer

@connect((state) => ({ 
    min: parseInt(state.view.form.generalInfo.min.value, 10),
    max: parseInt(state.view.form.generalInfo.max.value, 10),
})
export default class FormContainer extends React.Component {
    render() {
        let fields = [ 'min', 'max' ];

        // fill up fields array with proper field names (the index really matters)
        Array(this.props.max - this.props.min + 1).fill(0)
            .forEach((item, index) => {
                fields.push('dynamicField' + (index + this.props.min));
            });

        return (
            <DynamicForm
                fields={fields}
            />
        );
    }
}
```

Nothing seems difficult here. 
And the next code block is where I'm not sure that I made it correctly:
 
```jsx
// DynamicForm

import { reduxForm } from 'redux-form';

@reduxForm({ form: 'generalInfo', reduxMountPoint: 'view' })
export default class DynamicForm extends React.Component {
    render() {
        const {
            fields: {
                min,
                max,
            },
            handleSubmit,
        } = this.props,

        minAmount = parseInt(min.value, 10);
        maxAmount = parseInt(max.value, 10);

        // Below I do the same trick with Array.fill to render fields
        return (
            <form onSubmit={handleSubmit}>
                Min: <input {...min} />
                Max: <input {...max} />
                {Array(maxAmount - minAmount + 1).fill(0)
                    .map((item, index) => {
                        <div key={index}>
                            <input {...this.props.fields['dynamicField' + (index + minAmount)]} />
                        </div>
                    })}
            </form>
        );
    }
}
```

The form renders successfully. I simplified the code, but default values for min and max are ```1```. And yes, I have one dynamic field. I change ```min``` and ```max``` fields and read this changes inside ```FormContainer```, so ```fields``` array is correct and I get all of them inside ```DynamicForm``` component. But I still have only one field rendered. 

Tried to fix this I've got that ```this.props.fields.max.value``` is ```undefined``` inside ```DynamicForm```. I logged ```props``` on render and on every change I get normal values from ```FormContainer``` and default ones from ```DynamicForm```. So, this means, that ```onChange``` handler works correctly and passes values to the store, and stores ```value``` prop to ```<input>```. This is how React works. But when I try to get value prop from field object I don't have it at all. ```this.props.values``` doesn't change too: it has all fields names as keys, that initialized with ```undefined```.
