### ISSUE TITLE
How do I tell which values are dirty in onSubmit?

### ISSUE THREAD

**Issue by aherriot** [erikras/redux-form#2621]
What is the best way to tell which values have been modified from the `initialValues` in my `onSubmit` method?

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
