### ISSUE TITLE
issue with destroyOnUnmount

### ISSUE THREAD

**Issue by rmv125** [erikras/redux-form#2641]
I m developing component which allow to select date.
So it is a select which contains options like Day, Week, and have the Custom option. If "custom" is selected one more field should be rendered.
It looks like that:
![day](http://storage6.static.itmages.com/i/17/0301/h_1488386171_5511761_1be1ac6efc.png) ![custom](http://storage8.static.itmages.com/i/17/0301/h_1488386214_4123059_d6da61c720.png)
So the problem:
I select "custom" and the additional field renders
I change that additional field
I select not "custom" and the additional field unmounts
but the value is not removed from the form state!
I have destroyOnUnmount set to true.
Here how action log looks like:
![log](http://storage3.static.itmages.com/i/17/0301/h_1488386533_5793368_8e2642581e.png)

Can anyone explain what i'm doing wrong?

**Comment by gustavohenke** [comment]
Basically, if it's in your values data, then it'll be sent.
You could try passing a callback to [`onChange`](http://redux-form.com/6.5.0/docs/api/Field.md/#-onchange-event-newvalue-previousvalue-void-optional-) in order to reset the data of the additional field.

The next you open an issue here, please follow the template. It was made for a reason.
