### ISSUE TITLE
how can I disabled 'enter' for submissing?

### ISSUE THREAD

**Issue by lzpBlack** [erikras/redux-form#2655]
how can I disabled 'enter' for submissing? 

sometimes , I don't want 'enter' for submissing , I want disabled it。

**Comment by gustavohenke** [comment]
This issue doesn't belong to our GitHub issue tracker.
We request you to [ask again at StackOverflow](https://stackoverflow.com/questions/ask?tags=redux-form), using the `redux-form` tag, then post the question link here.
*As usual*, don't forget to explain your question well and show what you've got so far!

This is because the GitHub issue tracker is better suited for discussions related to bugs and improvements of Redux Form.
Meanwhile, StackOverflow is better at keeping popular questions visible, while separating feature-related questions from help-related questions.

Thanks for using Redux Form!
