### ISSUE TITLE
Focus on first input field

### ISSUE THREAD

**Issue by m1m6** [erikras/redux-form#2732]
Hi, i'm trying to set the first input field in any form to be focused, so what is the best practice to implement something like this, and how could i check the type of the field, is it text, number, checkbox...etc.

is by listening to @redux-form actions, and then dispatch an focus action?

**Comment by vnctaing** [comment]
I don't see any problem, sounds like a good solution to me

**Comment by gustavohenke** [comment]
Just use `autoFocus` prop.
[This is plain HTML5 btw, no JS involved](https://davidwalsh.name/autofocus).

**Comment by m1m6** [comment]
@gustavohenke and if i have a 20 form ? is there any other way to do it other than manually

**Comment by gustavohenke** [comment]
If you have 20 forms in your page and you want every one of them to focus their first field, the behavior is unpredictable anyway.

`autoFocus` is way more reliable than listening for Redux Form actions... and quite better than setting up refs to your fields in order to call `.focus()` on them.
Just choose the main form of your page to receive the `autoFocus` prop!

**Comment by thiagofront** [comment]
and if I need to focus on the first input that has no value

**Comment by ernani** [comment]
You will need to iterate through the fields and check which one should receive the call to `.focus()`.
