### ISSUE TITLE
Synchronous validation isn't performed on props change

### ISSUE THREAD

**Issue by danielevns** [erikras/redux-form#2809]
When a wrapped component receives new props, `render` is called but the synchronous `validate` method is not. This is problematic when `validate` uses props because previously valid form values may become invalid with new props. The expected behavior is for `validate` to be called whenever `render` is called.

I've reproduced the issue in a minimal example [here](http://codepen.io/danielevns/pen/WjNOxX): The input value is valid if it is greater than or equal to the counter.

I am using the latest version of redux-form (6.2.2) and React 15.5.4.

This appears to be the same issue as #1152, but I was advised to create a new issue because the previous one applied to v5.

**Comment by erikras** [comment]
At first I thought this was a bug, but now I realize that it's more of a mild annoyance that the library already has a workaround built for.

The synchronous validation cannot be called on every prop change, because sometimes the prop changes are from the internal `redux-form` state. For example, when `valid` switches from `true` to `false`, we needn't call the synchronous validation _again_ just because `!deepEqual(props, nextProps)`.

However, we already have a built-in way for the library user to override the logic about whether or not to run validation. It's called [`shouldValidate`](http://redux-form.com/6.6.3/docs/api/ReduxForm.md/#-shouldvalidate-params-boolean-optional-). Below is a sandbox demonstrating how to implement `shouldValidate()`, specifically identifying props that your validation function needs to know if they have changed. See `SyncValidationForm:15`.

[![Edit Redux Form - Issue #2809](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0R6y1WppK)

**Comment by Limycuk** [comment]
redux-form version 7.2.0

Sandbox doesn't work =(
shouldValidate(params) : boolean [optional] DEPRECATED #

what a new way to handle onChange nextProps?

**Comment by gustavohenke** [comment]
`shouldValidate`.
