### ISSUE TITLE
Warnings on using Field in my form.

### ISSUE THREAD

**Issue by parth7676** [erikras/redux-form#2821]
**You are manually calling a React.PropTypes validation function for the `name` prop on `Field`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library.**

What should be solution to this?

**Comment by gustavohenke** [comment]
If you're using v6: migrate to [v6.6.3](https://github.com/erikras/redux-form/releases/tag/v6.6.3), which fixes this.
If you're using v5: [v5.3.5](https://github.com/erikras/redux-form/releases/tag/v5.3.5) was supposed to fix this, but then it introduced yet another issue: #2824 

I may be wrong though because this message seems to be different than the one reported in #2810
