### ISSUE TITLE
Field validation not triggered after reset

### ISSUE THREAD

**Issue by bbenezech** [erikras/redux-form#2838]
Very easy to reproduce:

https://codesandbox.io/s/o22j1lOZB

Modify age, then reset, then modify age, then submit.
Field validation on `Username` and `Email` are bypassed.
`UPDATE_SYNC_ERRORS` is not triggered after reset like it is when a validated field is dirty.

It looks like the conditions `updateSyncErrorsIfNeeded` are incorrects.

This is a major issue IMO. I have no easy workaround. 
@erikras I know you must be terribly busy but can you have a look?

**Comment by irvingv8** [comment]
Hello there @bbenezech!

Where did u got that sandbox from ? 

I certainly can reproduce the behavior on it, but I can't do it on the codesanbox provided in the docs:

https://codesandbox.io/s/PNQYw1kVy

perhaps someone screwed up while setting it up ?

**Comment by bbenezech** [comment]
@irvingv8 The only difference is the absence of validation on `age`.
If the modified field is validated, it works, if not, it doesn't. Sorry I should have made that clearer.

I looked at the conditionals in `updateSyncErrorsIfNeeded`, not sure I can do it, I have no clear idea what is going on here.

**Comment by irvingv8** [comment]
Ok! I Believe I fixed it! I'll submit a pull request, will be my first contribution to OSS <3! hopefully I did it well, even though this was an easy one

**Comment by irvingv8** [comment]
@erikras is there any guide/steps on how to contribute to redux-forms? It was little bit hard for me to get to test what i modified, I find the rebuild examples script, but it was going over all of the examples taking a LOT of time to rebuild each of them and I just wanted to test a single one. 

I ended up deleting all the other examples, running the script and testing...

Maybe the script could take the name of a example to rebuild ?

**Comment by timhwang21** [comment]
I actually ran into this exact issue myself a while back. Really appreciate the PR, and I'm willing to help get this moved along!

You probably want to add a test [here](https://github.com/erikras/redux-form/blob/master/src/__tests__/reducer.reset.spec.js). Specifically, something like `it should not erase sync errors if they exist.` The test structure is pretty self-explanatory.

One question I have: I'm wondering about the order of things happening. 

1. [Validation seems to happen when new props are received](https://github.com/erikras/redux-form/blob/809c8414121ba2c3de1a5797d259ac4ebb56193e/src/reduxForm.js#L244). This function checks to see if values are deeply equal, and skips validation if so.
2. Your PR seems to be simultaneously setting the `values` to `initialValues`, and `syncErrors` to the existing `syncErrors`. Wouldn't these errors be outdated, so to speak?
3. The issue is only happening when "Age" is the only field populated when the form is reset. In other words, validation is being run after resetting when "Name" or "Email" field values change upon reset. It's not that errors aren't being properly persisted.

It seems the correct fix would lie in making either `updateSyncErrorsIfNeeded` or `validateIfNeeded` in the main file more robust.

**Comment by irvingv8** [comment]
Ty for the guidance @timhwang21, now that you mention it, it totally makes sense, I went straight to the fact that syncErrors was out of the state right after the reset, but you are right, there is something more to it as it only happens when the non validated field is the one populated. 

I'll take another shot at it in a couple of hours and see if I can get to culprit of the trouble.

And about:

> Your PR seems to be simultaneously setting the values to initialValues, and syncErrors to the existing syncErrors. Wouldn't these errors be outdated, so to speak?

values -> initialValues was already there.
And sorry but i didn't understand the "Wouldn't these errors be outdated, so to speak?", problem i found was that after the reset syncErrors wasn't in state anymore, so I'm not setting syncErrors to the existing ones (cause they don't exist), but I might be wrong it's my first time looking at the core.

**Comment by timhwang21** [comment]
Sure, what I meant is that values and errors are being populated at the same time in reset. Validation happens on the new values AFTER reset. The errors you are propagating are the errors from BEFORE reset. Hence any new errors caused by the reset won't be saved. Though, in the edge case at play here, if the reset causes errors then set validation would probably be called anyways. So it might work but strikes me as an indirect solution.

There was a PS from the last release that changes accessing errors from props to a property set on this, I had to stop digging but it seems this may be a regression due to that fix.

**Comment by erikras** [comment]
Good news, guys. I found the bug. This was a tricky one.

**Comment by irvingv8** [comment]
Would be great If you could share some details, I'd like to get started helping people on this repo, sorry for the Pull Request, It was my first time looking at the core. Is there any way I can contact you if I have any doubts about it ?

**Comment by erikras** [comment]
Published fix as [`v6.7.0`](https://github.com/erikras/redux-form/releases/tag/v6.7.0).

@irvingv8 Twitter or email (see `package.json`)

**Comment by SpearThruster** [comment]
This is still not working, no action for UPDATE_SYNC_ERROR is being dispatched & no validation occurs.

**Comment by arman-mukatov** [comment]
I confirm, the problem is not solved yet, after the reset, verification is not carried out..

**Comment by irvingv8** [comment]
@arman-mukatov could you provide a codesanbox sample to test ? I can no longer reproduce this issue with 6.8.0

**Comment by HiroAgustin** [comment]
I have this same problem using version `7.0.3`

**Comment by danielrob** [comment]
I won't re-open this bug because the original reproduction sandbox + repro steps do not work against the [same sandbox upgraded to 7.0.3](https://codesandbox.io/s/3lL40Jy5M). If you are still experiencing an issue like this, please create a new formal issue report.

**Comment by ashishlal91** [comment]
I am having same problem... validation does not work after reset form...
