### ISSUE TITLE
Minus sign in number input does not work with normalize

### ISSUE THREAD

**Issue by terencechow** [erikras/redux-form#2839]
### Are you submitting a **bug report** or a **feature request**?
Bug.

Trying to use the normalize function in a field that is of type Number. I want to only allow numbers between 0-9999. When someone types a - it is allowed because html5 allows - in a number input.

I was hoping to regex that out in normalize but when I console log the value in the normalize function '-' shows up as an empty string. Hence I can't regex for it.

### What is the current behavior?
Current behaviour is that I can '-' shows up as empty string '' in the normalize function of a field of type number

### What is the expected behavior?
Expected behaviour is that I can '-' shows up as '-' in the normalize function of number input type

**Comment by irvingv8** [comment]
Hello there, I've been looking into this, and it looks like it's a bug with the input type=number itself, if you create an html input with type number write "-" in it and try to access it's value via JS you will get an empty string. What's worse it'll allow you to write multiple "-"

My suggestion will be to use input type text, use regex to allow only digits. Something among the lines of this: 

  (value, previousValue, allValues) =>{
    const empty = /^$/
    const reg = /[\d]/
    return empty.test(value) ? 0 : reg.test(value) ? value : previousValue
  }


the empty regex is to check that if the user types something like "20" and wants to delete everything he's able to (otherwise he'll be stuck at 2), could enhance user experience trimming the leading 0 for the user.

**Comment by danielrob** [comment]
Not sure your assertions there @irvingv8's, a play over at https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_number seems to provide the negative value regardless of min max. 

@terencechow please provide a repro of this issue (e.g. in a sandbox).

**Comment by irvingv8** [comment]
@danielrob It does provide the value if you actually put a number in there, but as he is trying to normalize the input, he wants to get the value for everything that's being typed in. So if the user starts typing '-' and you try to get the value at that point, you will get and empty string.

**Comment by danielrob** [comment]
Gotcha! Thank you then for your excellent answer, this seems to more than adequately answer this question.
