### ISSUE TITLE
[v6.6.3] onSubmit function doesn't provide "values", "dispatch", and "props" as arguments

### ISSUE THREAD

**Issue by MaxInMoon** [erikras/redux-form#2848]
**Bug**

The `onSubmit` function passed by the parent, give me `(event1, event2)` as arguments, instead of `(values, dispatch, props)`
(When input values change, I can see updated values into the store)

**Step to reproduce**

- The getting started [example](http://redux-form.com/6.6.3/docs/GettingStarted.md/) with redux-form v6.6.3
- Observe arguments received in the `onSubmit`function

**Versions**
```
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.3",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^5.0.0-alpha.6",
    "redux": "^3.6.0",
    "redux-form": "^6.6.3",
    "redux-saga": "^0.14.7",
    "redux-thunk": "^2.2.0",
```

_________________________________________

I simply followed the "getting started" example, triple checked issues opened and closed, and something escapes me! 
Thx by advance

**Comment by danielrob** [comment]
Hi! Thanks for getting started with redux-form and sorry no one replied sooner. I can certainly confirm this functionality is not broken, so I think you'll need to provide some code so we can better advise. Also, stack overflow is a great place for usage questions where you might get more help sooner. 

I suggest taking a look at the simple form example, but I also added logging to the [console in this sandbox](https://codesandbox.io/s/66ZWkA55n) to show you that those properties are being passed. 

I'll close this out since it is a usage question which is a few months old, but feel free to reply if you still need clarification.

**Comment by MaxInMoon** [comment]
@danielrob thanks for you feedback!

My problem came because I was passing the submit function to the form as a `handleSubmit` or `onSubmit` prop, which I think overrides the redux-form prop.

When I discovered the redux-form lib I was too exited, and I certainly missed few lines on the doc ;)

**Comment by danielrob** [comment]
@MaxInMoon a truly excellent reason ;).
