### ISSUE TITLE
GetFormValues without loosing original state

### ISSUE THREAD

**Issue by FKSI** [erikras/redux-form#2861]
Hi,

According to the documentation example:

```
SelectingFormValuesForm = reduxForm({
  form: 'selectingFormValues'  // a unique identifier for this form
})(SelectingFormValuesForm)

// Decorate with connect to read form values
const selector = formValueSelector('selectingFormValues') // <-- same as form name
SelectingFormValuesForm = connect(
  state => {
    // can select values individually
    const hasEmailValue = selector(state, 'hasEmail')
    const favoriteColorValue = selector(state, 'favoriteColor')
    // or together as a group
    const { firstName, lastName } = selector(state, 'firstName', 'lastName')
    return {
      hasEmailValue,
      favoriteColorValue,
      fullName: `${firstName || ''} ${lastName || ''}`
    }
  }
)(SelectingFormValuesForm)

export default SelectingFormValuesForm
```

The `mapStateToProps` function will not return the current state but only the one describe in the function itself. 

When trying to use `Object.assign({}, state, { ... })` I get what I want but the in state the form object looks like: 

```
form
    object Object
```

Instead of 

```
form
    <name of the form>
```

Thanks for you help :)

**Comment by gustavohenke** [comment]
> When trying to use Object.assign({}, state, { ... }) I get what I want

Ah, don't do that. Every time *anything* in the state changes, so does your component! That could be *a lot* of re-renderizations!
You certainly don't need all of the state, so I recommend you to be selective regarding what you pass to your component.

Finally, `form` is an object instead of a string with the name of the form because... **it was overridden by yourself. And now this is the name of the form**.
`form` is the default key where Redux Form reducer is mounted, so all of its state is located under this key.

That being said, there's not much we can do about it.

Thanks for using Redux Form!
