### ISSUE TITLE
Adding default value input type

### ISSUE THREAD

**Issue by radvc** [erikras/redux-form#2874]
Hi, im having a problem by adding a default value on one of my input type

`
<Field component={component} placeholder={placeholder} value={this.state.price} />
`
the problem is the value didn't pass to the component. When I try to display the value it is empty and nothing is in there.

**Comment by Nopzen** [comment]
As i recall its called `defaultValue` instead of value, hope it helps

**Comment by gustavohenke** [comment]
Closing in favor of the older, more upvoted #1964

**Comment by adriantoddross** [comment]
So does defaultValue work, or not? Because I'm having the same issue right now and even adding a value attribute to my custom component doesn't seem to do anything.

**Comment by danielrob** [comment]
@adriantoddross the OP's case may not have worked because passing value to `Field` will only work if the value is passed through to the actual element (e.g. `<input value={this.props.input.value} />`). `defaultValue` is for uncontrolled form fields, and shouldn't be used here. If you want to initialize your form with initial values use the [`initialValues`](https://redux-form.com/7.3.0/docs/api/reduxform.md/#-code-initialvalues-object-lt-string-string-gt-code-optional-) prop. This cannot be done at a field level currently, though you could add your vote to #1964 for this.
