### ISSUE TITLE
Select with dynamic options

### ISSUE THREAD

**Issue by jiexishede** [erikras/redux-form#2883]
### Are you submitting a **bug report** or a **feature request**?

feature request

http://stackoverflow.com/questions/43600649/material-ui-redux-from-select-with-dynamic-options

**Comment by timhwang21** [comment]
We use the `react-select`, and pass the dynamic options to the widget as a prop, which works well. Looking at your link, your issue might be fixed by passing empty array as a default `options`? Regardless, this library expects you to bring in your own widgets -- it doesn't provide form elements of its own.

**Comment by jiexishede** [comment]
@timhwang21  Thank you very much.

**Comment by gustavohenke** [comment]
I looked at your question and I agree with @timhwang21.
