### ISSUE TITLE
Could not find "store" in either the context or props of "Connect(ReduxForm)"

### ISSUE THREAD

**Issue by devarashetty** [erikras/redux-form#2900]
I am facing the following  error 

```Could not find "store" in either the context or props of "Connect(ReduxForm)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ReduxForm).```

**Comment by erikras** [comment]
The error is exactly right. You should read [the `react-redux` docs](http://redux.js.org/docs/basics/UsageWithReact.html#passing-the-store) to understand how to provide the Redux store to all your components.

**Comment by moimikey** [comment]
@erikas then was this false information? https://twitter.com/dan_abramov/status/630774054237175808?lang=en

**Comment by erikras** [comment]
That tweet is using the technical meaning of "dependency". `redux` and `react-redux` are [_peer_ dependencies](https://github.com/erikras/redux-form/blob/master/package.json#L113-L114) of `redux-form`.

In other words, **you cannot use `redux-form` without also using `redux` and `react-redux`**.

That said, the problem you are having is because you do not have `react-redux` configured properly. You should run through some of the tutorials for that library before attempting to use `redux-form`.
