### ISSUE TITLE
Why redux-form uses action instead of event callback to fire field value change?

### ISSUE THREAD

**Issue by quytang** [erikras/redux-form#2936]
I have a question that why redux form using action to dispatch change? Should it use callback instead? It's strange to me and I don't feel comfortable with it.

--
P.S. Sorry if this issue annoys you but I dig in the internet all day and can find out the answer.

**Comment by erikras** [comment]
I'm not sure I understand your question. The way state is changed in Redux is with dispatching actions.

**Comment by quytang** [comment]
Hi @erikras,
Redux-form fire action in every single key-stroke. It's not traditional way to deal with events.
If I input 3 a keys it will dispatch 3 actions.

<img width="509" alt="screen shot 2017-05-17 at 11 12 51 am" src="https://cloud.githubusercontent.com/assets/6160148/26152479/b0de6210-3b39-11e7-9fb1-cdb5cb05622e.png">

For example,
```
class Form extends React.Component {
...
      render() {
           <form onSubmit={this.onSubmit}>
                ...
                <input name="name" onChange={this.onChange} />
           </form>
      }
}
```
My question is why reduct form not do this way instead.
I think onSubmit can use action to dispatch but apply to the others is a little weird.

**Comment by marcselman** [comment]
Redux holds a global state object and the only correct way to update this state is by dispatching an action. Redux-form was designed to be used with Redux and thus uses this method (based on the Flux architecture). There are a lot of other form components available for React which use global state for example or other methods which you might be more comfortable with. Local state has the problem though that when the component is unmounted and remounted the state is reset.
I suggest taking the time to learn more about the Redux style because, in my opinion, it has a lot of advantages and is well worth the effort to learn it.

**Comment by quytang** [comment]
Thank you @marcselman. Yikes, I know about redux and its architecture.
But I don't think we should always deal with global state. 
Is it redundant If every ui event of the application stay at the global state tree. Would it soon become a massive state tree.
I am new to redux/react framework. Thus, I don't know wether I am wrong but It's my opinion.

**Comment by erikras** [comment]
1. The creators of Redux are on the record as saying that they think using Redux for every keypress on a form input is overkill.
2. Thousands of developers are using this library to great success.

⚖️ It's up to you.

**Comment by quytang** [comment]
thanks @erikras
