### ISSUE TITLE
Input type number is storing as string

### ISSUE THREAD

**Issue by 10SPD** [erikras/redux-form#2940]
Redux@6.7.0

From the documentation, it says that inputs of type "number" will be stored as numbers. However, as you can see in my screenshot it is storing the values as a string. It would be awful if I have to parse them manually as this would be unnecessary looping.

**Component**
```
export const renderInput = ({ input, label, placeholder, type, meta: { touched, error } }) => (
    <Form.Field>
        <label>{label}</label>
        <input {...input} type={type} placeholder={placeholder} class={'' + (touched && error) ? 'error' : ''} />
    </Form.Field>
);
```

**Field of type: number**
```
<Field component={renderInput}
          name="baseValue" label="Default value"
           placeholder="0"
           type="number"
                        />
```

![screen](https://cloud.githubusercontent.com/assets/12517969/26199799/aa3b903a-3bcb-11e7-96f8-56e911a90c58.png)

**Comment by sanohin** [comment]
You can use `parse` prop on Field.
```javascript
<Field component={renderInput}
          parse={value => Number(value)}
          name="baseValue"
          label="Default value"
          placeholder="0"
          type="number"
/>
```

**Comment by atatakobry** [comment]
how can i set initial undefined value, cause `Number('') -> 0`?

**Comment by gustavohenke** [comment]
> From the documentation, it says that inputs of type "number" will be stored as numbers.

@10SPD can you point where in the docs this is?

**Comment by alicerocheman** [comment]
it would be great if the inputs of type 'number' remained numbers throughout the process! :)

**Comment by pawarvijay** [comment]
@sanohin last digit 0 cannot be removed , giving a bad user experience [example](https://codesandbox.io/s/6jjp4o8rjr)

**Comment by MichaelBuen** [comment]
@pawarvijay can use this:

```javascript
parse={value => !value ? null : Number(value)
```

**Comment by cdimitroulas** [comment]
@MichaelBuen that does not allow you to enter a value of 0.

Something like this might be better:
```js
parse={value => isNaN(parseInt(val, 10)) ? null : parseInt(val, 10)
```

**Comment by mrchief** [comment]
`type="number"` simply adds the HTML attribute so browsers show up/down controls. It still doesn't store anything as numbers, rather strings. While `parse` workarounds are nice to have, it's seems like redux-form should handle that internally - and spare the world from the `parse={...}` ceremony.

**Comment by danielrob** [comment]
You can't store all valid numbers that can be entered into a number input in javascript as a number, so as a library how can you universally decide when a string should be converted to a number? 
```
const piStr = "3.14159265358979323846264338327950288419716"
Number(piStr)
// 3.141592653589793
```

Additionally how should it be converted to a number? If it was the same mechanism as checkbox values are altered when `type=checkbox` was detected then you could end up at:  

`Number("023") // returns 23 - safe if just using component="input"` but
`Number(023) // returns 19  -  which could happen for a custom onChange call.`

I can understand this is a desirable common case default, but I think it adds unneeded complexity. A string is a safer default format, as well as being aligned with HTML standard. I think this is the type of problem the end developer should be forced to deal with.

**Comment by mrchief** [comment]
Those are edge cases or rather not commonplace. Most forms are simple and shouldn’t require such acrobatics.

**Comment by mrchief** [comment]
Hit send earlier than I intended to...

In the end, it’s about having sane defaults. And the principal of least surprise. If I’m saying I want the type to be number, I expect a number. 

If I overflow it, then it’s up-to me to deal with it, and not the other way around. I shouldn’t be forced to convert everything from string to it’s respective type.

**Comment by mrchief** [comment]
> I just think it's too dangerous. A string not being a number fails fast in developers eyes. A string being cast into a number and silently losing data, could end up being a prod bug.

I see your point. In fact, I've even experienced the prod bug scenario in jQuery world. :)

> It's true that it's hard to initially imagine the cases where overflow becomes a concern. But my bank account number has the same amount of digits as the max integer. Add a routing number, and you've got yourself an overflow.

Your bank account number is 300+ chars long? But I see your point. However, I also think those can be overcome/prevented with the help of proper docs/examples. Many people may not know about those or may not think about those - but mentioning them in examples or drawing attention to those, will help in reminding and spreading the awareness.

Further, by RF automatically treating everything as string and asking folks to implement the parse workaround (without educating them about the underlying problem) still makes them vulnerable to the prod bug scenario (i.e. they may not realize they are silently losing data).

> Primarily, I think this expectation that a number would be stored as a number comes from jsx.

Jeez, this reminds me how long it has been since I used a vanilla HTML form! I think you maybe right but that we're all in JSX land right now so might as well focus on that. And it's not just JSX - it also stems from JSON based APIs - where the type matters. 

> Secondly, if parsing to a number is the default, then how would the API look for folks that don't want that? 

If someone wants this behavior, they can always implement the `parse={x=> x.toString()}` workaround. Or maybe it's driven by the `initialValues` (see below).

> At the moment specifying type="number" and using parse are decoupled concerns. 

I agree. And I'm not insisting we should tie it to `type="number"` either (although browsers do not allow any string to be input in a numeric field - so it's a pretty strong hint that the underlying model is a number). 

Or maybe we can infer the types from the `initialValues` - the idea being that by default everything is string - but if the model is initialized with numbers, then it honors that. 

Or maybe we introduce a flag - say `preserveNumbers` or something - which keeps numbers as numbers.

In the end, I agree that there are no perfect answers. And I very much appreciate you taking time for your inputs. At the very least, we should have something in docs and examples about this situation.

**Comment by CodenameCookie** [comment]
How can you do math on the value if you cant get them out as a number?

**Comment by CodenameCookie** [comment]
> @MichaelBuen that does not allow you to enter a value of 0.
> 
> Something like this might be better:
> 
> ```js
> parse={value => isNaN(parseInt(val, 10)) ? null : parseInt(val, 10)}
> ```

Challenge with that will be it doesnt allow for floats. We need something more robust. No offence but I am kinda shocked there isnt.

**Comment by iamandrewluca** [comment]
`redux-form` it gives you ways to transform state: `parse`, `format`, `normalize`. Even `<input type="number" />` does store the value as string. This should solve all problems. `Number` allows floats and `''` (empty string) will be parsed as 0 and showed into input.
```
<Field
  name="theOne"
  component="input"
  type="number"
  parse={Number}
/>
```
`redux-form` is not responsible for transforming state, but it gives you ways to do so.
