### ISSUE TITLE
FieldArray meta.error never contains any error of the array objects

### ISSUE THREAD

**Issue by kromit** [erikras/redux-form#2967]
bug report

### What is the current behavior?
`FieldArray` with `name='items'` `meta.error` prop always contains an empty items array. 
```
meta:{
    error:{
        items:[] // missing errors
    },
    dirty:true,
    invalid:true,
    ...
}
```

### What is the expected behavior?
`meta.error` should contain an array of objects with errors.
```
meta:{
    error:{
         items:[
          {itemName:"missing value"},
          {itemName:"missing value",itemNr:"not a number"}
    },
    dirty:true,
    invalid:true,
    ...
}
```

version 6.7.0

**Comment by danielrob** [comment]
This was duplicated by #3173, but I'm keeping that one open as it was expressed as an enhancement which is more accurate. 

The `meta.error` prop is for reporting errors from the validate function passed to FieldArray itself, or errors otherwise placed under the `arrayname._error key`. #3173 tracks that it might be useful if more errors could be added to this prop.
