### ISSUE TITLE
how to pass  action type if login succes with redux-form

### ISSUE THREAD

**Issue by mynameisbams** [erikras/redux-form#2973]
i try make login, when i login and the loginis success then passing type: 'Login'... but not worked... anyone have solution for me?

when i put action.type in console.log it just show me '@@redux-form/SET_SUBMIT_SUCCEEDED' not 'Login'

    export function login(data) {
        if (data.email === 'me') {
            //NavigationActions.navigate({ routeName: 'Route' });
            console.log("login success");
            //dispatch({type: 'Login'});
            //type:Login,
            return (dispatch) => {
                dispatch({type:'Login'})
            }
            // return (dispatch) => {
            //     console.log(dispatch);
            //     console.log("===>", action)
            // };
        }else{
            console.log("login error");
        }
    }

:(

**Comment by gustavohenke** [comment]
Your issue doesn't belong in our GitHub issue tracker, because it seems to be a usage support question; in this case, please open a question in StackOverflow, and use the `redux-form` tag.

If we're wrong, or if you are able to lay it out better, perhaps we will be able to help you.
In this case, please open a new issue.

Thanks for using Redux Form!
