### ISSUE TITLE
Why handleSubmit triggers asyncValidate

### ISSUE THREAD

**Issue by zed31124** [erikras/redux-form#3031]

**Comment by gustavohenke** [comment]
> Why handleSubmit triggers asyncValidate

...because if something in the server changed since you filled an async validated field, that could cause a conflict (like a signup form), so you can handle it before submitting.

If you would like to propose some enhancement, please open a new issue, providing more evidence to support you.
Otherwise, it's better to ask somewhere else, since here is not the best place for this.
