### ISSUE TITLE
setting focus to a field programmatically (react-native)

### ISSUE THREAD

**Issue by jasan-s** [erikras/redux-form#3065]
I set a ref on a field like so in a stateless component :
 ` <Field ref={(e) => {textInput = e}} name='email' returnKeyType={'done'}
 component={reduxFormTextInput} />`

then in another Field I did this:
`<Field name='name' component={reduxFormTextInput} onSubmitEditing ={() => moveFocus()}/>`

Outside of return (before) I defined the following: 
```
let textInput = null
const moveFocus = () => {
    console.log('ZZZZZZ')
    textInput.focus()
  }
```

The console.log outputs correctly if I comment out the ` textInput.focus()`  but left uncommented I get an error, that textInput.focus is not a function 
Without Using Field and using standard TextInput the focus function works

**Comment by gustavohenke** [comment]
> Without Using Field and using standard TextInput the focus function works

This is because your ref is for the `Field` component. This is React behaviour.
To get a ref to the internal instance of `reduxFormTextInput`, do this:

```
const moveFocus = () => {
  textInput.getRenderedComponent().focus()
}

<Field ref={ref => textInput = ref} withRef />
```

[Redux Form docs for this](http://redux-form.com/6.8.0/docs/api/Field.md/#-withref-boolean-optional-)

...but then you have another problem: your custom component `reduxFormTextInput` must provide an instance API for this to work.

First of all, make sure it is a class, not a functional component, because these have no instance API.
Then, in such class, provide a method called `focus`, which internally calls the `.focus()` method on the `TextInput` ref.

Good luck!

**Comment by iuliuvisovan** [comment]
I believe the way to do it now is just `this.input.focus()`. Using latest version of RN, and `getRenderedComponent` is not a function on a `textInput`.  `this.input.focus()` works tho.
