### ISSUE TITLE
Validate a single form element

### ISSUE THREAD

**Issue by maheshambiga** [erikras/redux-form#3125]
Is there any way to know if a single element of a form is valid. The scenario is, there are a couple of elements in a form and I need to enable/disable a button if a particular element is valid/invalid.

**Comment by gustavohenke** [comment]
Yes, there are a couple of selectors you can use to find out if a field is valid/invalid:

- `getFormSyncErrors`
- `getFormAsyncErrors`
- `getFormSubmitErrors`

[Full docs on available selectors in v6.8.0](http://redux-form.com/6.8.0/docs/api/Selectors.md/)

Unfortunately, you cannot use `isValid`/`isInvalid`, because it only supports testing whether the whole form is valid, and not a specific field.
