### ISSUE TITLE
Saving Indicator and long promise help

### ISSUE THREAD

**Issue by leemm** [erikras/redux-form#3146]
Hi.  I'm trying to display a UI Overlay during the save process.  I'm dispatch the ui change using a thunk, but the problem is it waits for the Promise to resolve before re-render occurs.  There is a _longPromise()_ in my code (can take around 10 seconds to action) so it's currently waiting 10 seconds before the indicator appears.

Any advice/pattern would be appreciated.  Thanks in advance!

```
save(values, validate, props){

    const {
        dispatch,
        setOverlay
    } = props;

    return dispatch( setOverlay(true, 'Saving User...') )
        .then(() => {

             return longPromise();

        });

}

render(){

    const { handleSubmit } = this.props;

    return (
        <form onSubmit={ handleSubmit(this.save) }>
            <span>Form fields here</span>
        </form>
    )

}
```

**Comment by jorrit** [comment]
I think you should use StackOverflow for support questions.

**Comment by gustavohenke** [comment]
@jorrit is right. Your issue doesn't belong in our GitHub issue tracker, because it seems to be a usage support question; in this case, please open a question in StackOverflow, and use the `redux-form` tag.

If we're wrong, or if you are able to lay it out better, perhaps we will be able to help you.
In this case, please open a new issue.

Thanks for using Redux Form!

---

*Hint:* look for the `submitting` prop.
