### ISSUE TITLE
Normalizer does not work with letters input

### ISSUE THREAD

**Issue by barjas** [erikras/redux-form#3150]
I have the following code : 

where CredtCardNormalizer is coming from the below code
```
<Field name={'number'}
component={ReduxFloatingInput}
placeholder="Credit card number"
icon="ios-card" maxLength={19}
keyboardType="numeric"
normalize={CredtCardNormalizer}
/>
const CredtCardNormalizer = (value, previousValue) => {

  if (!value) {
    return value
  }
  const onlyNums = value.replace(/[^\d]/g, '')

  if (onlyNums.length <= 4) {
    return onlyNums
  }
  if (onlyNums.length <= 8) {
    return onlyNums.slice(0, 4) + '-' + onlyNums.slice(4)
  }
  if (onlyNums.length <= 12) {
      return onlyNums.slice(0, 4) + '-' + onlyNums.slice(4, 8) + '-' + onlyNums.slice(8)
  }
  return onlyNums.slice(0, 4) + '-' + onlyNums.slice(4, 8) + '-' + onlyNums.slice(8, 12)+ '-' + onlyNums.slice(12)
  
}

```
the WIERD thing happening, all works fine: if i type numbers then the field got formatted: 
**1234-1234-1234-123**
BUT IF I TYPE ANY LETTER ? then the value of the text returned without any formatting 
**123-12abc**
am doing someinh wrong or is it a bug ? 

the other issue is that the value dispatched in the "action @ @ redux-form/CHANGE" is numeric only (which is correct) . that is even the field is showing "123-12abc" but the dispatched payload in the action is "123-12".... and the field looose focus (blure event) then it shows "123-12"

**Comment by klk1010** [comment]
This would probably be a more appropriate question for Stack Overflow.

You should insert the dashes separately in a format function. Remember, format gets called after the value is pulled out of the store, but before it is displayed to the user. It's used to convert values from a server friendly format to user friendly format. The result here should always be a string. This function should take the number and insert dashes where appropriate. 

The normalize function is called after a keystroke and is the last function called before the value is put in the store. This function should be used to put the value in a server friendly format. If your API is expecting a number string, this would be the place to strip out the dashes. Since you don't need to know about the inputs in other fields, you could also do this in the parse function and reserve normalize for more complex field to field stuff, but this should still work as expected if done in the normalize function as both are called after user input, but before storing the data. 

http://redux-form.com/6.8.0/docs/ValueLifecycle.md/
