### ISSUE TITLE
return promise on remote submit

### ISSUE THREAD

**Issue by iColpitts** [erikras/redux-form#3161]
** Feature Request **

I'm currently creating a form with 2 submit buttons. One of which advances the app and the next that submits the form and closes it. It would be great if I could dispatch the remote submit an have a promise returned which would allow me to direct the next step of the button as long as the form had not gotten a submission error.

**Comment by gustavohenke** [comment]
You can already do that: you just need to acquire a `ref` to your `reduxForm()` instance.
http://redux-form.com/6.8.0/docs/api/ReduxForm.md/#-submit-promise-

Via Redux actions, this is not possible, though. At least not easily.
How I would it via actions:
- use `connect` to get a prop that tells me whether the form
  - is submitting (via `isSubmitting` selector)
  - submitted with success (via `hasSubmitSucceeded` selector)
- dispatch `submit` action
- watch for changes to those props above in the `componentWilReceiveProps` lifecycle method _(tricky, right?)_

**Comment by ivawzh** [comment]
I have a pretty similar case. But I also need to be able to reuse the form without the same buttons.
Is it possible to make `submit` action return a promise and resolve on success, please?

**Comment by gustavohenke** [comment]
Hi  @ivawzh, it would be a lot better if you created a StackOverflow question for this.

**Comment by MarkPare** [comment]
This is one of the main weaknesses of redux form.  Remote submit allows for some great decoupling of forms (understood as a specific set of inputs and rules governing their operation) and the action that submits them.  The 2 things are distinct.  Getting a promise from remote submit would facilitate this decoupling.  I'm not knocking the library or its contributors, because it's already a great library and I'm grateful for it.  But this would be awesome.  You all accepting PRs?
