### ISSUE TITLE
Partial submit of FormSection ?

### ISSUE THREAD

**Issue by SBRK** [erikras/redux-form#3216]
Here is what I want to do, consider these initialValues:
```
{
  arr: [
    { field1: 'toto', field2: 'tata},
    { field1: 'tutu', field2: 'titi'},
  ],
  field3: 'foo',
  field4: 'bar,
}
```
How would I make a form in two parts, one for the `field3` and `field4` properties that would update the store on change, and another part for `arr` that would have a `FieldArray` with a `FieldSection` for the currently open member of `arr`, that would have its own update/cancel/remove buttons (so that the changes are only pushed when I press the update button, and if I press cancel, the FormSection is removed and nothing changes in the store, even if I changed something in the input of `field1` or `field2` for example)? I cannot use `reset` because then it would restore everything to its initial values, including `field3` or `field4`.

**Comment by danielrob** [comment]
I've personally solved this in two ways in my projects, but that's not to say there is not a better way. 

DIY FieldArray approach: 
Use the methods provided to FieldArray to manage the indexes value directly. This works especially well if you already have some custom components you normally pass to `Field` already. You can pretend to be a `Field` component for them, e.g. passing them an input.onChange function and input.value so that when updates are made to the field, you can just store them in your renderFieldArray component until such time as 'Update' button is pressed, at which point you dispatch an action to update the value for the appropriate FieldArray index. 

Heavy handed, but fully featured: 
Render an entire new sub-form (with reduxForm), who's on-submit action is to dispatch a change event for the primary form. This is nice in that it gives you independent validation, so the original form is only updated with a successful submit. 

Would either of these solve the problem for you?

**Comment by SBRK** [comment]
The second approach you described is pretty much the approach I took for now. The problem I had was that I had sync problems between the two forms.

My "main" form would have everything in `initialValues`, including `arr`, so on each update it would destroy whatever change I made to `arr` via the other form. I solved this by setting only the properties I needed in initialValues

**Comment by danielrob** [comment]
@SBRK I think we either need to close this issue out, or elaborate it more generally to make it a full blown enhancement/feature request. It's a bit murky at the moment, do you have any ideas?

**Comment by SBRK** [comment]
It could be an enhancement request but for now I'm just doing a custom solution. The FormSection sectionPrefix propagation is still a bit buggy anyway (see my recent issues), so a full subform feature is quite a long way away.
