### ISSUE TITLE
Select "default" value is not in values after submit

### ISSUE THREAD

**Issue by tonoslav** [erikras/redux-form#3226]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?
1. I have form
 - input:text , name: name
 - input:text , name: country
 - select, name: color (values: red, green, blue) (label = value)

2. Initialize values in componentWillMount 
this.props.dispatch(initialize(formSelector, {
        country: 'SVK'
}

3.  Type into **name** field = **Test**
     Don't change **color** field, because I see **red** selected (because it is first option)

4. Submit form
    Returned values : {
         'name': 'Test',
         'country': 'SVK'
    }

### What is the expected behavior?
4.  Returned values : {
         'name': 'Test',
         'country': 'SVK',
         'color': 'red'
    }

this works but only if I change **color** field 

### What's your environment?
Redux form: 6.7.0 
Node: 7.7.2

**Comment by danielrob** [comment]
Interesting idea. It would be helpful if you posted also your specific select setup.

In saying that the concept of default and initial values are practically the same in this instance, is there any reason why you couldn't or didn't want to do similarly to your country value initialisation?

**Comment by tonoslav** [comment]
@danielrob btw these are not exact values/fields I use, there are more than 40 fields, I just wanted to show example of what the problem is, because in basic html form if you have **select** field with some **options**, the first one is automatically selected even it doesn't has **selected** attribute and when you submit form you can get value of that **select** 

Do you know anything what can solve my problem? Should I call in my CustomSelect component for example in componentWillMount = **this.props.dispatch(change(formSelector, fieldname, options[0].value))** to ensure that first one will be set or is there any better solution?

**Comment by danielrob** [comment]
You can also use [intialValues](http://redux-form.com/7.0.1/docs/api/ReduxForm.md/#-code-initialvalues-object-lt-string-string-gt-code-optional-), though if for some reason you don't know the options in advance to generate the initialValues, then yes an onmount dispatch is a workaround. 

In general, yes, I personally would try to make my model be reflected in the view, rather than ever thinking about the view update the model on mount. If your model has defaults, set them in the `initialValues` and let that be reflected in the view.

**Comment by danielrob** [comment]
Closing this as answered support request.

**Comment by Skaronator** [comment]
Pretty crazy that the values doesn't really represent the current state of the form. This should be fixed IMO.

**Comment by tmbdrogba** [comment]
What if the <option> list is updated for any reasons ?

We have to manually change the value of the <select>, otherwise it is set to the previous one, wich maybe is no longer available as an <option> in the <select>.

**Comment by ernani** [comment]
It makes sense to have to set initialValues for that select to RED due to keeping a pristine state if you want it to be the default initial one. IMHO redux-form didn't capture an onChange event of that select yet so it can't know its value. redux-form doesn't work as standard form submit, it is all event driven, but, please correct me if I am wrong.

**Comment by samuelkaufman** [comment]
@danielrob 
> In general I would personally try to make my model be reflected in the view, rather than ever thinking about the view update the model on mount. If your model has defaults, set them in the initialValues and let that be reflected in the view.

I agree, but it seems wrong to me that you can have a form where the values as displayed on the screen are not the values in the form...

I think it's a fair assumption that a form framework would manage the state being in sync between the view and the model.

**Comment by escalepion** [comment]
it doesnt help that we resolve this with initialState if we use arrayfield. I need same thing exactly. In arrayfield of course. When i click the submit button, it must post initially first selection but i never get it if the user doesnt select it. But i need initial value.

**Comment by danielrob** [comment]
@samuelkaufman @escalepion 

> I think it's a fair assumption that a form framework would manage the state being in sync between the view and the model.

redux-form _is_ keeping the model and view in sync, but the default action of a select when no value matches an available option is to show the first option. You have to give the setup something to work with!

The OP needs to decide if a null value is truly acceptable for their select. If it is, then an empty <option /> is required to allow the view to meaningfully reflect the model. If it is not then an initial value needs to be provided, because that is the form state. 

Remember, actual DOM state doesn't magically affect the React model, events and component lifecycle's are what affect model changes.

**Comment by Skaronator** [comment]
This issue also apply to a checkbox. For example a remember me checkbox on login.

*1st Render**
`value: null`

*User click on the checkbox*
`value: true`

*user click on the checkbox again*
`value: false`

So 3 different states even if a checkbox only has 2 (checked or not checked)

**Comment by samuelkaufman** [comment]
@danielrob that's fair :)

So just to summarize:

Sounds like the official stance of redux-form should be:

* provide defaults for checkboxes/select boxes
_or_
* provide null states as the first option (ex: "City" )

If you do not, you're going to get unwanted behavior:
ie if you submit your form, your handleSubmit function will only get values that have triggered an onChange event.
