### ISSUE TITLE
On the Initializing From State example what is the purpose of initializeForm property?

### ISSUE THREAD

**Issue by jpierson** [erikras/redux-form#324]
On the [Initializing From State](http://erikras.github.io/redux-form/#/examples/initializing-from-state?_k=sxni9f) example what is the purpose of `initializeForm` property? It doesn't appear to be used anywhere.

**Comment by erikras** [comment]
Excellent observation and question. That's vestigial from an older way of doing it. I will remove it.

**Comment by dpiccone** [comment]
Is props.initializeForm going to be deprecated?

I see two different ways of initializing the form:

1. from the state like http://redux-form.com/5.2.5/#/examples/initializing-from-state?_k=sxni9f
2. from the props, by using 
```
componentWillReceiveProps(props) {
  let { name, initializeForm } = props;
  if (name) {
     initializeForm({ name });
  }
}
```
Personally I am using the second version because using props doesn't force the component to depend on specific part of the state by specifiying mapStateToProps.

**Comment by erikras** [comment]
> Is `props.initializeForm` going to be deprecated?

No. It's called [`props.initialize` in `v6`](http://redux-form.com/6.0.0-alpha.15/docs/api/Props.md/#-initialize-data-object-function-), though.
