### ISSUE TITLE
Way to set InitialValues from redux state values + use mapStateToProps props 

### ISSUE THREAD

**Issue by idangozlan** [erikras/redux-form#3251]
Hi,

Is there a way to set InitialValues from redux state values + use mapStateToProps props inside the form?

Thanks!

**Comment by cristianfraser** [comment]
`mapStateToProps` receives both the redux's `state` and the components `ownProps`.

You can have 

```
const mapStateToProps = (state, ownProps) => ({
   sth: state.something(ownProps.prop),
})
```

**Comment by idangozlan** [comment]
Can you explain the solution better? Can't understand how that information can help me...

**Comment by gustavohenke** [comment]
I think you're probably after the [Initialize from state](http://redux-form.com/7.0.3/examples/initializeFromState/) example.

Since this is a usage question, I'll close it. It's better to ask those in StackOverflow :)
In case you can lay out your issue better, showing your intention with some code, we may be able to help you here as well.
