### ISSUE TITLE
Input cursor/caret jumps to the end when component is stateful

### ISSUE THREAD

**Issue by weaintplastic** [erikras/redux-form#3253]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
There are some reports out there that dealing with the issue that the cursor/caret is jumping to the end of an input whenever text is entered somewhere in the middle or beginning.

I've set up a minimal use-case that demonstrates that behavior in relation to wether or not the custom component is handling an internal state. In this case the component keeps information in a state of the total characters left to type in order to display them next to the input component.

https://codesandbox.io/s/KGXD07rz

![](http://i.imgur.com/7nvvbrf.gif)

By commenting out line 21 in `components/Input.js` you can switch between a working and not working setup:

```
    this.setState({
      charsLeft: maxLength - event.target.value.length,
    });
```

### What is the expected behavior?
The expected bahavior is to persist the cursor position while typing. 

### Sandbox Link
https://codesandbox.io/s/KGXD07rz

### What's your environment?
redux-form 7.0.1
redux 3.6.0
react-redux 5.0.4
react 15.5.3
react-dom 15.5.3

Browser: Chrome (latest)
OS: Mac Os

### Other information
Related issue: https://github.com/erikras/redux-form/issues/2049

**Comment by wildex** [comment]
Did face the same issue on latest redux-form release

**Comment by gustavohenke** [comment]
I made `InputField` extend from `PureComponent` instead of `Component`, and the problem stopped happening:

https://codesandbox.io/s/xGjrrMZ8n

It seems like React wasn't able to keep the `input` DOM node after you typed 🤔 
I don't understand why this is the case, since the resulting DOM is the same, but it isn't an issue of redux-form.

---

@wildex, please open a new issue providing enough details.
