### ISSUE TITLE
Submitting without button and handleSubmit in component

### ISSUE THREAD

**Issue by JonathanWbn** [erikras/redux-form#3260]
I have simple form with two things I am doing differently from how the documentation suggests:
- submitting onBlur, no submit button
- handling the submit with the handler local to the component, not passed from the parent

This is my setup:
```
class SimpleForm extends Component {

  handleSubmit = () => {
    // my submit handler
  }

  render() {
    const { handleSubmit } = this.props;
    return (
      <Box alignSelf='center' margin={{ top: 'large' }}>
        <form
          onSubmit={handleSubmit(this.handleSubmit)}
          onBlur={() => this._form.submit()}
          ref={c => this._form = c}>
          <Field name='test' component={TextInput} />
        </form>
      </Box>
    );
  }

}
```

The problem with this implementation is, that the page refreshes on blur. Is there any way I can prevent the refresh or just another implementation to achieve the same thing?

**Comment by danielrob** [comment]
Please also raise a Stack Overflow issue, and add the link here. Once issues are closed here they tend to lose visibility, but Stack Overflow issues are never closed, and this helps others searching for similar issues :). 

Your form is refreshing because of a default post action to the server (native html behaviour). `handleSubmit` normally prevents this default behaviour. It think you may simply want to do: 

```
onBlur={handleSubmit(this.handleSubmit)}
```

**Comment by JonathanWbn** [comment]
That worked, thanks.

**Comment by danielrob** [comment]
Cool! You make me realise though I've never had to deal with `handleSubmit` intercepting the native form action which is what you were trying to have it do. I'll try to remember to report back once I know more on that :).
