### ISSUE TITLE
Can not get autofilled value in v6 and v7?

### ISSUE THREAD

**Issue by jaggerwang** [erikras/redux-form#3263]
### What is the current behavior?
Field autofilled by browser can not read in handleSubmit in v6.0.5. I googled a [post](https://medium.com/@dschmidt1992/auto-fill-with-redux-forms-9b51ad8ef962) to solve this problem, but only works for v5.

### What is the expected behavior?
Get the autofilled value in handleSubmit.

### What's your environment?
React: 15.1.0
Redux-Form: 6.0.5

**Comment by danielrob** [comment]
While [I'm sympathetic to this problem](https://stackoverflow.com/a/44961355/4682556), because reacts synthetic events not matching up with dom's synthetic events makes life tricky sometimes, I'm not convinced the issue your facing is a general problem. 

For example I am able to autofill http://redux-form.com/7.0.3/examples/simple/ without any issues.

**Comment by jaggerwang** [comment]
Yes, the simple example is ok. Maybe it's my usage caused.
