### ISSUE TITLE
Add an option to make SubmissionError keys case-insensitive

### ISSUE THREAD

**Issue by sajagi** [erikras/redux-form#3270]
### Are you submitting a **bug report** or a **feature request**?
Feature Request

### What is the current behavior?
Submit validation currently makes case-sensitive matching of SubmissionError keys and form fields. Certain frameworks (e.g. ASP.NET Core Web API) rely on (default) case-insensitivity when matching request data into the model (e.g. username would match Username) which respects different casing culture (camelCase in JavaScript vs PascalCase in C#). However, the differences in casing are not trivially revertible so the framework sends model validation errors back to the client using casing of the server model.

### What is the expected behavior?
An option passed to SubmissionError indicating whether or not the match to form fields should be case sensitive or not. (by default: case sensitive). 

### Sandbox Link
Just modify the returned key name (e.g. username) in submit() function to PascalCase and the validation won't display errors.

### What's your environment?
redux-form 6.6.8

**Comment by gustavohenke** [comment]
I'm strong against adding such complexity to the project, since case insensitive stuff is usually something from the Windows-world 🤔 

Can you give _any_ example of other JS libraries/frameworks that ignore case sensitivity?

**Comment by timhwang21** [comment]
Additionally, the developer is in control of the submit validation function. Can't you just convert casing there? For example, in the `submit.js` example [here](http://redux-form.com/7.0.3/examples/submitValidation/), just put the error message under a different key.

**Comment by sajagi** [comment]
@timhwang21 Sure, there are always workarounds (there is a workaround for pretty much anything, isn't there), the simplest probably being an inherited class to SubmissionError where it would probe for the forms' fields and modify the names accordingly. However it would be nice to have this functionality built-in since you'd probably have to pass in the form context. As far as I can tell this is the only feature because of which ASP.NET Web API doesn't work with redux-form out of the box.

@gustavohenke Sorry, I fail to see the logic that the idea should be rejected because Windows is involved. Blame those who created languages using anything else but camelCase (e.g. Python, C#) for object properties.

**Comment by erikras** [comment]
Rejecting this has nothing to do with any animosity towards Windows. Case sensitivity is a standard of the language we are writing in. Like it or not, we're stuck with only one language in the browser.

![erik node 2017-07-31 17-01-11](https://user-images.githubusercontent.com/4396759/28783831-df8801da-7611-11e7-9b40-4c1681980366.jpg)

Adding case insensitivity would increase complexity, bundle size, and execution time for _everyone_ just to better support one of dozens of server-side frameworks. And when the PHP folks come and ask for `snake_case` insensitivity? What if Ruby wants another form? I'm pretty sure there are no libraries that would implement this request.

If I were you, I would just use the PascalCase for your field names as well. It seems like that would solve your problems. If you've got existing front end code that is already using different case than what is on the server because the server is case insensitive, you're going to have a hard time whether or not you use this or any form library.

**Comment by timhwang21** [comment]
@sajagi I don't think it's a workaround. I think it's how submit validation is intended to be used. You have full control of the submit validation function. That's like saying "changing any options from `redux-form`'s default configuration is a workaround, `redux-form`'s defaults should support all my use cases."
