### ISSUE TITLE
Uncaught TypeError: (0 , _immutable.List) is not a function

### ISSUE THREAD

**Issue by binarykitchen** [erikras/redux-form#3274]
Looks like there is a bad import in 
https://github.com/erikras/redux-form/blob/master/src/structure/immutable/keys.js#L5

where this line

```js
import { Iterable, List } from 'immutable'
```

is not clear what it really imports. When compiled with babel, it looks like

```js
var _immutable = require('immutable');
...
var empty = (0, _immutable.List)();
```

where the variable `_immutable` seems to be an instance of something completely different.

Makes me wonder what `'immutable'` is really here? It's not listed in package.json either.

**Comment by binarykitchen** [comment]
Realised this happens when you do a `ReduxForm = require('redux-form/immutable')` which causes the above error.

Wondering how to require it the proper way??

**Comment by binarykitchen** [comment]
cc @danielrob

**Comment by binarykitchen** [comment]
ping?

**Comment by binarykitchen** [comment]
piiinngg?

**Comment by gustavohenke** [comment]
We don't list it in `dependencies` or `peerDependencies` because not all developers will depend on it.
It's up to the user to opt for the immutable variant of Redux Form.

However, you can see the dependency listed in the [immutable example](https://github.com/erikras/redux-form/blob/v7.0.3/examples/immutable/package.json).

**Comment by binarykitchen** [comment]
ugh, thats wasn't clear and obvious at all. and is nowhere documented.

can you at least print a warning or so?

and what dependency is needed exactly? immutable or redux-immutablejs?

at last, why not provide it in its own npm package?

cc @gustavohenke

**Comment by gustavohenke** [comment]
> thats wasn't clear and obvious at all. and is nowhere documented.

Isn't this explanation enough? http://redux-form.com/7.0.3/examples/immutable/

> can you at least print a warning or so?

Since the source is using the modules syntax (`import`/ `export`), it's not possible to use `if`s or `try`/ `catch` around it and log something about the `immutable` not being available.

> and what dependency is needed exactly? immutable or redux-immutablejs?

It should be `immutable`, since that's what imported, according to the code you pasted here.
But also the Immutable example above should give some hints as well...

Should we add further docs around this, @erikras, @danielrob?

> at last, why not provide it in its own npm package?

I think @erikras made the decision based on the popularity of React + ImmutableJS.

**Comment by binarykitchen** [comment]
http://redux-form.com/7.0.3/examples/immutable/ needs to mention that immutable and redux-immutable or redux-immutablejs must be in package.json. in total two packages must be added to make this work. furthermore also would highlight lines of package.json in that immutable example.

then i think it's also bad practice when a npm package requires another package to make this work but is not listed in package.json. it should be in its own package. imo this goes against the fundamental lego principle of modular software development.

**Comment by binarykitchen** [comment]
well, i managed to fix this myself. webpack v1.x messed up with the many different immutable versions, so i ended up adding an alias:

```js
    alias: {
      // because webpack cannot deal with peer dependencies well (known issue)
      immutable: path.join(rootPath, 'node_modules', 'immutable')
    }
```

and that resolved the error mentioned a top.
