### ISSUE TITLE
formValues' values seem one step behind in some cases

### ISSUE THREAD

**Issue by SBRK** [erikras/redux-form#3286]
I have a weird problem once again :D And I was not able to reproduce it in a simple CodeSandbox example, so I am not sure what is causing it in our code. 

To summarize, I have a part of my form that updates a value (via the props `change` method, if that matters), and another part that displays that value, via `formValues`. Both are encapsulated in a `FormSection` (with `name='my_array[0]'`). When I update the value, the `formValues` component gets updated with the previous value. 

For example: 
Initial value is `null` => `formValues` value is null
I update the value from `null` to `foo` => nothing happens
I update the value from `foo` to `bar` => `formValues` value gets updated to `foo`
I update the value from `bar` to `toto` => `formValues` value gets updated to `bar`

I tried reproducing the problem in CodeSandbox but wasn't able to, so the problem is probably coming from somewhere in our code, but I don't know where, and I hope someone here can give me indications on what to look for, or better, maybe someone had this very problem and solved it :)

**Comment by SBRK** [comment]
Got it ! And the problem I had on #3228 is very likely the same cause.

I tracked down the problem to the `context` updating with the wrong `values`, because I was calling `change` in a `componentWillReceiveProps`.

What happened was that an update on the store (unrelated to the form) would trigger `reduxForm` to update its values, triggering a cascade of `context` update for all its descendants, among which, the component where I called `change`. I would then call `change`, which would update the store, but the process of updating all of the childrens' context was still ongoing, with `values` corresponding to the previous state. I added a `setTimeout` to my `change` and the problem is solved. I should probably move it to `componentDidUpdate` instead.

**Comment by jedwards1211** [comment]
@SBRK thanks, you saved me a lot of time.

The sad thing is I've probably had this issue and solved it before and I forgot what the deal was...I wonder if we could implement better dev warnings.

**Comment by mbixby** [comment]
In my case, `mapStateToProps` in `formValues()` was evaluating *before* `mapStateToProps` in `reduxForm()` because I was accidentally passing `store` as a prop to reduxForm().

When `connect()` receives `props.store`, it will use that prop instead of `context.store`. Connect will then create an independent subscription tree – two `connect`s using props.store and context.store will be using different subscriptions. Subscription is what dictates order of mapStateToProps evaluation, so the two `connect`s here will be called in undefined order regardless of where they are in React component tree:
```javascript
// parentSub's source should match where store came from: props vs. context. A component
// connected to the store via props shouldn't use subscription from context, or vice versa.
var parentSub = (this.propsMode ? this.props : this.context)[subscriptionKey];
this.subscription = new Subscription(this.store, parentSub, this.onStateChange.bind(this));
```
For me it was a little unexpected. If the stores are equal it shouldn't matter whether they are coming from props or context.
