### ISSUE TITLE
initialValues doesn't update after being passed an empty Object

### ISSUE THREAD

**Issue by lifeiscontent** [erikras/redux-form#3302]
### What is the current behavior?

if the initial state of initialValues is an empty object, the redux-form stops looking for changes from its parent, however if its `undefined` it continues to listen.

### What is the expected behavior?

when the action is dispatched, the initial values are rendered properly

### Sandbox Link
https://codepen.io/lifeiscontent/pen/NvjaGz

### What's your environment?

Tested on Chrome with the versions used within the sandbox link

**Comment by tstirrat15** [comment]
This is an incorrect use of initialValues. If you want the behavior that you're describing, you need to set the `enableReinitialize` flag in the `reduxForm` configuration. Otherwise, `initialValues` are set the first time that the form is rendered and then cannot be modified.

However, be warned that enabling reinitialization will bring on a whole bunch of correct but somewhat unintuitive behaviors around `pristine`/`dirty` and friends.
