### ISSUE TITLE
Typescript usage - SubmissionError

### ISSUE THREAD

**Issue by JozefBiros** [erikras/redux-form#3346]
Hello, I am using redux-form with Typescript.
I cannot figure out how to correctly use SubmissionError with typescript.

When I try using Submission error as is stated in docs:
```
throw new SubmissionError({  _error: 'Login failed!' })
```
Typescript will throw this error: 
```
Argument of type '{ _error: string; }' is not assignable to parameter of type 'void'.
```

Without typescript it is working just fine. 

So problem lies in type definition in @types/redux-form:
```
export interface SubmissionErrorConstructor<T = void> {
    new (errors?: FormErrors<T>): Error;
}

declare const SubmissionError: SubmissionErrorConstructor;
```
or my incorrect usage.

What am I doing wrong or how to correctly use SubmissionError with Typescript?

**Comment by gustavohenke** [comment]
I *think* the problem is with the `SubmissionErrorConstructor` interface - it specifies a generic `T = void` 🤔 
Try playing with this interface a little bit, see if you can find a solution, and let us know.

Since we don't officially support TypeScript, the fix must be done in the [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redux-form), and submitted for approval in that repository as well.
