### ISSUE TITLE
[bug] Destroy prop throws error when called

### ISSUE THREAD

**Issue by jarekb84** [erikras/redux-form#3365]
### What is the current behavior?
Calling the destroy prop throws a console error and does not destroy the redux state for the current form.

Console error
 Uncaught TypeError: path.lastIndexOf is not a function
   at deleteInWithCleanUp  #(deleteInWithCleanUp.js:34)

### What is the expected behavior?
Redux state is destroyed for the current form.

### Sandbox Link
https://codesandbox.io/s/9zjj15zqkw

Click on "Load Account" then click "Destroy Redux state"

### What's your environment?

redux-form v7.0.3, node 6.11.1, OSX/Chrome 60

### Other information
Have destroyOnUnmount: false and keepDirtyOnReinitialize: true
Using Immutable JS

**Comment by kgregory** [comment]
@jarekb84 I don't see any reference to the destroy prop in your linked example.

**Comment by jarekb84** [comment]
@kgregory Updated the link, musta not saved/forked my example correctly.

**Comment by kgregory** [comment]
This is happening because you're setting the destroy prop as the onClick handler:

```
<button type="button" onClick={destroy}>Destroy Redux state </button>
```

onClick will pass parameters to its handler, which are in turn being passed to destroy.  The destroy prop accepts parameters, you can name forms that should be destroyed.  Since the event object is not a set of valid form names, you're getting a console error.

You should avoid directly assigning event handlers in this fashion and invoke functions that dispatch actions from within another function, so that you can control what they receive:

```
<button type="button" onClick={() => destroy()}>Destroy Redux state </button>
```

Pretty sure this one can be closed @erikras

**Comment by jarekb84** [comment]
@kgregory yup, that fixed my issue.
