### ISSUE TITLE
Flow error: ComponentType. Property not found in exports of "react"

### ISSUE THREAD

**Issue by davidroeca** [erikras/redux-form#3390]
### Bug Report
Based on the updates from 7.0.3 (working) -> 7.0.4 (failing), my flow type checks are breaking

### What is the current behavior?
In my current application
```bash
$ npm run flow
No errors!
```

### What is the expected behavior?
In my current application
```bash
$ npm run flow
...
Error: node_modules/redux-form/lib/index.js.flow:204
204: ): { (React.ComponentType<*>): React.ComponentType<*> }
           ^^^^^^^^^^^^^^^^^^^^^^ ComponentType. Property not found in
  2: import * as React from 'react'
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ exports of "react"

Error: node_modules/redux-form/lib/index.js.flow:204
204: ): { (React.ComponentType<*>): React.ComponentType<*> }
                                    ^^^^^^^^^^^^^^^^^^^^^^ ComponentType. Property not found in
  2: import * as React from 'react'
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ exports of "react"
```

### What's your environment?

Linux Mint 18.2
flow-bin 0.51.1

redux-form:
Expected: 7.0.3
Current: 7.0.4

**Comment by davidroeca** [comment]
Actually realizing that this requires `flow-bin` updates so I'm closing

**Comment by IanVS** [comment]
It's a shame that I'm not going to be able to update to new versions of this library simply because I'm stuck on an older version of `flow-bin`.  Perhaps the old (`7.0.3`) definitions can be put into [flow-typed](https://github.com/flowtype/flow-typed/issues/1151) for older flow-bin versions and maybe that'll work?  I'm not sure there are any other good ways to maintain types within a project that can be consumed by multiple versions of flow, but I'd love to hear about it if there are.

**Comment by erikras** [comment]
>  I'm not sure there are any other good ways to maintain types within a project that can be consumed by multiple versions of flow, but I'd love to hear about it if there are.

Yeah, I don't think there are. Even if you did update `flow-typed`, it's not obvious to me if/how you could override the types in the library itself. Sorry...

**Comment by IanVS** [comment]
>it's not obvious to me if/how you could override the types in the library itself.

I believe I could just add `node_modules/redux-form` to the `[ignore]` section of my `.flowconfig`, and then flow would fall back to `flow-typed`.
