### ISSUE TITLE
Field Level Validation is not working properly if we create the same field again.

### ISSUE THREAD

**Issue by knnemade99** [erikras/redux-form#3403]
Hi,
To generate my issue Please follow these steps: 
1. Go to https://codesandbox.io/s/4jlmw7099w  link
2. Now without giving any value click on Submit It will give required error on 'abc' field.
3. Change the value of username to 1, a new abc field will be shown and previous field will be hidden.
4. Now click on Submit button, it will submit the form without giving required error for 'abc'.
5. It should give required error because I provided the required constant to that field's validation.

Please help me with this problem ASAP.

Thanks in advance.

**Comment by ClementParis016** [comment]
It doesn't work because the form has been initialized with the original field you removed and it doesn't know the new field you added should replace the previous one.

I think what you're looking for is a [FieldArray](https://redux-form.com/7.0.4/docs/api/fieldarray.md/), which handles dynamic fields creation/removal.

**Comment by danielrob** [comment]
Closing question due to non-response.
