### ISSUE TITLE
Should you reduxForm() then connect() or the opposite?

### ISSUE THREAD

**Issue by ClementParis016** [erikras/redux-form#3424]
I'm not sure if the order of calling `reduxForm()` and `connect()` functions has any sort of importance, but the current docs (v7.0.4) aren't clear about this aspect.

In "Examples / Initializing from State" we are calling `reduxForm()` before `connect()`:
https://github.com/erikras/redux-form/blob/fdc7f1d2eaf2a243d399adc0ffeaeee55103a11c/examples/initializeFromState/src/InitializeFromStateForm.js#L119-L132

and in "FAQ / How do I mapStateToProps or mapDispatchToProps?" we do the opposite:
https://github.com/erikras/redux-form/blob/fdc7f1d2eaf2a243d399adc0ffeaeee55103a11c/docs/faq/HowToConnect.md
```js
Example = connect(
    mapStateToProps,
    mapDispatchToProps
)(Example);

export default reduxForm({
    form: 'example' // a unique name for this form
})(Example);
```
I stumbled upon this because I was wondering "but, what if I need both initalizing from state and mapDispatchToProps?".

I think it makes more sense to call `connect()` after `reduxForm()` as it has the benefits of being able to dispatch custom actions on custom props (other than `onSubmit` for example), while still permitting to set initial values from state.

I can update the docs if needed.

**Comment by gustavohenke** [comment]
That's a quite subjective question 😃, and the answer to it is **It Depends™**

First of all, I want to have one thing clear:

> In "Examples / Initializing from State" we are calling reduxForm() before connect():

There's a confusion here.

The `reduxForm()` decorator is, indeed, called first.
However, its result is passed as an argument to `connect()`. So what gets rendered by React is first the `connect()`ed component, then the `reduxForm()`ed component, then the form component!

---

So, answering from my point of view:

**Do you need to set `initialValues` or `onSubmit`, etc?**
Decorate your component with `connect()` before `reduxForm()`.
Otherwise, redux-form won't see your props.

**Do you need to use redux-form state and/or props to deal with your own reducer's data?**
Decorate your component with `reduxForm()` before `connect()`.

**Do you need to pass any props that are not related to redux-form?**
Decorate your component with `connect()` before `reduxForm()`.
This is simply because I'm usually sure that my state is not going to change as much as the form's state.
It's a minor performance mindset 🐎 , won't affect the good use of the component.

I hope this helps you :)

**Comment by ClementParis016** [comment]
That's a clear answer, thank you :)

**Comment by artnos** [comment]
This should be in the documentation. I had to figure this out the hardway.

**Comment by mtg5014** [comment]
OK...I know this is closed but I've just run into this issue and have a question about @gustavohenke 's answer above:

Do you need to set initialValues or onSubmit, etc?
Decorate your component with connect() before reduxForm().
Otherwise, redux-form won't see your props.

Do you need to use redux-form state and/or props to deal with your own reducer's data?
Decorate your component with reduxForm() before connect().

....what if we need both?

I will save my explanation for why for the conversation, but this seems like a hole for my use case...

Thanks in advance!

**Comment by gustavohenke** [comment]
Hi @mtg5014 [I answered your question on StackOverflow](https://stackoverflow.com/a/48534735/2083599) with the same advice:

You can probably wrap your component with `connect` as many times as you wish -- it should work just fine.
