### ISSUE TITLE
getFormValues(form)(state, 'field') with Immutable return a Map instead of value

### ISSUE THREAD

**Issue by filipposarzana** [erikras/redux-form#3440]
### What is the current behavior?
Using `getFormValues(form)(state, 'field')` inside my selector is undefined since no value has been typed on input but after I type something it returns a `Map` with `'field'` as `key` 
```
{field:value}
```

### What is the expected behavior?
I expect to act like `formValueSelector(form)(state, 'field')` that returns the value of `field` inside the `form` specified in selector

### What's your environment?

Redux `v7.0.4`
All OS
Node `v8`

**Comment by dapids** [comment]
Hi, any news on this? I and my teammates are using `formValuesSelector` for such purpose, but it's not documented so we don't know whether it's the best choice or not.

Thanks,
David

**Comment by developer239** [comment]
https://redux-form.com/7.0.4/docs/api/formvalueselector.md/

What I would like to know is why the heck is selecting form values so complicated? There is no way that one more prop would have killer impact on final form component performance.

I mean why not doing something like this? `this.props.fields[fieldKey]`

Instead of all the connect, form values selector clutter...

Or at least let me specify what fields do I need to access when creating the form.

**Comment by filipposarzana** [comment]
Thanks @developer239 but I can assure you this doc wasn't there at the time :+1:
