### ISSUE TITLE
Feature Request: validators like angular4, easy to set and get errors

### ISSUE THREAD

**Issue by webmobiles** [erikras/redux-form#3451]
I was looking for a field level validation in the oficial site:

https://redux-form.com/7.0.4/examples/fieldlevelvalidation/

But it's seems very manual , is there something more automatic ? or any other library that matchs good with react-form ? something like Validators in angular? 

in Angular4 is very easy to define validations (there is a library validators), with an array of validators:

```
`ngOnInit(): void {
  this.heroForm = new FormGroup({
    'name': new FormControl(this.hero.name, [
      Validators.required,
      Validators.minLength(4),
      forbiddenNameValidator(/bob/i) // <-- Here's how you pass in the custom validator.
    ]),
    'alterEgo': new FormControl(this.hero.alterEgo),
    'power': new FormControl(this.hero.power, Validators.required)
  });
}`
```

then is very easy to find type errors trought an objects,  for a Validators.required , error is define in 'field.errors.requerid' object:

`<div *ngIf="name.invalid && (name.dirty || name.touched)"
     class="alert alert-danger">

  <div *ngIf="name.errors.required">
    Name is required.
  </div>
  <div *ngIf="name.errors.minlength">
    Name must be at least 4 characters long.
  </div>
  <div *ngIf="name.errors.forbiddenName">
    Name cannot be Bob.
  </div>
</div>`

source:
https://angular.io/guide/form-validation

**Comment by blord-fullscreen** [comment]
In React it's generally considered bad practice to define new functions inside of render, because they will often trigger unnecessary re-renders. As of redux-form 7, you will need to define your validation functions externally. The advantage is that it allows them to be reused. For example, what if you have another component that also wants to forbid the name "Bob"? You now have to define that validation function twice. A hardcoded check like this can easily be moved out of render, where it belongs. Instead, create a validation module and import from it. It may seem odd and more "manual" at first, but this is the right way to do it in React.

Take a look at #3288, especially https://github.com/erikras/redux-form/issues/3288#issuecomment-320729482

**Comment by webmobiles** [comment]
that is typescript , not js, so it's a  class, so i don't think the function is defined a render, valdator in angular4 is really an external function, but you don't need to write validations by hand, it's like wallmart validator https://github.com/hapijs/joi
I've just to do know if there a library that i can use together with react to validate the most of common validations... maybe not, it's not an idea with redux form? any way if i write my validation in functions is better to do all by hand? i 've just wanted to know that, in this case i wont to look for an external library, and i will start to write functions to  do my own validator library..

**Comment by webmobiles** [comment]
what about this?
https://github.com/johanetox/redux-form_validate
think you it's something that can match ?

**Comment by blord-fullscreen** [comment]
I haven't used joi-browser. For me the file size is too large.

It might be nice to see a small library of functional validation patterns. Because the validations I use are so simple, and I want the bare minimum of file size, I just write it myself, e.g.

```
export const validateNoEmpty = inputStr =>
  (inputStr === '' || inputStr === undefined ? 'Required.' : undefined);

export const validateNoLeadingSpaces = inputStr =>
  (/^\s+/.test(inputStr) ? 'No leading space characters allowed.' : undefined);

// Checks with arguments are prebuilt:
const validateMinValue = minNum => inputStr =>
  (parseFloat(inputStr) < minNum ? `Must be at least ${minNum}.` : undefined);

export const validateMin5 = validateMinValue(5);
```

It all works. Just don't expect Angular syntax to work in React!

**Comment by webmobiles** [comment]
thanks, so it's like the oldies days when i use to create my javascript validate functions, but this time JS is much better ! thanks for your advise

**Comment by gustavohenke** [comment]
Can I also suggest [revalidate](https://github.com/jfairbank/revalidate)?
