### ISSUE TITLE
Support auto-redirect to most current documentation on website

### ISSUE THREAD

**Issue by ntomallen** [erikras/redux-form#3472]
I'm not sure if this is the correct place for this issue. Essentially, google has cached old API versions of the documentation, so when searching google for `redux form values`, the top result is to this [out of date documentation.](https://redux-form.com/6.0.0-rc.1/examples/selectingformvalues/) This happens with basically anything I search for through google, so I'm always having to go back to the home page of the redux-forms website and trying to manually find the documentation. In all, it's just a pain to navigate.

Ultimately, it'd be nice if the website supported the multiple versions of the documentation better. For instance, everything should auto-redirect to the most recent API so that it's easier to find the most relevant information. Then, one could choose which API version to view if they need a different one. A good example of this is the [Laravel documentation](https://laravel.com/docs/5.5/installation), which includes a drop-down in the top-right corner to select the correct API version.

**Comment by erikras** [comment]
This is why I created a warning when you are looking at the docs pages. Unfortunately, it's too much work to go back and install it in every single old example. A redirect is also not the right answer, because sometimes someone might _want_ to look at old docs or examples. It's not an ideal situation, I know. 😦

![redux form - reduxform 2017-10-06 11-55-12](https://user-images.githubusercontent.com/4396759/31273018-4b1313d6-aa8d-11e7-9f94-f6213ee40d9a.jpg)
