### ISSUE TITLE
TypeError on immutable getFormValues

### ISSUE THREAD

**Issue by erin-doyle** [erikras/redux-form#3488]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

See sandbox link below for demo.

Importing getFormValues like this:

```javascript
import { getFormValues } from 'redux-form/immutable';
```

and then using like:

```javascript
const formValues = getFormValues(NEW_ITEM_FORM_NAME)(state);
```
throws the TypeError.

### What is the expected behavior?
An error is not thrown.

### Sandbox Link

https://codesandbox.io/s/1zp260qo6l

### What's your environment?

redux-form v7.1.0 (7.0.4 does not exhibit this issue)
Mac OSX 10.11.6
react and react-dom v15.6.1
Issue discovered running Jest tests

### Other information

Error stacktrace:
```node
TypeError: (0 , _immutable.isCollection) is not a function

    at getIn (/Users/edoyle/Development/storefront/node_modules/redux-form/lib/structure/immutable/index.js:42:40)
    at nonNullGetFormState (/Users/edoyle/Development/storefront/node_modules/redux-form/lib/selectors/getFormValues.js:11:16)
    at /Users/edoyle/Development/storefront/node_modules/redux-form/lib/selectors/getFormValues.js:13:20
```

**Comment by jmtoung** [comment]
I'm getting the same issue - 7.0.4 does not observe this issue but 7.1.0 does.

**Comment by ryancurtin** [comment]
Which version of immutable.js are you using?  I was able to fix this issue by upgrading to 4.0.0-rc.7.

**Comment by erin-doyle** [comment]
I was using immutable version 3.8.1.  It does look like updating to version 4.0.0-rc7 fixes the issue in the sandbox I created.

**Comment by erikras** [comment]
Oh damn, right. So `v7.1.0` migrated to `v4.0.0-rc.5` of Immutable (because of React 16 flow issues), which renamed `isIterable()` to `isCollection()`. It's kind of impossible to support breaking changes in a third party library. Perhaps I did jump the gun a little bit in using an RC of Immutable, and for that, I apologize. But everyone using Immutable is going to need to migrate to `v4` eventually. So if you need to still use `v3` of Immutable, you should not yet upgrade to `redux-form@7.1.0`.
