### ISSUE TITLE
clear conditional fields when unselected

### ISSUE THREAD

**Issue by terencechow** [erikras/redux-form#3540]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
upon selecting a field that conditionally renders more fields, changing that initial field should remove the conditional field values.

See the example link. Click hasEmail and type some email. Now unclick hasEmail. the email value is saved in the form despite it no longer existing. 

### What is the expected behavior?
when a field doesn't exist in redux-form it is removed from the state

### Sandbox Link
https://redux-form.com/7.1.1/examples/selectingformvalues/

### What's your environment?
redux-form 7.1.1

**Comment by gustavohenke** [comment]
That is a quite controversial behaviour of Redux Form...

There are folks that defend one may want to include unmounted fields in the submission, others don't.
Since this is pretty much the case of the link you mentioned, I'll just say that this case can be fixed by nullifying the other field when a change happens.

I'm closing this issue for now, but feel free to continue the discussion!
