### ISSUE TITLE
disable punycode

### ISSUE THREAD

**Issue by thomaspersson** [erikras/redux-form#3593]
When using Swedish characters like "å, ä or ö" in a text field, they get decoded to punycode, eg xn--5ca.

As default I expect that what I type get's saved and if I would want punycode I would opt-in or do a custom parsing myself. Can't find anywhere in the documentation on how to disable this.

**Comment by erikras** [comment]
All Redux Form does is take the value from `event.target.value` from the [`SyntheticEvent`](https://reactjs.org/docs/events.html), so that's likely your browser doing that conversion.

Redux Form gives you _complete_ control over the [value lifecycle](https://redux-form.com/7.1.2/docs/valuelifecycle.md/), so if you want to encode and decode the values as they are passed to and from the input, you can do that.

**Comment by erikras** [comment]
Also, thanks for introducing me to punycode. I'd never heard of it. 👍

**Comment by ernani** [comment]
No pun intended! +1

Off Topic: Doesn't Danish have umlauts or chars like that? I've thought so!

**Comment by thomaspersson** [comment]
Thanks, located issue to Chrome so will continue my search there :)
