### ISSUE TITLE
add fields's onChange callback

### ISSUE THREAD

**Issue by joehua87** [erikras/redux-form#362]
Thank you very much for this awesome library...
I've faced the problem like https://github.com/erikras/redux-form/issues/330
So I think it's better to add callback to field's onChange.
I've implement in:
* https://github.com/joehua87/redux-form/blob/master/src/events/createOnChange.js
* https://github.com/joehua87/redux-form/blob/master/src/events/__tests__/createOnChange.spec.js

**Comment by erikras** [comment]
Even if `onChange` did support this, _you still couldn't call `handleSubmit()` in your callback_ because the data won't have filtered down through the props yet. What does this accomplish?

**Comment by joehua87** [comment]
:( Sorry for the wrong code.

I want to submit the form when the field's value changed.
Currently I'm using like this:
```javascript
onSubmit(event, field) {
  if (field) {
    field.onUpdate(event);
  }
  const {submit, handleSubmit} = this.props;
  handleSubmit((data) => {
    if (field) {
      data[field.name] = event.target.value;
    }
    submit(data);
  })();
}
```
The JSX:
```jsx
<Input  {...sort}  onChange={(event) => this.handleSubmit(event, sort)}>
Button onClick={this.handleSubmit.bind(this)}>Search</Button>
```

**Comment by erikras** [comment]
I think you are correct in identifying the main problem being with validation, as `handleSubmit()` is only going to have the old data for validation. But that's a problem with your current solution as well.

**Comment by joehua87** [comment]
Many thanks for answer :)

**Comment by kyleboyle** [comment]
I've used the below code to submit the form whenever a field changes without tinkering with the fields themselves.
```
  componentWillReceiveProps(nextProps) {
    if (nextProps.dirty && nextProps.valid) {
      let doubleDirty = false;
      Object.keys(nextProps.fields).forEach(key => {
        if (nextProps.fields[key].value !== this.props.fields[key].value) {
          doubleDirty = true;
        }
      });
      if (doubleDirty) {
        nextProps.handleSubmit();
      }
    }
  }

```

**Comment by joehua87** [comment]
:+1: Thank you @kyleboyle

**Comment by slangeberg** [comment]
@erikras - I am needing to track deltas for form submit, so we don't submit the entire blob. Is @kyleboyle 's approach the best way to deal with that for now? Thank you so much. Great library, so far!

**Comment by erikras** [comment]
Oh, I've got traversal logic all over the place. :-) But nothing that does this precise thing. Seems like it wouldn't be too hard to make a cousin of [`getValuesFromState()`](https://github.com/erikras/redux-form/blob/master/src/getValuesFromState.js) that only returned the dirty values.

**Comment by atwam** [comment]
Tried this approach, I am getting issues because calling nextProps.handleSubmit() makes it propagate a "touch" on all inputs, which in turns re-updates the props of everything (and I can't use `props.submitting` because my submit function isn't a promise, so the prop isn't set).
Haven't figured a way to avoid that, not for the lack of trying.

I am starting to think that it wouldn't be too bad to be able to provide a callback that would be called after any value change, have a `onChange` config parameter the same way we are able to provide `onSubmit`.

Another approach I have tried is to just use the `asyncValidate`, but it feels wrong and I hit a bug (should raise an issue for that), where `asyncValidate` checks whether a field belongs to `ayncBlurFields` config using its "actual" name, which fails with dynamic fields : One would have to provide `children[0].name`, `children[1].name` etc etc in `asyncBlurFields` if one want to async validate all the `children[].name` fields.

So, back to step one, I like your approach but end up having an infinite loop.

**Comment by kyleboyle** [comment]
@atwam the double dirty check is suppose to stop the recursion. Is your onSubmit function throwing an uncaught exception? I've found that will cause an infinite loop. Also you'll have to verify that the dirty check is working for dynamic / nested fields, I haven't tested that.

**Comment by atwam** [comment]
@kyleboyle Indeed, it seems to improve once I removed the call to my submit function through handleSubmit
If find it's actually easier for me now to use `this.save()` rather than `this.props.handleSubmit()`, bypassing redux-form altogether, given I only get this `save` method called once everything is valid anyway.

**Comment by freen** [comment]
@kyleboyle's solution didn't work for me. When I call `nextProps.handleSubmit();` inside `componentWillReceiveProps`, I get the issue described by #190: `You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop`.

Whereas I declared the form tag as documented: `<form onSubmit={handleSubmit(submit)}>`, where `submit` is my custom handler, passed down from my form container.

I'm running 5.3.1.

**Comment by freen** [comment]
Described the same issue here: http://stackoverflow.com/questions/38902221/redux-form-trigger-form-onsubmit-after-input-onchange

**Comment by kyleboyle** [comment]
@freen I was using redux 3.5.1, so the api may have changed. I think the principle still applies you just have to figure out the right way to invoke the handleSubmit, I am no longer using this approach in my app so can't go back to verify. did you try `handleSubmit(submit)`?

**Comment by oyeanuj** [comment]
@kyleboyle @freen @atwam Where did y'all end up with for this case on v6?

**Comment by freen** [comment]
@oyeanuj I'm using 5.3.1 --- can't speak to 6.
