### ISSUE TITLE
Problem with dynamically constructed validation function

### ISSUE THREAD

**Issue by smashercosmo** [erikras/redux-form#3646]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
I'm trying to use validation function, that is dynamically constructed during render phase. I need it to check, that field value is equal to another field's value. This doesn't work. However static function works perfectly.

### What is the expected behavior?
I guess it should work, unless I'm doing somethingg wrong

### Sandbox Link
Here is the sandbox link https://codesandbox.io/s/4xvj31y174

### What's your environment?
Redux-Form v7.2.0

**Comment by ancestorak** [comment]
The value of `validate` props should not change between renders as it causes the field to be re-registered. In your example you should call `createEqualityValidator` outside of the component so that you don't create a new instance each time.

If for some reason you can't create the validation function statically, you can still call `createEqualityValidator` during render as long as you [memoize](https://lodash.com/docs/4.17.4#memoize) the result.

**Comment by smashercosmo** [comment]
@ancestorak thx for the explaination
