### ISSUE TITLE
Low perfomance

### ISSUE THREAD

**Issue by isergey** [erikras/redux-form#371]
In Simple form example http://erikras.github.io/redux-form/#/examples/simple?_k=52ex5m , when hold button in field over time (filling symbols), drawing starts to slow down. Why?

**Comment by xcatliu** [comment]
I tried redux-form in my own project, it was obvious that performance problem only appeared when I enable `redux-devtools`, so I think it's not a `redux-form` issue.

**Comment by erikras** [comment]
This is most likely due to the `redux-devtools` running on the demo site, which is saving a back catalog of every action dispatched and rerunning every one on every action dispatched. `redux-form` is much more performant in production. e.g. [Here is a page](https://react-redux.herokuapp.com/survey) running it without the devtools.

**Comment by isergey** [comment]
Many thanks for answers!
