### ISSUE TITLE
Optional configuration props are not included in exported propTypes

### ISSUE THREAD

**Issue by mk0x9** [erikras/redux-form#3873]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Configuration props are being bypassed to wrapped component. `forbidExtraProps` from `airbnb-prop-types` emits error in console for bypassed `onSubmit` and `onSubmitSuccess` props. _Also looks like `clearFields` and `clearSubmitErrors` should be declared in `src/propTypes.js`_

### What is the expected behavior?
Config props shouldn't be bypassed to wrapped component.

### Sandbox Link
https://codesandbox.io/s/p33y2z3z3x

### What's your environment?
redux-form@7.2.3
google chrome@64.0.3282.186

**Comment by danielrob** [comment]
This only matters if you specifically want to use something like `forbidExtraProps` in which case you probably can easily specify as the developer which optional props you want to verify against (you probably want to). 

It's my guess this is largely intentional/not particularly desired. If you'd like it please raise a PR and see what the response is.
