### ISSUE TITLE
Calling Field's input.onChange(undefined) does not set field value to undefined.

### ISSUE THREAD

**Issue by tnrich** [erikras/redux-form#3946]
Hey there, 
I'm trying to reset a form field to be `undefined` but it doesn't seem to work. Here is a codesandbox showing it not working: 

https://codesandbox.io/s/5w72x5rpmx

It does work passing `null`, but I am confused why `undefined` doesn't work. I couldn't find any mention of why this would be the case in the docs but maybe I missed something. 

Besides this behavior being confusing, I would especially love it to be set to `undefined` (and not `null` or `false`) in my case because I often set certain default values for my form values using the 
```
const {input: {value = "hey"}} = this.props
```
Which only works if the value gets reset to `undefined`.

Thanks!

**Comment by Olliebaba** [comment]
Is there a specific reason you want it to be `undefined` instead of an empty string? Technically `null` is a value, so I'm not sure that's actually what you're looking for. 

This kinda gets weird when comparing fields which were defined in `initialValues` vs fields which were not defined (or when not including initial values all together.) [See here.] (https://github.com/erikras/redux-form/issues/3366) Sounds like this is going to be updated in v8.

What's worked best for me is to assign an empty string when I want to act like something doesn't have a value. [Here's an example of it working.](https://codesandbox.io/s/4299yk4y30)

One thing to note in my example is that I applied a unary to the inc/dec buttons so they cast the empty string to a 0 when doing addition.

**Comment by tgreen7** [comment]
@Olliebaba Destructuring default values only work when the value is undefined. For example sometimes in my app I have a form value getting defaulted to an empty array and then use logic like array.length. Currently I can't unset that value because onChange with undefined doesn't work and if I did an onChange with null then that value would not be defaulted to an empty array and my app crashes.

**Comment by Olliebaba** [comment]
@tgreen7 - I'm not sure what you're referring to. Could you make a sandbox example of what you're describing?

**Comment by tgreen7** [comment]
@Olliebaba I recreated it using formValues and the change function (I was having trouble getting a field to store an array). https://codesandbox.io/s/0nzq9x5m0

**Comment by tgreen7** [comment]
here is the line that is causing the issue https://github.com/erikras/redux-form/blob/de8beb08e888f99c30753fee93768c4e7e0788c3/src/createReducer.js#L234

**Comment by rdsedmundo** [comment]
I'm with the same problem.

**Comment by renato-bohler** [comment]
Same problem here.

In [redux-form-input-masks](https://github.com/renato-bohler/redux-form-input-masks), we use `normalize` to create input masks, and we've been returning an empty string to clear the `Field`'s value to `undefined`, but this behavior is detailed on the [docs](https://redux-form.com/7.3.0/docs/api/actioncreators.md/#-code-change-form-string-field-string-value-any-code-).

Also, using empty string to clear the `Field` will not work if the input has an initial value. This is some odd behavior: why should the initial value determine how the change action behaves for empty strings? This is caused by the line of code below:

https://github.com/erikras/redux-form/blob/a97606fee0ed365903fff80cc93956fe2313a3ce/src/createReducer.js#L232

I'm okay with empty string setting undefined on the `Field`'s value, but from the user's perspective it just makes no sense that initial value would play a role in this case.

**Comment by negebauer** [comment]
I'm also having a problem with the inconsistent behavior. The `initial === undefined` makes it so that there's always a value for a field, even when you don't want it.

My use case is the following

- I have a various fields `foo.bar1`, `foo.bar2` in the form
- Each field can be selected and deselected, which changes it's value from `{}` when selected to `''` when deselected, using `onChange(value ? '' : {});`
- When submitting, the form `values` only include the fields that are selected (whose value is `{}`), fields that had a `''` value are not in the `values` object passed to `onSubmit`

The `CHANGE` actions trigger when clicking on each field in this way

- When the field isn't selected (value is `''`)
```js
{
  type: '@@redux-form/CHANGE',
  meta: {
    form: 'foodForm',
    field: 'features.alcohol',
    touch: false,
    persistentSubmitErrors: false
  },
  payload: {}
}
```

- When the field is selected (value is `{}`)
```js
{
  type: '@@redux-form/CHANGE',
  meta: {
    form: 'foodForm',
    field: 'features.alcohol',
    touch: false,
    persistentSubmitErrors: false
  },
  payload: ''
}
```

Which results in the following diffs to the state respectively

```js
{
  form: {
    values: {
      foo: {
        bar1: {}  // foo bar1 key is added with {} value
}}}}
```

```js
{
  form: {
    values: {
      foo: {}  // foo bar1 key is removed
}}}
```

But if I pass `initialValues` to the form this behavior is broken, it triggers the same `CHANGE` actions, but the diff of the second one results with a state of:

```js
{
  form: {
    values: {
      foo: {
        bar1: ''  // foo bar1 key is still present with '' as it's value
}}}}
```

When the intended behavior is for `bar1` to be removed from the form values

**Comment by tnrich** [comment]
I put in a PR for this here: https://github.com/erikras/redux-form/pull/4441

**Comment by tnrich** [comment]
That previous PR had issues because all tests were failing on master so I remade the PR against the latest version of master.

**Comment by skindc** [comment]
Hi, Do you know when this will be released? This will solve a very annoying problem of mine being able to reset a select component

**Comment by iamandrewluca** [comment]
This week should be released I think.

**Comment by skindc** [comment]
> This week should be released I think.

Great, thank you for your quick response.

**Comment by renatoagds** [comment]
Published in [`v8.2.6`](https://github.com/erikras/redux-form/releases/tag/v8.2.6).

**Comment by YauheniKhadanionak** [comment]
Looks like we still can't set `undefined` for fields with initial values. [Sandbox here](https://codesandbox.io/embed/redux-form-simple-example-4yxri)
This is caused by `shouldDelete` check into `createDeleteInWithCleanUp`:

https://github.com/erikras/redux-form/blob/87beada1e8a42c62e66c297f1651870f8fe6f254/src/deleteInWithCleanUp.js#L33-L35

https://github.com/erikras/redux-form/blob/de8beb08e888f99c30753fee93768c4e7e0788c3/src/createReducer.js#L44-L54

**Comment by iamandrewluca** [comment]
We can reverse this if
https://github.com/erikras/redux-form/blob/master/src/createReducer.js#L306
or even more check only for `payload === undefined` but I don't know exactly if this may be a breaking change, there are to much responsibilities in `redux-form` and I don't know exactly all cases for `CHANGE`
@renatoagds any thoughts on this one?

**Comment by iamandrewluca** [comment]
Maybe we should not care about initial value at all, and let user set his desired value.

**Comment by khanilov** [comment]
I think this issue should be reopened, it's crucial.

**Comment by iamandrewluca** [comment]
@khanilov what version do you have?

**Comment by khanilov** [comment]
@iamandrewluca I have 8.2.6.

I am addressing the issue pointed in this comment:

> Looks like we still can't set `undefined` for fields with initial values. [Sandbox here](https://codesandbox.io/embed/redux-form-simple-example-4yxri)
> This is caused by `shouldDelete` check into `createDeleteInWithCleanUp`:
> 
> https://github.com/erikras/redux-form/blob/87beada1e8a42c62e66c297f1651870f8fe6f254/src/deleteInWithCleanUp.js#L33-L35
> 
> https://github.com/erikras/redux-form/blob/de8beb08e888f99c30753fee93768c4e7e0788c3/src/createReducer.js#L44-L54

As @YauheniKhadanionak pointed, `shouldDelete` would return false if there is initial value for field.
https://github.com/redux-form/redux-form/blob/v8.2.6/src/createReducer.js#L52-L56

So `deleteInWithCleanUp` not work if initial value presented.

Btw for what reason there are checks for initialValue in `change` handler?

**Comment by aekanshkansal1** [comment]
The issue is still there in redux-form@8.3.5. Not resolved.
