### ISSUE TITLE
Support :invalid pseudoclass on form inputs

### ISSUE THREAD

**Issue by saiichihashimoto** [erikras/redux-form#4033]
Hi, I was wondering if there is planned support for the :invalid pseudo-class on invalid form inputs. I'd like a way to not have to dynamically add classes to my input when they have an error, since this is a browser supported feature already (https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid).

Is this something you plan to support?

**Comment by gustavohenke** [comment]
This is very likely out of question.
Redux Form cannot know about the inner structure of the components that you pass to `<Field>`. Anything that we add support for would either be a) too magic; or b) only work for very specific cases (like `<Field/>` only, without passing [`component` prop](https://redux-form.com/7.3.0/docs/api/field.md/#-code-component-component-function-string-code-required-)).

**Comment by danielrob** [comment]
@saiichihashimoto are you sure this doesn't work? This is most likely to be the nature of react if this doesn't work, since redux-form just renders an <input> element at the end of the day with prepared and spread `input` props. 

If it turns out redux-form is doing something odd when using `component="input"`, then you can write a custom`Input` component: 

```
const Input = ({ input, meta }) => (
  <input {...input} className="my-input" type="email" /> 
)

<Field component={Input} name="input" />

// css
.my-input:invalid {}
```

If that doesn't work then it's almost certainly because react removes the native input validations on controlled form elements, in which case yeah you'll need to fall back to: 

```
import classNames from 'classnames'

const Input = ({ input, meta }) => (
  <input {...input} className={classNames('my-input', invalid: meta.error )} type="email" /> 
)

<Field component={Input} name="input" />

// css 
.my-input.invalid {

}
```

If either the first option above works but `component="input"` doesn't, or a standard controlled react input works but spreading redux-forms `input` prop onto the element doesn't work, then this would be related to redux-form.

**Comment by danielrob** [comment]
I'll close this issue for now since I consider those scenarios to be fairly unlikely, but feel free to prove me wrong with an example sandbox and I'll reopen :).
