### ISSUE TITLE
Custom rule validation with params working incorrect

### ISSUE THREAD

**Issue by nghiepit** [erikras/redux-form#4043]
Hi guys,

https://codesandbox.io/s/o7x41x8x76?module=%2FFieldLevelValidationForm.js

This is hard to understand.
I do not know how to explain.

```js
const minValue = min => value =>
  value && value < min ? `Must be at least ${min}` : undefined
const minValue18 = minValue(18)

// It works
<Field name="age" type="number"
        component={renderField} label="Age(it works)"
        validate={[required, minValue18]}
/>

// Working incorrect
<Field name="age2" type="number"
        component={renderField} label="Age(working incorrect)"
        validate={[required, minValue(18)]}
/>
```

**Comment by gabrielperales** [comment]
@nghiepit I had the same issue, I think it because `minValue(18) !== minValue(18)`, I mean, each time you call `minValue(18)` it returns an instance of a function, but it is not the same instance, meanwhile `minValue18` is always the same instance. 

So something is happening with `redux-form` that it detects that the validation is changing and it is `unmounting` the field each time the validation function changes...

I fix it by adding `destroyOnUnmount: false` to my reduxForm configuration.

**Comment by gabrielperales** [comment]
I think this https://github.com/erikras/redux-form/issues/3566 is related to this issue.

**Comment by nghiepit** [comment]
Thanks, @gabrielperales `destroyOnUnmount: false` it works.
