### ISSUE TITLE
normalize + parse + format

### ISSUE THREAD

**Issue by Fakkio** [erikras/redux-form#4055]
### What is the current behavior?
When using normalize, parse and format, and normalize function return empty string, input became uncontrolled.

Example:
https://codesandbox.io/s/mo0znw38v9

Normalize should remove letters and leaving only numbers and punctuation. Parse and formatter should show comma in input but send dot to the redux store.
But, if you start to write letters in an empty field, they stay there, until you press a number, at that point only the number appear.
In my app, i receive also a warning saying i used a controlled input as not controlled or something like this, this doesn't appear in codesandbox though.
I've noticed that the input behave anormally until normalize function return at least one char.

### What is the expected behavior?
Normalize should remove letters and leaving only numbers and punctuation. Parse and formatter should show comma in input but send dot to the redux store. If you start to insert letters, the input simply has to stay empty.

### Sandbox Link
https://codesandbox.io/s/mo0znw38v9
the issue is on float number input

### What's your environment?
windows 10 pro - 1803 - 17134.81
react: 16.4.0,
react-dom: 16.4.0
redux: 4.0.0
react-redux: 5.0.7
redux-form: 7.3.0
node: 8.11.1

**Comment by danielrob** [comment]
The input becomes uncontrolled when the value prop is passed as `undefined` (i.e. equivalent to not having the value prop). Therein lies your solution ;). 

Currently: 
initial state (`""`) => user enters `a` ("a") => parse ("a") => normalization ("") => store ("") => formatting (`undefined`) => input becomes uncontrolled. 

Use: 
```
const formatter = value => value ? value.replace(".", ",") : "";
const parser = value => value ? value.replace(",", ".") : "";
```

I'll close this as per issue template instructions as it appears to be a support request rather than a bug / feature request.
