### ISSUE TITLE
Redux-form with Material-ui DropDownMenu

### ISSUE THREAD

**Issue by zigrivers** [erikras/redux-form#413]
I'm trying to use redux-form with Material-ui's DropDownMenu, but I am unable to get the DropDownMenu to display the user's selection. The actions are firing when the user selects an option and it is writing to state correctly, but it isn't updating DropDownMenu's display of the user's selection.

I think this is because of the way that DropDownMenu is defining their properties. They define them as follows:

> **displayMember**   string default: text
> DropDownMenu will use text as default value, with this property you can choose another name.

> **valueMember**   string default: payload
> DropDownMenu will use payload as default value, with this property you can choose another name.

> **selectedIndex**   number default: 0
> Index of the item selected.

> **onChange**   function(event, selectedIndex, menuItem)
> Fired when a menu item is clicked that is not the one currently selected.

I've defined my component as follows:
```javascript
class Department extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
        let {fields: { department }, handleSubmit, closeDialog, openDialog, resetForm } = this.props;
        const departments = constants.departments.map(( dep ) => {
            return {
                value : dep,
                label : dep
            }
        });
        <DropDownMenu valueMember="value"
                  displayMember="label"
                  placeholder="Department ..."
                  menuItems={departments}
                  {...department} />
        );
    }
}

Department = reduxForm({
    form          : 'dep',
    fields        : [
        'department'
    ]
})(Department);

export default Department;
```

Any ideas on what I'm doing wrong? Or can I not use this component with redux-form?

Thank you!

**Comment by neverfox** [comment]
I use material-ui with redux-form just fine, though I don't have any particular experience with DropDownMenu. You should be able to use any component as long as the API matches [redux-form's assumptions](http://erikras.github.io/redux-form/#/faq/custom-component?_k=fl4pzb). Redux-form is only going to communicate with the `value` and `onChange` props, which you might need to customize since you're playing around with `valueMember` and `displayMember`. Try creating a wrapper component that changes the API for redux-form's sake and transforms and passes the appropriate things along to DropDownMenu.

**Comment by olmg-mike** [comment]
I have struggled mightily with material-ui Select fields.  The conclusion I finally came to was to use version 0.13.4 of material-ui.  This was based on the subset of material-ui components I was using and the material-ui creators also say the SelectField in 0.14.0 is a mess and they are right.  Half the fields are deprecated but still work yet, the alternative correct composability features do not work.  Use  SelectField instead of DropDownMenu if you can use 0.13.4 version of material-ui.  All this being said with not checking if things have changed in material-ui in the last week or so.

Here is an example of how I use it.  The ContentTypes variable is just an array of {id,name} fields.  The contentType variable is the redux-form field. err

<SelectField {...contentType}
          floatingLabelText="Content Type"
          valueMember="id"
          displayMember="name"
          menuItems={[{'id': '', 'name': ''}, ...ContentTypes]}
          errorText={errorText(contentType)}
        />

**Comment by neutrous** [comment]
Hi there, I'm using material-ui@0.14.4 with redux-form. It plays well in most situation, however, when using SelectField component, its value couldn't be set correctly by redux-form. May be it's relevant to the signature of onChange props? SelectField using 3 params when calling onChange, and the 1st parameter (event) seems not matching the assumption of normal event.

**Comment by ooflorent** [comment]
`redux-form@v6` has an [example using Material UI](https://github.com/erikras/redux-form/tree/v6/examples/material-ui)

In the future, we recommend that you ask questions on StackOverflow first, and file issues if you’re confident the bug is in the library.
