### ISSUE TITLE
Async validation for more than one field

### ISSUE THREAD

**Issue by KateKate** [erikras/redux-form#424]
Do you have an receipt to show loading icon (of async validation) only for the field just blurred. I know about asyncValidating prop, but it's the single prop for all fields. Thank you in advance!

**Comment by erikras** [comment]
This feature does not currently exist.

**Comment by pablogq** [comment]
+1

**Comment by VladShcherbin** [comment]
+1

**Comment by altaihero** [comment]
++

**Comment by adiachenko** [comment]
Is there any reasonable hack around this limitation? Frankly, it's not something crucial but I'm curious nonetheless.

**Comment by KateKate** [comment]
I've sent PR about it, waiting for feedback https://github.com/erikras/redux-form/pull/445

**Comment by erikras** [comment]
Published @KateKate's fix under [`v4.0.6`](https://github.com/erikras/redux-form/releases/tag/v4.0.6).

**Comment by djshapiro** [comment]
If I understand the PR correctly, it looks like asyncValidating can now have a value of true, false, or a field. But the case where multiple fields are asynchronously validating at the same time still needs to be solved, correct? Seems like an edge case, I know, but I'm just trying to understand the extent of this change.

**Comment by erikras** [comment]
@djshapiro The field that was blurred to trigger the async validation is the one set to the `asyncValidating` value. There can only be one of those.

If you want a spinner on both your password and confirm inputs (dumb example, since that's not an async operation, but...), you could display it if `ayncValidating === 'password' || asyncValidating === 'confirm'`.
