### ISSUE TITLE
Uncaught error in production mode

### ISSUE THREAD

**Issue by romanovskyyy** [erikras/redux-form#4302]
When using redux-form 8.0.4 with react-redux 6.0 there is a bug in production mode (minified code), with throw new Submission Error, that is uncaught
`Uncaught (in promise)
   r:{
       errors: {_error: "Email isn't valid"}
    }
`
Everything works in development, error is catched and show on UI

**Comment by erikras** [comment]
Grr... sounds tough to diagnose... 😦 Any effort on your part to recreate, like in a sandbox environment, would be appreciated.

**Comment by oisti** [comment]
Hi!

Sandbox: [https://codesandbox.io/s/github/oisti/redux-form-error/tree/master/](https://codesandbox.io/s/github/oisti/redux-form-error/tree/master/)

Important!
Error only occurs if project is built (npm run build)

**Comment by antoinerousseau** [comment]
Same issue here:
If you try to log into https://tribeez.com/login with wrong credentials, no error is shown, but the exact same code shows the error message in dev mode.

**Comment by arielschvartz** [comment]
Same problem here. Any ideas?

**Comment by qw4n7y** [comment]
+1

**Comment by mmerickel** [comment]
I've tracked this down using @babel/core 7.2.2 to the fact that the `SubmissionError.name` is being minified which is causing the `isSubmissionError` to return `false` due to it doing a simple check on the name. I'm not clear if it's a bug in babel, es6-error, or redux-form's usage of the name comparison.

**Comment by mmerickel** [comment]
Some further sleuthing and this is a known issue [1] in es6-error and redux-form is just going against its recommendations here by testing the name attribute. I think `instanceof` is supposed to work but it doesn't right now possibly because redux-form is being compiled in loose mode.

[1] https://github.com/bjyoungblood/es6-error/issues/31#issuecomment-301128220

**Comment by gevorg** [comment]
> Uuh, here was already an issue. Spent some time and found that the SumbissionError.name is mangled. As has been found already here :D :D
> 
> Could the test:
> 
> `const isSubmissionError = error => error && error.name === 'SubmissionError'`
> 
> Be changed to this:
> 
> `const isSubmissionError = error => error && error.name === SubmissionError.name`
> 
> Shouldn't that fix this? The instanceof test was (at least in my test code) also able to catch the SubmissionError.
> 
> I put in our production code this into webpack config. It hides the issue. Perhaps somebody finds this useful :
> 
> ```
>   plugins.push(
>     new webpack.optimize.UglifyJsPlugin({
>       mangle: {
>         except: ['SubmissionError']
>       }
>     })
>   );
> ```

Thanks for workaround, do you know any option to fix this without ejecting react-app? :thinking:

**Comment by erikras** [comment]
Published fix in [`v8.1.0`](https://github.com/erikras/redux-form/releases/tag/v8.1.0).

**Comment by gevorg** [comment]
:tada: :tada: :tada:
