### ISSUE TITLE
Reduce rerendering of form

### ISSUE THREAD

**Issue by davidspiess** [erikras/redux-form#431]
If i focus a text field, the whole component gets rerenderd twice.
First the `active` property is set to `undefined`, then to the name of the active element.
Why not directly switching to the new active state?
On big forms it does have quite a performance impact, there is a small delay notable when placing the cursor.
Changing a radio button can cause even more rerender. (See gif).

![rerender](https://cloud.githubusercontent.com/assets/992674/11841767/dd1eb1f4-a3ff-11e5-9a56-d6b9d4620158.gif)

**Comment by erikras** [comment]
When you click from field to field, it's firing two actions, `BLUR` and `FOCUS`, both of which change the state, and when the state changes, the form component must be re-rendered.

In general, with React, you shouldn't worry too much about re-rendering, because it's so fast.

If you're very sensitive to this, you could stop passing `onBlur` and `onFocus`, by specifying only the `value` and `onChange` props, and you would lose the `touched` flag tracking. Example:

```js
<input type="text" onChange={myField.onChange} value={myField.value}/>
```

That would only re-render when a form value changes.
