### ISSUE TITLE
Initialize Dynamic Form from state

### ISSUE THREAD

**Issue by tarim** [erikras/redux-form#4349]
Hi There,

I have a redux form, and it has fields(dropdown, text and more). Most of them generated dynamically(name(A1, A2, A3 ...), id, etc.). When the user edits it, I want to initialize it from the state(the API results). Is that possible, please?

Thank you,

**Comment by gustavohenke** [comment]
It certainly is possible.  You just have to pass an `initialValues` prop that maps to those dynamic fields.

I don't have a clue about how they are generated since you didn't provide an example, but keep in mind that if you need data generated by redux-form before you can initialise redux-form, that will require some creativity.

**Comment by tarim** [comment]
@gustavohenke,

Thank you for your reply. I did initialize the form. But, whatever I do, it did not work correctly. If I do initialize on `componentDidUpdate( this.props.initialize(this.props.initialValues)),` it will get the latest redux state data and initialize correctly, but you cannot update the form(initialize all the time). If I use componenetDidMount or others, it won't get the latest redux data and do not initialize correctly. 

So, the question is how redux form handle the redux data for initialization, please? What is the right way to handle this issue, please?

**Comment by Deimos88** [comment]
I have problem like this
