### ISSUE TITLE
Form fields change values to empty strings when they get focus.

### ISSUE THREAD

**Issue by avsd** [erikras/redux-form#440]
I'm using redux-form with Django REST Framework and server-side validation, and here is the effect I'm getting:

![reduxform2](https://cloud.githubusercontent.com/assets/720283/11871719/2f84f0ec-a4c9-11e5-80cc-5d92b546842b.gif)

Initially all field values are `undefined`. But once you put a cursor into an input the field changes to an empty string. Is this a bug or an expected behavior? Is there a way to prevent it?

**Comment by erikras** [comment]
*Excellent* screencast to demonstrate. Thank you!

This behavior is because the value for the field is stored in `onBlur` from `event.target.value`, which is giving `''`. I disagree with using `event.target.value || undefined` as the field value (thus making it _never_ `''`), so I think you have two options.

1) For text fields, you _could_ avoid passing the standard `onBlur` function, only updating the field value `onChange`. 

```js
<input
  type="text"
  {...myField}
  onBlur={() => {}}/> // overrides prop destructured in the previous line
```

2) Not be such a stickler in your validation between `undefined` and `''`. What does that really gain? If you really want to convert `''` to `undefined`, you can do that when you save the data.

I recommend the latter.

**Comment by avsd** [comment]
@erikras - distinguishing between empty string and no value is standard behaviour of REST API, as implemented in Django Rest Framework: http://www.django-rest-framework.org/

The option (1) will not work, because if I type something in the field and then delete it, I will still get an empty string.

I guess the quickest fix for my case would be to process the data before making API request replacing all empty values with `undefined`. But in general, I think the current behavior is incorrect, because it's inconsistent and non-deterministic: if a field is empty, it should either always send an empty string, or always an `undefined`.

**Comment by avsd** [comment]
btw, here is the tool to make nice screencasts ;) http://www.cockos.com/licecap/

**Comment by drouillard** [comment]
"But in general, I think the current behavior is incorrect, because it's inconsistent and **non-deterministic**: if a field is empty, it should either always send an empty string, or always an undefined." 
Is that correct in this case? If field is not touched -> always undefined. If entered and blur event triggered -> empty string. Wouldn't non-deterministic be if you hit submit twice and then received 2 different errors?

**Comment by erikras** [comment]
I don't believe this falls under the purview of `redux-form`, and I think that visiting an input and not entering anything (`''`) has separate meaning from never having visited it (`undefined`), so it is up to the user of the library to lump those two together if they wish.

**Comment by GuillaumeCisco** [comment]
Indeed, it's frustrating.
What you could do before submitting your form and you know you want some fields to bet set to undefined and not to an empty string is to use reduce.

```
values = Object.keys(values).reduce((previous, current) => {
                previous[current] = values[current] === '' ? undefined : values[current];
                return previous;
            }, {});
```
This code automatically set empty strings to undefined. You could add a filter if you wanted to pass some fields to empty strings.

Cheers,

**Comment by jinxac** [comment]
`onBlur={() => {}} ` works fine with this. 

 @avsd  Even i was using django-rest in backend, so what i did is initialize the non-mandatory values in the form to `null` . Then override onBlur method and call the API on submit. The empty fields would have the initialized value which is null.

**Comment by devangbhuva97** [comment]
<Field ...... onFocus = { (e) => e.preventDefault()  onBlur = { ... } />
I solved by preventing onFocus Action.
