### ISSUE TITLE
Installing from github for latest update is not working #dispatchSubmit

### ISSUE THREAD

**Issue by andrew-oko-odion** [erikras/redux-form#4421]
### Are you submitting a **bug report** or a **feature request**?

`BUG`
I am using yarn as my package manager and I am trying to make use of the latest changes, so I installed using github. but non of the modules are exported.  I am trying to make use of the dispatchSubmit feature that was just merged in a couple of days ago.

### What's your environment?

`Linux`
`yarn verison 1.1.0 `

**Comment by gustavohenke** [comment]
Yeah, the code in GitHub isn't built.

There are a few options in [this StackOverflow question](https://stackoverflow.com/questions/48287776/automatically-build-npm-module-on-install-from-github).
Since the best option -- a prepare script -- involves installing all dev dependencies of the package for everyone, that's out of our scope, as it wouldn't be fair to users.

You are free to try other options though, but I don't think changing the Redux Form repo makes sense at the moment.
