### ISSUE TITLE
Overwriting values after submit affecting redux form fields store while using FormSection.

### ISSUE THREAD

**Issue by narensprinter** [erikras/redux-form#4459]
Please check this example - https://codesandbox.io/embed/6w3mw20q8n - I created demo version.

// If i overwrite first_name after onSubmit function. its affecting and changing redux field store. how i can control this ? . Also its happening only while using FormSection.

**Comment by renatoagds** [comment]
@narensprinter can you provide more information, following our template?

**Comment by narensprinter** [comment]
@renatoagds Type any first name and last name then click submit button .form registered values automatically changing if i overwrite values inside onSubmit function call. https://codesandbox.io/embed/6w3mw20q8n

**Comment by renatoagds** [comment]
@narensprinter That the expected behaviour, since you're changing the deeper object, and still pointing for same reference in memory. The `Values` component didn't update, because it's listening for store dispatch, and it didn't happen, since you mutate direct. If you don't want to get that happen, you need to deep clone (https://lodash.com/docs/4.17.11#cloneDeep) or use `Immutable`.
