### ISSUE TITLE
Validate only fields that are rendered

### ISSUE THREAD

**Issue by Juliograham** [erikras/redux-form#4497]
Feature request.

Validation currently runs on every field whether or not the field is rendered. (Version 5.2.3)

Is it possible to run validation only for the fields that are rendered?

**Comment by renatoagds** [comment]
@Juliograham We validate the registered fields. So, if you want to no run validation into some field, make sure that is not registered. You could do that, using [`forceUnregisterOnUnmount`](https://redux-form.com/8.2.2/docs/api/reduxform.md/#-code-forceunregisteronunmount-boolean-code-optional-) or stopping using global validation to use `Field` single validation: https://redux-form.com/8.2.2/docs/api/field.md/#-code-validate-array-lt-function-gt-value-allvalues-props-name-gt-error-code-optional- .. I don't know if all these features is supported in v5, if not, I suggest you take a few time to update your version, since you're 3 majors versions behind.
