### ISSUE TITLE
Server validation errors not using Promises

### ISSUE THREAD

**Issue by VladShcherbin** [erikras/redux-form#450]
I'm using websockets to validate on the server, how can I attach errors to the form after server response received?

```js
channels.methods.push('create:seo', {data: data})
  .receive("ok", () => {
    // success, flush the form and redirect
  })
  .receive("error", (response) => {
    const { errors } = response;

    // how to pass errors to the form ?
  });
```

**Comment by VladShcherbin** [comment]
So, with action creators I managed to do this:

```js
handleSubmit(data, dispatch) {
  dispatch(startSubmit('seoCreateForm'));

  channels.methods.push('create:seo', {data: data})
    .receive("ok", () => {
      // form is destroyed on redirect
      dispatch(pushPath('/seo'));
    })
    .receive("error", (response) => {
      const { errors } = response;

      dispatch(stopSubmit('seoCreateForm', errors));
    });
}
```

@erikras can you have a quick look, is it ok to do this or is there a better option?

**Comment by erikras** [comment]
:+1: Looks good. That's the answer.

For other people following this, if you are _not_ destroying the form via a redirect, then you should also call `dispatch(stopSubmit('seoCreateForm'))` (with no errors) in the `ok` branch.

**Comment by erikras** [comment]
I added your example [to the FAQ](http://erikras.github.io/redux-form/#/faq/websockets).

**Comment by VladShcherbin** [comment]
@erikras great, thank you!

**Comment by nzjoel1234** [comment]
Hey I am trying to use this approach like so:
`<form onSubmit={handleSubmit(save)} >`

In `save` I am dispatching startSubmit and then later (asynchronously) I either redirect (in the success case) or in the error case I dispatch `ReduxForm.stopSubmit('MyFormName', { _error: error })` followed by but i notice that (since my save function returns nothing) redux-from's handleSubmit function deploys setSubmitSucceeded.

Am I doing something wrong or is it fine that setSubmitSucceeded is deployed?

Am I supposed to be wrapping my `save` function in redux-form's `handleSubmit` function?

In @VladShcherbin's example above or in the docs there are no mentions of how to wire this into the form's `onSubmit` function.

**Comment by hyperivo** [comment]
@nzjoel1234 I faced the same issue since I am using redux-logic to handle all async stuff. The easiest solution I could come up with was just to follow what was said above + return a Promise in my onSubmit. This will leave redux-form in a 'submitting' state until either the promise resolves (not happening) or I dispatch a stopSubmit Action in my logic.

```javascript
function onSubmit(values, dispatch) {
  return new Promise(() => { dispatch(signupSubmit(values)); });
}

export default reduxForm({
  form: 'signup',
  onSubmit
})(SignupForm);
```

Please let me know if in the meantime you found a better solution to this problem.
