### ISSUE TITLE
Select Menu not working with Cascader componet of antd 

### ISSUE THREAD

**Issue by abhijithvijayan** [erikras/redux-form#4503]
### Are you submitting a **bug report** or a **feature request**?
bug-report

### What is the current behavior?
select menu not rerendering with selected value in dom

### What is the expected behavior?
option gets selected

### Sandbox Link
https://codesandbox.io/embed/redux-form-antd-0kz0u

### What's your environment?

Redux-Form v8.2.4

### Other information
Uses Cascader from 'antd'

**Comment by ralekna** [comment]
This is not a bug with Redux Form. It much more some issue with `Cascader` component that you're using - it doesn't accept new `value` coming from redux-form state. In renderField function you can print `input.value` and see it for yourself. 

BTW, in you example you're using Form component that is `antd` instead of `redux-form`. You can alias `Form` by using __`as`__ keyword.

```javascript
import { Field, reduxForm, Form as ReduxForm } from 'redux-form';
import { Cascader, Col, Form, Icon, Input } from 'antd';
```

**Comment by abhijithvijayan** [comment]
@ralekna Is it a must to use Form from redux-form? I have no issues with using form from antd/bootstrap so far.
