### ISSUE TITLE
Multiple submit handlers / submit buttons

### ISSUE THREAD

**Issue by mikkelwf** [erikras/redux-form#535]
I was just wondering if it would be possible in some way to have two form submit buttons?

I want to use the same basic form, but do two different things when the use submits the form 
* get routed to the new saved instance
* stay on the form page and be able to enter in another instance

So the data should stay the same, but i need to be able to notify the method i'm dispatching, that i want to change the flow.

I cannot see a clear way to do this, so i hope somebody can be of help with my issue.. :)

**Comment by drouillard** [comment]
1. handleSubmit returns a promise which you can chain off of. See comment in #527 for example.

2. Could bind a variable to your submit and then use it
``` javascript


const onSubmit = (foo, data) {
 // do your async behavior and after it returns
  if (foo) ...
}

<form onSubmit={handleSubmit(onSubmit.bind(this, foo))}>
```

**Comment by drouillard** [comment]
@erikras I wonder if questions like these could be moved to stackoverflow?

**Comment by erikras** [comment]
@drouillard Yeah. I don't have a particularly strong feeling about it. Is there any reason to believe that the community of knowledgable library users, like yourself, would be more or less likely to answer them there? As the lib author, I very much appreciate users answering other users' questions.

**Comment by drouillard** [comment]
@erikras I think if you (I can help as well with your permission) asked people to post usage questions on stackoverflow it would allow issues to get cleaned up and also would get users answers in a more timely fashion.

I think the flow would be

1. Kindly ask user to post question on stackoverflow (keep issue open)
2. User posts on stackoverflow and provides link in github issue
3. Close the issue - answer/track on stackoverflow

The risk is people feel like they are being ignored/side stepped, but really its about keeping issues clean so people can track development. I am using redux form in a new effort, and its tough to follow actual bugs/enhancements. 

Also to clarify - I think this is a great question. Just that its a usage question rather than an issue.

**Comment by erikras** [comment]
Excellent ideas, @drouillard. Thanks.

**Comment by mikkelwf** [comment]
I used the 2nd approach and bound a custom value to the submitHandler, and i works quite well.
The only thing i could not do was access the onSubmit method sent in via the props, so i assigned the method to another name, and then i could access it via the props in my custom mySubmit method.

Thanks for the help guys! :star: 

I think it's a good idea to move questions like these to stackoverflow. I just posted my question here because i could see that many other people had done so already here, but i'ts probably better to keep issues here to actual issues, enhancements etc.
