### ISSUE TITLE
Q: How to access errors on submit from outside of component when using synchronous validation

### ISSUE THREAD

**Issue by Strajk** [erikras/redux-form#538]
Hi, thanks for awesome work!

I'm using synchronous validation, which is blocking call to handleSubmit until all validations will pass... is there a place where I can get all errors on user's attempt to submit a form (but not on every form state change)? 

Pseudocode

```
handleSubmit(errors, values) {
  if (errors) {
    // --> here I would like to log all validation errors
  } else {
    dispatch(fooActions.save())
  }
}

render() {
  ...
  <FooForm
    initialValues={...}
    onSubmit={this.handleSubmit}
  />
  ...
}
```

or maybe better API

```
handleErrorSubmit(errors) {
  // log errors
}

handleSubmit(values) {
  dispatch(fooActions.save())
}

render() {
  ...
  <FooForm
    initialValues={...}
    onSubmit={this.handleSubmit}
    onErrorSubmit={this.handleErrorSubmit}
  />
  ...
}
```

**Comment by erikras** [comment]
If you just want to log them, you can do that in whatever code you are returning them from.

If you want to display them... If you set [`returnRejectedSubmitPromise`](http://erikras.github.io/redux-form/#/api/reduxForm), you should get them back from the submit call. e.g.
```js
<FooForm onSubmit={values => dispatchSave(values)}/>
```
```js
class FooForm extends Component {
  handleSubmit() {
    this.props.handleSubmit() // will call the onSubmit above
      .then(() => {
        // success stuff
      })
      .catch(errors => {
        // THESE are the errors you seek!
        this.setState({submitErrors: errors});
      });
  }

  render() {
    return (<div>
      <button onClick={this.handleSubmit}>Submit</button>
      {this.state.submitErrors} // format this somehow
    </div>);
  }
}

FooForm = reduxForm({
  form: 'foo',
  returnRejectedSubmitPromise: true
})(FooForm);
```
Does that help?

**Comment by damassi** [comment]
I solved this problem last night after a bit of frustration and it turned out to be fairly simple (though it would be much better if we could have a `dispatch(validateSync(formName))` action that flows through the system) and triggers touched, etc. 

Keep in mind that my use-case is somewhat complex and my forms were large enough to warrant me creating a wrapper library around redux-form in order to break everything apart and keep everything sane. But yeah, what I did was 

- Aggregate and merge all of my form data through a higher order reducer, 
- Aggregate all of my validations into a singleton `validator` that keeps track of which validations it needs to check against depending upon which form I'm displaying (i've stitched together tons and tons of forms). 
- When I click submit I can call `validator.validate(formData)` which then returns all of the errors that my form contains (if any). 
- To get around the missing `dispatch(validateSync(formName))` action (to trigger "touched" and update the view), I had to basically fake a submit call by collecting, in the validation aggregator, `handleSubmit(() => {}) which then is called as I iterate over all of the form pieces that need validation. If any are invalid errors will appear in the view, which acts independently of the blocking action.

In sum, in order to block submissions it I had to roll my own strategy. 

Here's a gist of what I'm doing. Basically it just passes values down to reduxForm() and allows you to stitch together a ton of independent forms: https://gist.github.com/damassi/00e798e080d7b7246c8e

Note that i'm running into pretty serious performance issues in __DEV__ which mostly disappear when deploying to production. Memoization has helped.

**Comment by Strajk** [comment]
Sorry for late response, especially when you both responded almost immediately.

@erikras 

Your solution *almost* works for me and don't know if that's my problem with using your lib or if it's bug in redux-form.

I'll try to explain with picture :)

![untitled 2016-01-20 14-14-15](https://cloud.githubusercontent.com/assets/697301/12449810/24b5c912-bf80-11e5-9311-3fc65b076571.png)

Thanks so much for your time!

**Comment by Strajk** [comment]
@damassi thanks for answer, but I would like not to resort to such complication for one event to analytics :) but if i will not find any other solution, I would try that!

**Comment by erikras** [comment]
So it sounds like your problem is that your `handleSubmitFoReal()` needs to return a promise?

**Comment by Strajk** [comment]
@erikras the problem is that handleSubmitFoReal is not even called when there are validation errors, so it cannot return promise

**Comment by erikras** [comment]
That is true if there were sync or async validation errors, but you are defining neither of those. Where are your validation errors coming from?

**Comment by Strajk** [comment]
Oh :( I'd tried to omit not important code from examples and I omitted even validate property...

```
FooForm = reduxForm({
  form: 'foo',
  fields: [...],
  validate: (values, props) => { ... return {...} },
  returnRejectedSubmitPromise: true
})(FooForm);
```

**Comment by Strajk** [comment]
Now I'm thinking that since we got destructuring in ES6 I should not even use `...` in examples :D

**Comment by erikras** [comment]
Oh, so you want to have both sync and submit errors together?

It is true that, in an effort to avoid unnecessary server calls, `redux-form` doesn't do the submit if there are client side sync errors.

If that doesn't answer your question, then I guess I'm misunderstanding the problem.

**Comment by Strajk** [comment]
Yep, maybe it would be better to explain my motivation first :)

We have sync validations and we don't want to submit form unless all validations pass...

but at the same time, we want to send submit errors to analytics like Google Analytics, Kissmetrics and similar to track common problems with validations so we can optimise UX --- and this should be send only on user's attempt to submit the form, not on every render()

btw thanks so much for your time

**Comment by erikras** [comment]
Okay, so what if you track when `this.props.submitFailed` flips from `false` to `true`, and then log `this.props.errors`? You'll only get the first one, but it's something...

**Comment by Strajk** [comment]
OK, thanks for your help!

By the way, I added `if (returnRejectedSubmitPromise) return Promise.reject();` at the end of `handleSubmit.js` and all tests are passing. It would fix my problem, but I don't have deep understanding of whole project so don't know if it's right design decision.

**Comment by erikras** [comment]
Actually, that seems okay. Since the submit has failed at that point, and if someone has given that prop, they are expecting a promise.

**Comment by damassi** [comment]
Awesome, @erikras - your solution works much better for me :+1:

**Comment by Strajk** [comment]
Wow, are you in some competition for best support for open source project or what? :))

would you mind making a new release to npm? thx so much!

**Comment by erikras** [comment]
[`v4.1.5`](https://github.com/erikras/redux-form/releases/tag/v4.1.5). :smile:
