### ISSUE TITLE
correct way to initialize a child component's form

### ISSUE THREAD

**Issue by arolson101** [erikras/redux-form#584]
I have a popup dialog that has a redux-form inside it.  It works great when adding new values, but I want to use it to edit existing values as well.  What is the correct way to set its values (via props)?  I have the object with the correct values in a parent component, and I want the child to be responsible for the default values.  The closest I can come to an answer is to pass them in as initialValues, but they will overwrite the form's initialValues.  I want the form to have the equivalent of user-filled in values.

**Comment by dbertella** [comment]
I'm struggling around this too, I'm trying to reproduce the example with initial values without firing an action but taking them from props with no luck. Any example around maybe?

**Comment by aybmab** [comment]
+1

**Comment by ooflorent** [comment]
The correct way is to use `initialValues`. If you encounter troubles using it, StackOverflow is a better to ask for help. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it since GitHub search is terrible!

If your question does not bring enough attention, feel free to post a link to it here and I'll do my best to answer it!
