### ISSUE TITLE
Bug in "Complex Values" example?

### ISSUE THREAD

**Issue by bmueller-sykes** [erikras/redux-form#613]
This is either a bug, or I don't understand what's going on. 

in `ObjectSelect.js`, the <select> element has this:

`value={multiple ? value.map(JSON.stringify) : JSON.stringify(value)}`

the first part of that statement, `value.map(JSON.stringify)`, seems wrong to me, no? I can't quite figure out what that's supposed to be.

And is it the case that the second half of the statement is redundant, is `JSON.stringify` necessary? Isn't the value going to come through as an object literal?

**Comment by greaber** [comment]
Using an array for the values is a React thing.  See the bottom of https://facebook.github.io/react/docs/forms.html.  It might work to use an object as a value rather than a string, but the examples on that forms page all use strings, and also `JSON.stringify` will often take structurally equal objects to the same string.  (I'm not sure how bulletproof it is, but the example does claim to be "quick and dirty".)  So I think there is no bug.

**Comment by erikras** [comment]
Well, it was working, so in that sense, it wasn't a bug, but I tried without doing any of the json conversion, and it works just fine. I had been under the impression that the values should be strings. Thanks guys. :+1:
