### ISSUE TITLE
Submit form on change

### ISSUE THREAD

**Issue by Bitaru** [erikras/redux-form#67]
Hi, thanks for awesome lib {it really made my life simpler}.
Is it possible to submit form with changed data when my component triggers onChange event?
Basically i want to update item in state when user selected type of this item in form.

Sorry for stupid question might be it is in docs, but i don't see it -_-

**Comment by erikras** [comment]
What happens when you submit the form is up to you. I'm not entirely sure what you're asking, but you can pass whatever you want to your component's `onChange` event. By default `onChange` just modifies the redux state in memory, and does not "submit" anything, but you could pass
```javascript
onChange={(event) => {
  this.props.handleChange(event); // update redux state
  this.submit({ myField: event.target.value }); // make some ajax (?) call to submit the altered data
}
```

**Comment by Bitaru** [comment]
Oh, i got it...
```
<TypeSelect value={type.value} onChange={(data) => {
  type.handleChange(data);
  this.props.onSubmit({ type: data }); // fire onSubmit function in parent to commit data in store
}} />
```
But i tho' there is a possibility to force submit whole form if validation passed

**Comment by MarkusPint** [comment]
Is this still valid? this.props.handleChange seems to be undefined.

I want to update the redux state + trigger an AJAX call.

**Comment by max-mykhailenko** [comment]
Yes, one way to send whole form — add onChange to form tag with zero timeout.

**Comment by MarkusPint** [comment]
Thanks! @max-mykhailenko

**Comment by freen** [comment]
What @erikras and @Bitaru propose here doesn't work for me, because directly callling my custom `submit` handler (the one passed to `handleSubmit`) would skip form validation.

I need to trigger `onSubmit` from `onChange` without skipping validation. I described the dilemma here as well: http://stackoverflow.com/questions/38902221/redux-form-trigger-form-onsubmit-after-input-onchange

@max-mykhailenko Could you include a code snippet for your proposal? I'm not sure how to implement what you mean.

**Comment by max-mykhailenko** [comment]
@freen 

```javascript
onImageUpload(image) {
  this.props.fields.images.addField(image);
  setTimeout(this.props.handleSubmit, 0);
}
```
