### ISSUE TITLE
Why can't Redux Form use React Redux instead of a custom decorator?

### ISSUE THREAD

**Issue by greaber** [erikras/redux-form#704]
It could be nice if the props passed to a form were just ordinary Redux state that could be accessed using react-redux.  (And also maybe if the form values could be ordinary Redux state instead of requiring calling `getValues`.)  Can someone explain why Redux From doesn't work like this but needs a custom decorator (that, however, emulates the API of react-redux)?  Does it have to do with the validations that Redux Form does?

**Comment by davidkpiano** [comment]
@greaber This is the exact approach that [React-Redux-Form](https://github.com/davidkpiano/react-redux-form) takes - everything is done through reducers and actions instead of custom form decorators (though you can use the `<Form>` and `<Field>` components as helpers).

With regard to Redux-Form, by using a custom decorator, it abstracts a lot of the "magic" and boilerplate behind providing bound actions to your control components and handling things such as validation, blur validation, async validation, promise submit, etc. This approach would make sense for someone who is still relatively new to Redux and not willing to have to understand how the reducers/actions interact with overall form state, which makes sense for the general use-case of forms in React.

**Comment by greaber** [comment]
Thanks, I will give React-Redux-Form a look.  I can see that Redux Form is nice for the anticipated use cases, but I am trying to use forms to let the user edit structured data I keep in Redux, and I keep feeling that I am fighting assumptions Redux Form makes and having to resort to hacks.  Maybe there is room for two Redux form libraries!
