### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by rkrdo** [erikras/redux-form#725]
@erikras It seems you [deleted](https://github.com/erikras/redux-form/commit/30986ef7fdaa5cf9925d932d8bfa562ffc8d1b86) the example, was it on accident?

**Comment by erikras** [comment]
It was intentional. The examples don't belong here (in `master`)  __yet__. They will live here eventually, but it was accidental that I put it here in the first place.

At the moment, the examples live [here](https://github.com/erikras/redux-form/tree/gh-pages/4.2.0/src/examples), although the docs are in a transition period (in _flux_ :smile:) at the moment. So far there are no other examples than the ones [demoed on the website](http://redux-form.com/4.2.0/#/examples?_k=6ulhrb).

Sorry for the confusion.
