### ISSUE TITLE
blur validate on submit

### ISSUE THREAD

**Issue by anorudes** [erikras/redux-form#733]
Hello, @erikras, i like your library) Can you help me with little problem?
I see that "validate" fires only on input blur (when changed focus). 
How i can run validate after click on submit?
```
Form = reduxForm({
  form: 'form',
  fields: [
    'field',
  ],
  validate, // want run this after click on submit button
})(Form);
```

Ye, i know about async validataion. Example:
```
submit(data, res => {
  const err = res.text;
  if (err) {
    reject({ _error: err }); // our error from server
  } else {
    resolve();
  }
});
```
but i don't want repeat validate on server.

**Comment by erikras** [comment]
This is sort of what the `touched` flags are for.  The sync validation (the `validate` config param) is run _on every render_, but so as to not display the errors all the time, they are only displayed (if you choose to use the flag as the examples suggest) when the field is also `touched`. When you submit the form, in order to show all errors, all the fields are marked as `touched` whether or not you have visited them. And if the validation fails, the submit is cancelled.

If you want to not mark the fields as `touched` on blur, there is a `touchOnBlur` config param that defaults to `true`, but if you set it to `false`, the fields will only be "touched" when you submit the form. I think that's what you are looking for.

**Comment by anorudes** [comment]
Thanks, @erikras for big answer, but "touchOnBlur: false" don't change anything in my form.
Can you show a mini example?)

My code (maybe i make misstake):
```
Form = reduxForm({
  form: 'forgotPassword',
  fields: [
    'email',
  ],
  touchOnBlur: false,  
  validate,
})(Form);
```

```
            {
              email.error &&
                <Label bsStyle="danger">{email.error}</Label>
            }
```
error doesn't show after click submit button, because validate function not called.
But i see the error after onBlur.

**Comment by ooflorent** [comment]
This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
