### ISSUE TITLE
Normalize causes asyncValidate to rerender form for every triggered action in the application

### ISSUE THREAD

**Issue by davidspiess** [erikras/redux-form#759]
Using `reducer.normalize`, every triggered action in my application causes the normalized form to rerender and causes performance issues. `shouldComponentUpdate` tells me that the `asyncValidate` function prop changed. So my guess here is, redux-form creates during the normalize process a new identity of the asyncValidate function instead of using the same. See https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.8dflk14xw

```
this.props[asyncValidate] changed: 'function (event) { for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) { args[_key - 1] = arguments[_key]; } return (0, _silenceEvent2.default)(event) ? fn.apply(undefined, args) : fn.apply(undefined, [event].concat(args)); }' => 'function (event) { for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) { args[_key - 1] = arguments[_key]; } return (0, _silenceEvent2.default)(event) ? fn.apply(undefined, args) : fn.apply(undefined, [event].concat(args)); }'
```

I recorded a short gif to make it clear how many rerenders this can cause if you are using some actions triggered on hover.

![example](https://cloud.githubusercontent.com/assets/992674/13947054/8e72c44a-f018-11e5-8ffb-eda8b042f191.gif)

Thank you :)

**Comment by gustavohenke** [comment]
This was probably something from the v5 ages; ages that any change would rerender the form anyway... then it came v6 which only updated a single field at a time!

In case you're still looking at this issue: I'm not sure if the `asyncValidate` function could be changing by a bug on us or a setup mistake of yours, but if you could at least try newer versions of the v5 branch, it would be great.

Since I don't know if @erikras still have plans to support v5, I'll close this issue for now (yeah, almost 1.5 years later...).
