### ISSUE TITLE
How to reset input[type=file] after form submission?

### ISSUE THREAD

**Issue by mtakac** [erikras/redux-form#769]
Hi I realize there has been some discussion about this issue already and I've seen the note in the docs about file inputs being a special case (http://redux-form.com/4.2.0/#/examples/file?_k=fyn5yj), however I cannot really understand what's the optimal solution here. Could somebody please advice on how to reset the value of a file input after a form submission?

**Comment by ooflorent** [comment]
Since file inputs cannot be managed like other input types, you need to trick React to create a new one. You can add a `key` property (and update it if you need to reset the input) to prevent `react-dom` from reusing it.

**Comment by larkintuckerllc** [comment]
I used this technique, i.e., I created a flag in the store called "lastPdfAddTime";  set to the timestamp of the last upload (initially set to -1).  Then I pushed this flag down to the form component and used it on the <Field> for the file upload input (set as a key).  

This solved my first problem, getting the input to reset it's value.  I can see that it reset because my validate function (passed to reduxForm) now sees the value as undefined.  Yeah!  BUT...

Seems that even though I pass an error on the file, e.g., "errors.file = 'Required.'", the form itself stays valid.  Unexpected.

My planned work-around that I am going to try is have a secondary read-only <Field> that is set to the filename of the upload (a normal UI experience) be what I am triggering on for my validation.

Wondering if there is someone who is better at this environment can provide a better work-around (or illuminate me on what is going on).

**Comment by larkintuckerllc** [comment]
BTW... I figured out my problem with trying to use the "key" solution.  The mistake was that I was setting the "key" on the "<Field>" component (thus reloading the whole component and apparently mucking with the error passing).  The fix was to use the option to include a separate component via the Field "component" attribute and apply the "key" work-around to just the <input> itself.

**Comment by jsushankprdxn** [comment]
@larkintuckerllc Can you please elaborate the way of doing the above you just explained or any example of your code would be really appreciated. 

Thanks in advamce

**Comment by jsushankprdxn** [comment]
Ahhhhh Got it resolved the issue with the below code
document.getElementById('files-upload').value = null;

This worked for windows. 
Cheersssss.

**Comment by gor181** [comment]
How we solved it is:

```
const fileInputKey = input.value ? input.value.name : +new Date();
...

<input
  key={fileInputKey}
  type="file"
  className="hidden"
  onChange={(event) => input.onChange(event.target.files[0])}
  ref={ref => (this.fileInput = ref)}
  accept={accept}
/>
```
