### ISSUE TITLE
Disable form initialization while submitting

### ISSUE THREAD

**Issue by jfrolich** [erikras/redux-form#770]
Hi,

Thanks for the great work on redux-form. When initialValues are updated, INITIALIZE is called. This is great as it updates the form to the current version of the data. I have an edge case where the underlying data can change during submission, INITIALIZE resets the submitting flag, and thus it looks like the form is finished submitting. Is it possible not to INITIALIZE the form state while the form is submitting? (Would you accept a push request for that?)

Cheers,

Jaap

**Comment by gustavohenke** [comment]
I assume that by the age of the question, you were probably using v5.
I never used it, but in v6 you can use `enableReinitialize` option. You could try using react-redux `connect` to set it to `true` only while not submitting. However, I don't know if it'll work (never tried).

Since you never manifested yourself again in this issue, I'll also assume you found a way out.
If you did, please let us know by posting your solution.
