### ISSUE TITLE
asyncBlurFields doesnt do anything for complex fields probably

### ISSUE THREAD

**Issue by WirthAware** [erikras/redux-form#774]
Hey, i'm started using this repo and have to say its really awesome to use so far, thank you! 

Maybe I'm missing something but I have a check for payment information in a form. 
I'm using complex fields like:

  'Payment.Iban',
  'Payment.Bic',
...

The payment information should be validated async by the server, so i tried to use Asynchronous Blur Validation from the examples. It works fine when i use just a simple field like 'Iban' without nested properties. So just 'Iban' would work. 

How to use nested fields like 'Payment.Iban'? It will not work for me. 
Here is what i'm putting in asyncBlurFields

asyncBlurFields: ['Payment.Iban']

I did'nt get any 
redux-form/START_ASYNC_VALIDATION or 
redux-form/STOP_ASYNC_VALIDATION
events. 
Any idea what i'm doing wrong?

**Comment by WirthAware** [comment]
May it helps, when i'm clicking submit the asyncValidate is called but not on blur.

**Comment by gustavohenke** [comment]
In v6, it's working: https://jsfiddle.net/gustavohenke/7jqx8whb/

**Comment by morgante** [comment]
@gustavohenke What's the status of maintenance/bugfixes on the v5 branch? v6 is a massive migration and I really don't like how this project has pushed a massive rewrite while v5 still had bugs.

Especially since v6 forces you to upgrade to redux-hot-loader beta... which forces you to upgrade to react-router v4.

It seems like getting this small fix will require rewriting my entire project. Why is the only production release of this one which *forces* you to use beta versions of other tools? This is v5, not v0.5...

**Comment by WirthAware** [comment]
@gustavohenke we also have a old project on v5 we cant migrate to v6. 

What we do at the moment is a lot of workarounds to handle the issues. 
The workaround for that issue is to do a ajax request and dispatch stopSubmit if there are validation errors.

**Comment by gustavohenke** [comment]
https://github.com/erikras/redux-form/pull/2645#issuecomment-284908300

And @morgante, I was not the one who fixed this issue, so I don't know what commit did it.
