### ISSUE TITLE
V6 validation for dynamically generated forms

### ISSUE THREAD

**Issue by lithin** [erikras/redux-form#838]
Great job on putting together V6 alpha! It brings a lot of exciting changes and I'm really happy with 95% of them :) My only concern is that some of the changes seem to make dynamically generated forms impossible.

In our use case, we generate forms based on a JSON schema and we never know in advance (that is when we're combining reducers) which forms will end up rendered. In V5, we're able to do this thanks to the fact we don't really have to specify the name of the form in reducers - apart from normalisation which we had to do separately in our validation. As you've moved validation function definition to the reducer, it seems that we can no longer by-pass this issue.

To get more info on what we're doing, I've done a talk on this topic - https://docs.google.com/presentation/d/1UZclbAbfiZlz36Jq_TAG_kaAYDsibShtSMNqs2zR0IY/edit (slides) and https://www.youtube.com/watch?v=kkqArkYV4fw (video - talk starts at about 33 min).

We can obviously keep using V5 but I got excited by some of the features (especially the Field component and enhanced performance) so I'd love to upgrade once it's a stable build.

Apologies if this isn't an issue-material, I'm happy to continue the discussion elsewhere and close this issue if you prefer :)

**Comment by erikras** [comment]
I enjoyed that. Thank you! Your criticisms were all good ones. As far as I know, you are the first presenter to talk about `redux-form`. It's very strange hearing someone else teach your library. 😄 

I'm going to leave this issue open because it does highlight a problem with `v6`. At the last minute, after I had already implemented the reducer-side validation, I figured out a way to have the sync validation be provided as it was in `v5`, but I decided not to put that into `alpha.4`, and I'm glad to see that people noticed.

Again, great talk. 👍 👍

**Comment by davidkpiano** [comment]
@erikras Re. sync validation, I think it might be a good idea to handle validation _outside_ of the reducer, and instead set validation via actions. This will allow both sync and async validation to be first-class w/r/t validating any field/form.

It will also allow validity to be set at any time, by dispatching that action, so that validation can be handled externally. This would require undoing validation inside the form reducer though 😟

**Comment by lithin** [comment]
Thanks @erikras ! I think you can expect more talks on this topic soon ;)

I agree with @davidkpiano that validation would be good as an action - after all, it is an "action", not "state. Validation is only relevant to the form and its fields as far as you can tell if they are valid but you shouldn't really need to know how this state was achieved? Not sure it makes any sense at all :D

**Comment by erikras** [comment]
> I think it might be a good idea to handle validation outside of the reducer, and instead set validation via actions.

You mean like,
```js
dispatch(markInvalid('foo.bar'))
```
or
```js
dispatch(setError('foo.bar', 'Required'))
```
? Or do you mean some other way?

**Comment by davidkpiano** [comment]
In RRF I have:

```js
dispatch(setValidity('foo.bar', true)); // sets foo.bar to valid
dispatch(setValidity('foo.bar', { required: false }));
// => sets foo.bar to invalid and the 'required' validity key to false

dispatch(setErrors('foo.bar', 'This is invalid'));
// => sets foo.bar to invalid and the .errors prop to 'This is invalid'

dispatch(setErrors('foo.bar', {
  required: 'This field is required'
});
// => sets foo.bar to invalid and sets the .errors.required prop to the message
```

**Comment by erikras** [comment]
@davidkpiano So is the idea that the validation function doesn't return anything, it is just given the value(s) and `dispatch` and expected to dispatch `setValidity` and/or `setErrors`?

**Comment by davidkpiano** [comment]
Right.

**Comment by erikras** [comment]
`v6` validation back to how it was in `v5`. [`v6.0.0-alpha.5`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.5)

**Comment by mihirsoni** [comment]
@erikras  This is great. It would have also made wizard form little hacky to make validation. Because when we give validation to reducer, we will never be able to validate the partial form. Thank you for this.

**Comment by randycoulman** [comment]
I just noticed that the migration guide still talks about the reducer-based validation.  I was going to create an issue to discuss it, but then saw the note in the alpha.5 release notes.

**Comment by erikras** [comment]
@randycoulman Yes, the sync validation in v6 is now just like in v5.

**Comment by randycoulman** [comment]
@erikras Yes, I understand that. My point is that the current version of the migration guide is now wrong, because it talks about that change as if it is still in place.
