### ISSUE TITLE
Leaving a form takes two clicks

### ISSUE THREAD

**Issue by jcalfee** [erikras/redux-form#860]
We have a Cancel button and an empty but required field in focus.  When we click the Cancel button the first time its event is not received.  Instead, the required field shows its error saying this field is required.  The next Cancel click will go through.

I believe the onBlur event is firing and redux form handling the event but stopping it from propagating.  Is this a known behaviour?  How to work-around?  Is their a way I can validate the form only on submit?

This button does not have type="submit", just a button:
```js
<button onClick={(e) => {e.preventDefault(); this.props.onCancel()}}>Cancel</button>
```
Also happens if I move the button outside of the <form block...

**Comment by jcalfee** [comment]
It appears to work if I add `onBlur=""` after the props `<input {...myfield} onBlur="".  If you know of unforeseen side-effects it would be good to know about it.  Thanks..

**Comment by fhelwanger** [comment]
If the button doesn't have a type="submit" attribute, then the button is type="submit".

The default type is submit, if you need it to be type="button", you must specify it.

**Comment by erikras** [comment]
I have seen this, too. It must have to do with the `blur` causing a rerender of the dom, which somehow halts the `click` event on the button. If we're going to track focus, then an action must be fired on `blur`, so I'm not really sure what can be done about this. It might be a wider React problem?

**Comment by jcalfee** [comment]
It is not an really an issue if it triggers the validation as long as the click event can propagate to other handlers.

**Comment by jcalfee** [comment]
Changing to `<button type="button"` fixed it, I do have this button within the form elements.
It it is harmless, you might check to see if their is a preventDefault() or stopPropigation() that could be making this a bit more fragile.

Feel free to close the ticket.  Thank you..

**Comment by erikras** [comment]
There is a `preventDefault()` on the `onSubmit`, but that's obviously needed to not submit the form ye olde html way. Glad the `type="button"` worked out.

**Comment by jcalfee** [comment]
I have a case where my cancel button is `type="button"` but I was still seeing the form validation run before the dialog closed.  I did auto-focus a field.  If the form resizes sometimes the cancel button does not work.  I did find a work around:
```js
        const blur = password.onBlur // slowing the blur event makes it easy to cancel
        password.onBlur = e => setTimeout(() => blur(e), 250)
```

**Comment by jcalfee** [comment]
Shoot .. I'm getting random annoying error from the onBlur work-around.
```
Uncaught TypeError: Cannot read property 'type' of null
getValue	@	getValue.js:33
(anonymous function)	@	createOnBlur.js:13
(anonymous function)	@	UserKeys.jsx:232
```

**Comment by erikras** [comment]
That means `event.target` is null. I wonder if, by delaying it, the event gets mutated (target unset) in the interim 250ms? That sort of sucks.

Worst case is you have to save it. Or you might as well just save the value.
```js
password.onBlur = e => {
  const value = e.target.value
  setTimeout(() => blur(value), 250)
}
```

**Comment by legalcodes** [comment]
I'm having this same issue. I'm unable to save the value using your example above because the event.target is coming in as null.

**Comment by StefanYohansson** [comment]
I have the same problem here. I was trying to figure out where is the problem, so I wrote two codepens.

1. React
http://codepen.io/syohansson/full/bBgEBm/
2. jQuery
http://codepen.io/syohansson/full/MbJyyj/

tested on Chrome and Firefox.

**Comment by jkoontz2010** [comment]
Good news, everyone who's hung up here:
The issue happens because validation intercepts the event (magically).

To prevent this, set up your validation to not occur if field is pristine:

`
export const inputField = ({ input, label, type, autoFocus, meta: { touched, error, pristine } }) => (
    <div className="group"> 
        <input {...input} type={type} required autoFocus={autoFocus} />
        <label>{label}</label>
        {touched && !pristine && ((error && <span className="field-error">{error}</span>))}
    </div>   
)
`

**Comment by cdaringe** [comment]
ya this is a tricky one.  its as though something in the `onBlur` is preventing the click event from propagating. i dont see in the `onBlur` code anything that would prevent the click event from reaching its original target's handler. 🤔

**Comment by kmsheng** [comment]
Another workaround is to check event.relatedTarget in `onBlur`, if its relatedTarget has type="button", set event.preventDefault().

```
  handleBlur = (event) => {
    const {relatedTarget} = event;
    if (relatedTarget && ('button' === relatedTarget.getAttribute('type'))) {
      event.preventDefault();
    }
  };
```

**Comment by R4DIC4L** [comment]
On a second thought, maybe skipping the validation on input type button is not always desired. You could have a button to add a new line of data in the form, and that would not be a submit button, nor would you like it to perform the add action unless the above line is filled.

Maybe we could, instead, add some custom property on the button/any other element to state that it is a cancel button and when clicking on it validation should not occur (this could be checked in the onBlur event as @kmsheng has pointed out, only the attribute name would be different). Any thoughts?

**Comment by ryanhomer** [comment]
@dpikt's solution is the only one that worked for me. Nothing mentioned prior to that worked; I didn't try anything mentioned after.

It seems to be the simplest solution and makes sense (don't take any action on a pristine field) -- unless you're using `onBlur` for something that needs to take place whether or not you've typed anything.

**Comment by altaurog** [comment]
I am using redux-form 7.0.4.  It seems that something changed with v7 because setting `onBlur` on the input in the wrapped component doesn’t seem to do anything, so @dpikt’s solution isn’t feasible.  On the other hand, using @kmsheng’s function as `onBlur` on the `Field` does work for me.

@jkoontz2010’s solution also works for me, which is even more interesting.  It isn’t at all clear from looking at that why it works, but I did a little experimentation.  It seems that displaying the error was pushing subsequent components down and pushing my button out from under the cursor.  In fact, when I click towards the bottom of my button, it doesn’t clear the cursor when it moves and it works.  So the chain of events seems to be:
 mousedown -> blur event -> validation -> DOM insertions -> _no mouseup event on the button_!
@kmsheng’s solution works by stopping the chain before validation and @jkoontz2010’s solution works by stopping the chain before DOM insertion.  But I was also able to resolve the problem by putting the error message inside a `div` with fixed height or by setting `position: absolute` so that the DOM insertions don’t move my button.

**Comment by ashwinputhige** [comment]
I had to change the button handler from `onClick` to `onMouseDown` to re-order the `click` and `blur` events

**Comment by ArtemBernatskyy** [comment]
@ashwinputhige but this won't work for touch and pointing devices.

**Comment by Dimasion** [comment]
I have similar issue when I double tapped on button to submit the form.

**I had button with SVG icon.**

**Behavior**: First tap triggered SVG, second triggered button with type 'submit'.
**Solution**: in Button component apply` pointer-events: none` for icon.

**Comment by rafecolton** [comment]
@kmsheng's solution worked for me!

> Another workaround is to check event.relatedTarget in `onBlur`, if its relatedTarget has type="button", set event.preventDefault().
> 
> ```
>   handleBlur = (event) => {
>     const {relatedTarget} = event;
>     if (relatedTarget && ('button' === relatedTarget.getAttribute('type'))) {
>       event.preventDefault();
>     }
>   };
> ```

If the user clicks out of the field, it validates, but if they click the cancel button, it doesn't validate and the cancelation is successful.

**Comment by Pasquale-Guglielmi** [comment]
> That means `event.target` is null. I wonder if, by delaying it, the event gets mutated (target unset) in the interim 250ms? That sort of sucks.
> 
> Worst case is you have to save it. Or you might as well just save the value.
> 
> ```js
> password.onBlur = e => {
>   const value = e.target.value
>   setTimeout(() => blur(value), 250)
> }
> ```

Please discourage this workaround. It causes other issues, e.g. in the case you've also got a button that triggers the "onClick" on a "type=file" input:
1) you start typing inside a form field
2) you click on the button
3) the file picker dialog shows up
4) you select the file and.........nothing happens, the "file input" onChange doesn't get triggered.
5) you remove the callback from the form fields' "onBlur", re-try from 1) to 4) and........now it works, the file input gets updated correctly. 

This side effect was a deal breaker for me.

**Comment by jsiddiqui** [comment]
Ran into this issue and figured out what is happening here. First `mousedown` causes the focus to be lost and `onBlur` fired. The `onBlur` handler causes errors to be displayed shifting the DOM a bit. Then `mouseup` is fired but due to DOM shifting, the mouse is often on another element. The synthetic `onclick` is only fired if `mousedown` and `mouseup` are both registered on the same element. The `onclick` event will always work if the clicked element is absolutely positioned or positioned above the form or the errors are shown in a way that the clicked element does not shift its position. It may still work if the target element is big enough such that it stays under the mouse after DOM shifting.

**Solution:** Add `onMouseDown={(e) => e.preventDefault()}` to the element with the `onClick` handler. This stops the `onBlur` from firing only when this button is clicked and the button retains its coordinates for the `mouseup` to eventually register it as a `click` event. If you want the `onBlur` as well, you can fire it yourself from the `onClick` handler. Touch should keep working.

**Comment by danidanimoraes** [comment]
Thank you so much @jsiddiqui. Such a simple solution when I was losing all hope.

**Comment by tomatobybike** [comment]
Good Job ，Thanks

**Comment by tomatobybike** [comment]
Good Job ，Thanks @jsiddiqui

**Comment by Deandrewily115** [comment]
@dpikt https://jquerys.space/questions/identify-updated-selections-in-a-dropdown-menu-using-jquery
