### ISSUE TITLE
Persist data state in session

### ISSUE THREAD

**Issue by Ezekiah** [erikras/redux-form#864]
hi again, I wonder if theres is a way to keep form input values event when the user actualize the website. Before using redux I used to to that with localstorage but now I don't really know how to connect redux to localstorage, can you guide me a bit please ? I use your react hot starter template, I think I might use express session to do that.

**Comment by mihirsoni** [comment]
@Ezekiah  Simplest way will  just use React´s lifecycle methods (```componentWillUnMount```)

You can use some external library for more powerful functionality https://github.com/elgerlambert/redux-localstorage/tree/1.0-breaking-changes.

**Comment by ooflorent** [comment]
Please try to use StackOverflow for questions. Github issues should be use for reporting bugs.

As @mihirsoni suggested, you can use React's lifecycle methods to serialize and deserialize your form values. You could also store the state of `redux-form`'s reducer. However, be careful when doing this because it may break on future updates.

**Comment by fabarea** [comment]
I faced the exact same need. Reporting this request as issue could lead to documentation improvement, so it is not useless IMHO.

**Comment by mihirsoni** [comment]
@fabarea Certainly this will out of scope for redux-form. This is a solution for the implementation.  Making this docs doesn't make any sense because the implementation might very cases to cases.
