### ISSUE TITLE
Immutable Form Submit error v6

### ISSUE THREAD

**Issue by NgoKnows** [erikras/redux-form#881]
When trying to call handleSubmit like in the example, I get this error 
`Uncaught TypeError: Object.values is not a function`
I'm not sure what could be causing this. I am using v6 alpha.6

**Comment by ooflorent** [comment]
v6 uses `Object.values` but to use the `runtime` transform from Babel. `Object.values` is a new addition to EcmaScript specification (ES2017) and may not be implemented in all browsers (currently it is only available in FF 47).

Use have to manually provide the polyfill using:

```js
import "babel-polyfill"
```

@erikras Is it the expected behavior? Do you want v6 to depend on the polyfill? Maybe we should consider using `lodash` or an internal helper for this.

**Comment by kristian-puccio** [comment]
Does anyone write react anymore without babel?

**Comment by ooflorent** [comment]
@kristian-puccio Using Babel does not involve using the polyfill nor the runtime transform!

**Comment by kristian-puccio** [comment]
Sorry your correct, we can probably assume people will use babel to get to
es2015 but I guess assuming es2016 is probably a stretch.

**Comment by ooflorent** [comment]
And `Object.values` is ES2017 (but stage 4)!

**Comment by erikras** [comment]
Easy fix. I'll move it back to Object.keys(). Already committed, but not ready for push yet.

**Comment by erikras** [comment]
Fix published as [`v6.0.0-alpha-7`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.7).

**Comment by jedwards1211** [comment]
@kristian-puccio just a note, I try to avoid using `babel-polyfill` if I can help it, and rely on `babel-runtime` only (which unfortunately isn't possible with `redux-form` right now)
