### ISSUE TITLE
Getting form values breaks when using a form field with the name of "value"

### ISSUE THREAD

**Issue by Aaronius** [erikras/redux-form#887]
I currently have a nested field named `value`:

`foo.bar.value`

When calling `getValues` for the form, `foo.bar.value` is not the value of the value field. The problem comes from https://github.com/erikras/redux-form/blob/e61517b23e4e3cde0c422658d624434fec18d1ea/src/getValuesFromState.js#L17-L20 when `getValues` is recursing through the fields. When it gets to the `bar` object, it sees that it has a value prop and assumes that `bar` itself is a field and that `value` is the value rather than detecting that `value` is actually a field.

Is there a better way to detect when a field is reached than just looking to see if has a `value` property?

**Comment by erikras** [comment]
Yes, that's what [`isFieldValue()`](https://github.com/erikras/redux-form/blob/master/src/fieldValue.js#L11-L13) is for. This must have been overlooked.

**Comment by Aaronius** [comment]
Thanks @erikras!

**Comment by Aaronius** [comment]
I've confirmed that this has fixed the issue. Thanks again for fixing and publishing so quickly.

**Comment by erikras** [comment]
You got lucky. 😄

**Comment by johanneslumpe** [comment]
@erikras This seems to break the usage of `getValues` with forms which are initialized on the server and the hydrated on the client. I have a form which has a `type` field and that gets initialized on the server. On  the client i see the correct `initialValue` and `value` props in the reducer, but `_isFieldValue` is missing. This breaks part of the application I'm working on, as the field is no longer returned via `getValues`.

Was this intentional or is this a bug/edge case? I hope you will be able to provide some insights here, because this really caught us off-guard :/

**Comment by MitchWeiss** [comment]
I can confirm @johanneslumpe's findings. After upgrading to 5.2.5 `getValues` returns an empty object. Downgrading to 5.2.2 before this change was made fixes the issue.

**Comment by erikras** [comment]
Fix published in [`v5.3.0`](https://github.com/erikras/redux-form/releases/tag/v5.3.0).
