### ISSUE TITLE
[v6] FieldArray using redux-form/immutable not re-render when push 

### ISSUE THREAD

**Issue by eric4545** [erikras/redux-form#913]
Hello @erikras i am trying use `redux-form@6.0.0-alpha.7`, but i found some problem when using immutable. The `FieldArray` value seem to be a normal JS array not immutable list, when doing `shouldComponentUpdate`  `size`  will be undefined .

**Comment by erikras** [comment]
Can you be more specific? The `FieldArray` doesn't present a "value" per se; it provides a pseudo array (with `length`, `map`, and `forEach`).

When you say "`size` will be undefined", it makes me think that you might be referring to the problem reported in #892, which I fixed with https://github.com/erikras/redux-form/commit/d3bf0676de26ac09b1a2f481288c1fecfa61b057, but has not yet been released as a new version.

**Comment by erikras** [comment]
Fix published as [`v6.0.0-alpha.8`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.8).
