### ISSUE TITLE
v6 is there anyway you can pass a validation function to the ``Field`` component?

### ISSUE THREAD

**Issue by darylhedley** [erikras/redux-form#917]
Would be great to be able to do something like this:

```
function validateFunctionJustForThisField(value) {
    var error = '';
    if (value.length === 0) {
        error = 'Required'
    }
    return error;
}

<Field component={MyFormComponent} validate={validateFunctionJustForThisField}/>
```

This would make dynamic forms much easier to construct.

**Comment by erikras** [comment]
That functionality is planned, but not yet implemented.

**Comment by darylhedley** [comment]
Excellent - so keen to start using v6 as we build dynamic forms for all three of our apps and the new Field component is a great addition! Thanks again for the work on Redux Form

**Comment by kristian-puccio** [comment]
Another things that would be nice is to pass the asyncBlur option to a field so you don't have to add a string to asyncBlurFields

**Comment by fenos** [comment]
@erikras i was trying to work on this, because i need the same feature for dynamic forms.
The following spec is how i thought to approach it, reading redux-form source for the first time.
Sorry if I miss some concept, please advice me and i will happy to PR on this.

## Implementation
- I tried to implement the `validate` function on the `Field` component, during the **registration** of the field adding the [validate](https://github.com/fenos/redux-form/blob/9de406b926d7f254859854179d1edfa57dd3aa93/src/Field.js#L27) prop into the register function.

- The validation of the fields is triggered on [validateIfNeeded](https://github.com/fenos/redux-form/blob/9de406b926d7f254859854179d1edfa57dd3aa93/src/reduxForm.js#L158) function.

- I reduce all the registered fields and pass their value to them so that the field can consume it into the component as following:
[validateFieldsErrors](https://github.com/fenos/redux-form/blob/9de406b926d7f254859854179d1edfa57dd3aa93/src/reduxForm.js#L125)
```js
<Field component={input} validate={value => {
   if (!value) {
     return 'Required';
   }
}} />
```

On every input change the validation is triggered correctly per field.

## Problem
My biggest problem is that i can't run the **validate** function of each `<Field>` component on the first render, cause the Fields are not yet registered when `redux-form` mount.

If this is not possible/easy todo with react-redux is there a way that i can prevent to go next page of my **wizard** if all the fields hasn't been touched and are **Required**? I can't hard code each field name into the current **redux-form validate fn** cause the definition came from the server.

[Commit reference](https://github.com/fenos/redux-form/commit/9de406b926d7f254859854179d1edfa57dd3aa93) Sorry the typo on the commit

**Comment by pulse00** [comment]
@fenos thanks for tackling single field validation - this feature would also be a great addition for our use cases.

@erikras is the direction @fenos is heading to the right one? if so, i'd be happy to help out in updating the v6 documentation.

**Comment by frankjwu** [comment]
This looks really interesting @fenos! We're exploring something similar and would love to see something like this in the next release candidate.

@erikras, any thoughts on this approach?

**Comment by dkwin** [comment]
Just to add to this, 

in the validate (values, nextProps) function, there is a field called registeredFields (which only has the name and type).  It'd be nice to have the entire props of the field so that why we can also call the validate function manually if needed.  

it'd be nice if in the 

`validate (values, nextProps) => {
  let errors = {};
for (key: Object.keys (values)) {
  errors.push (nextProps.registeredFields[key].props.validate (values[key]))'
}

}`

**Comment by gustavohenke** [comment]
v6.3.0 finally included Field level validation 😎
