### ISSUE TITLE
Dispatch action from redux-form plugin?

### ISSUE THREAD

**Issue by Deadarius** [erikras/redux-form#953]
Is there any way to do that?
Thank you.

**Comment by leesiongchan** [comment]
Are you saying [this](http://redux-form.com/6.0.0-alpha.9/docs/api/ActionCreators.md/)?

**Comment by erikras** [comment]
Yes, @Deadarius, you need to give more context to your questions.

I think you might be referring to the [`plugin()` API](http://redux-form.com/5.2.3/#/api/reducer/plugin) (not yet implemented in `v6`), in which case, no, you can't dispatch an action because that code is running inside the reducer, and reducers can't dispatch. My understanding is that if you need to listen for an action and then dispatch another one, you need middleware.
