### ISSUE TITLE
Autofill with array of fields

### ISSUE THREAD

**Issue by fitz0019** [erikras/redux-form#991]
I've searched the issues and I can't find one related. I'm using the autofill action to populate all the fields after an address lookup. If there are two fields I need to update to I need to dispatch an action for each field. Is there a way to dispatch one action which accepts an array?

Perhaps an array of objects which look like:
```js
[
  ...
  {
    field: 'addressLine1',
    value: 'First line of address'
  }
...
]
```

What do you think?

**Comment by erikras** [comment]
In general, I don't think that fear of dispatching many successive actions is warranted. For example, I don't think that each one is going to cause a rerender, because the rerender happens on the next process tick. However, it certainly seems like you could wrap the `redux-form` reducer in an [action batching higher order reducer](https://github.com/tshelburne/redux-batched-actions) with no modifications whatsoever to this library. If you choose to do that, I'd love to know how it goes.

**Comment by fitz0019** [comment]
Thanks for the quick reply. Your explanation makes sense and I agree perhaps my fear was unwarranted. I'll see how I get on!

**Comment by d-leeg** [comment]
Unfortunatley, using a batching reducer like @erikras suggested is not possible in the most common use-case of calling the redux-form bound action creators passed as props to one's form.

Instead, one has to resort to the less convenient (and less recommended) unbound versions, as well as wrap the form with a react-redux` connect()` to pass down the dispatch method of the store.

However, I do agree that multiple dispatches will not cause multiple renders in most cases, but they will cause multiple subscriber notifications.
